/* ---------- studio v1.2: six-step operator flow (appended to app.js inside the same closure) ---------- */
var SLOTS={gcp:[{k:'m',part:'service',en:'Month · all GCP by service',req:true},{k:'m',part:'project',en:'Month · all GCP by project',req:true},{k:'m',part:'sandbox',en:'Month · sandbox by service',req:true},{k:'q',part:'service',en:'Quarter · all GCP by service',req:false,q:true},{k:'q',part:'project',en:'Quarter · all GCP by project',req:false,q:true},{k:'q',part:'sandbox',en:'Quarter · sandbox by service',req:false,q:true},{k:'t',part:'service',en:'Contract to date · all GCP by service',req:true},{k:'t',part:'project',en:'Contract to date · all GCP by project',req:false},{k:'t',part:'sandbox',en:'Contract to date · sandbox by service',req:false}],
 azure:[{k:'m',part:'service',en:'Month · by service',req:true},{k:'m',part:'sub',en:'Month · by subscription',req:true},{k:'m',part:'region',en:'Month · by resource location',req:false},{k:'q',part:'service',en:'Quarter · by service',req:false,q:true},{k:'q',part:'sub',en:'Quarter · by subscription',req:false,q:true},{k:'t',part:'service',en:'Contract to date · by service',req:true},{k:'t',part:'sub',en:'Contract to date · by subscription',req:false}]};
var TOKENS=['month','prevMonth','gcp.net','gcp.gross','gcp.discounts','gcp.change','gcp.sandbox','gcp.top.name','gcp.top.share','gcp.td.net','gcp.credit.remaining','gcp.credit.pct','gcp.credit.consumption','gcp.credit.committed','gcp.credit.uncommitted','azure.net','azure.change','azure.top.name','azure.top.share','azure.credit.remaining'];
var REQ={gcp:{m:['service','project','sandbox'],t:['service']},azure:{m:['service','sub'],t:['service']}};
var CREDIT_EDITORS=[
 {path:'purchaseOrders',title:'Purchase orders',sub:'From the procurement ledger. The $ column is the ledger value net of 15% VAT; the report converts it at the peg.',cols:[{f:'name',l:'Purchase order'},{f:'sar',l:'Price (Riyals, with VAT)',t:'number'},{f:'usd',l:'Price ($, net of VAT)',t:'number'},{f:'status',l:'Status',t:'select',o:[['live','Live'],['full','Fully utilized']]}],add:'Add a purchase order',blank:{name:'',sar:null,usd:null,status:'live'}},
 {path:'fixed',title:'Drawdowns not visible in the billing dashboard',sub:'Support and one-time payments drawn from the credit that never appear as usage. Subtracted from the balance as they are.',cols:[{f:'name',l:'Item'},{f:'usd',l:'Amount ($)',t:'number'},{f:'noteEn',l:'Note'}],add:'Add a drawdown',blank:{name:'',usd:null,noteEn:''}},
 {path:'commitments',title:'Commitments paid monthly as used',sub:'Contracted totals. What has been used is read from the contract-to-date export, matched on the billing service name.',cols:[{f:'name',l:'Commitment'},{f:'usd',l:'Total ($)',t:'number'},{f:'servicesText',l:'Billing service name(s), comma separated'}],add:'Add a commitment',blank:{name:'',usd:null,services:[],servicesText:''}},
 {path:'incentives',title:'Google incentives',sub:'Credits Google provided. They already sit inside the usage figures as savings; listed here as a source.',cols:[{f:'name',l:'Incentive'},{f:'usd',l:'Amount ($)',t:'number'},{f:'status',l:'Status',t:'select',o:[['full','Fully utilized'],['live','Open']]}],add:'Add an incentive',blank:{name:'',usd:null,status:'full'}}];
function slotKey(k){var E=S.edition;return k==='m'?E.month:k==='q'?quarterKey(E.month):'td';}
function slotLabel(c,part,k){var s=SLOTS[c].filter(function(x){return x.part===part&&x.k===k;})[0];return s?s.en:(c+' · '+part);}
function cloudName(c){return c==='gcp'?'Google Cloud':'Microsoft Azure';}
function newPeriod(c,k,key){var C=S.clouds[c];return {key:key,kind:k==='m'?'month':k==='q'?'quarter':'todate',label:k==='m'?monthLabel(key):k==='q'?quarterLabel(key):(C.tdLabelEn||'Contract to date'),labelAr:k==='m'?monthLabel(key,true):k==='q'?quarterLabel(key,true):(C.tdLabelAr||'منذ بداية العقد'),services:[],files:{},raw:{},sample:false,source:'upload'};}
function ensurePeriod(c,k,key){var P=S.clouds[c].periods,p=P[key];if(!p||p.source!=='upload')p=P[key]=newPeriod(c,k,key);if(!p.raw)p.raw={};if(!p.files)p.files={};return p;}

/* ---------- classification and placement ---------- */
function monthsBetween(a,b){var x=ym(a),y=ym(b);return (y[0]-x[0])*12+(y[1]-x[1])+1;}
function nextMonth(iso){var p=ym(iso),y=p[0],m=p[1]+1;if(m>12){m=1;y++;}return y+'-'+(m<10?'0':'')+m;}
function classify(name,rows){var E=S.edition,head=Object.keys(rows[0]||{}),has=function(n){return head.indexOf(n)>=0;},lower=name.toLowerCase(),cloud=null,part=null;
 if(has('Subtotal ($)')&&has('Project ID')){cloud='gcp';part='project';}
 else if(has('Subtotal ($)')&&has('Service description')){cloud='gcp';part='service';}
 else{var hs=head.map(function(h){return h.toLowerCase().replace(/[^a-z]/g,'');}),hasN=function(c){return hs.some(function(h){return c.indexOf(h)>=0;});};
  if(hasN(['costusd','cost','pretaxcost','costinbillingcurrency','actualcost','costinusd'])){cloud='azure';part=hasN(['subscriptionname','subscription','subscriptionid'])?'sub':hasN(['resourcelocation','location'])?'region':hasN(['servicename','metercategory','service','servicefamily'])?'service':null;}}
 if(!cloud||!part)return null;
 if(cloud==='gcp'&&part==='service'){var gross=rows.reduce(function(a,r){return a+fnum(r['List cost ($)']);},0);if(/sandbox|spark|iw-sb|sb-dev|_sb[._-]/.test(lower)||(rows.length<=14&&gross<25000))part='sandbox';}
 var dates=name.match(/\d{4}-\d{2}-\d{2}/g)||[],k='m',key=E.month,detected=null;
 if(dates.length>=2){var a=dates[0],b=dates[dates.length-1],am=a.slice(0,7),bm=b.slice(0,7),n=monthsBetween(am,bm);detected=a+' to '+b;
  if(n<=1){k='m';key=am;}else if(n===3&&(ym(am)[1]-1)%3===0){k='q';key=quarterKey(am);}else if(n===6&&(ym(am)[1]===1||ym(am)[1]===7)){k='q';key=ym(am)[0]+'-h'+(ym(am)[1]===1?'1':'2');}else{k='t';key='td';}}
 else{var one=name.match(/(\d{4})-(\d{2})(?!-?\d)/);if(/to-?date|todate|contract/.test(lower)){k='t';key='td';}else if(/\bq[1-4]\b|quarter/.test(lower)){k='q';key=quarterKey(E.month);}else if(one){k='m';key=one[1]+'-'+one[2];}}
 var warn=null;if(k==='m'&&key!==E.month)warn='covers '+monthLabel(key)+' but the edition is '+monthLabel(E.month);
 return {cloud:cloud,part:part,k:k,key:key,warn:warn,detected:detected};}
function normalizeRows(cloud,part,rows){if(cloud==='gcp')return part==='project'?gcpProjects(rows,FX()):gcpServices(rows,FX());var parsed=azureRows(rows,FX(),S.edition.azureCurrency);return parsed.rows.map(function(r){return {name:r.name,id:r.id||'',net:r.net,gross:r.net,chg:'n/a'};});}
function place(cloud,part,k,key,fileName,data){var p=ensurePeriod(cloud,k,key);
 if(cloud==='gcp'){if(part==='project')p.projectsRaw=data;else if(part==='service')p.services=data;else p.sandboxServices=data;}
 else{if(part==='service')p.services=data;else if(part==='sub')p.subsRaw=data;else p.regions=data;}
 p.raw[part]=data;p.files[part]=fileName;p.sample=Object.keys(p.files).some(function(x){return /^sample_/i.test(p.files[x]);});
 if(k==='t'){p.label=S.clouds[cloud].tdLabelEn||p.label;p.labelAr=S.clouds[cloud].tdLabelAr||p.labelAr;}
 if(cloud==='gcp')recomputeGcp(p);else recomputeAzure(p);return p;}
function unplace(cloud,key,part){var P=S.clouds[cloud].periods,p=P[key];if(!p)return;
 if(cloud==='gcp'){if(part==='project')delete p.projectsRaw;else if(part==='service')p.services=[];else p.sandboxServices=[];}
 else{if(part==='service')p.services=[];else if(part==='sub')delete p.subsRaw;else delete p.regions;}
 if(p.raw)delete p.raw[part];delete p.files[part];
 if(!Object.keys(p.files).length){delete P[key];return;}
 p.sample=Object.keys(p.files).some(function(x){return /^sample_/i.test(p.files[x]);});if(cloud==='gcp')recomputeGcp(p);else recomputeAzure(p);}
function ingestOne(file,forced){return file.text().then(function(text){var rows=parseCSV(text);if(!rows.length)throw new Error('the file has no data rows');
  var route=forced?{cloud:forced.cloud,part:forced.part,k:forced.k,key:slotKey(forced.k),warn:null}:classify(file.name,rows);
  if(!route)throw new Error('not a GCP Reports CSV (needs Service description or Project ID plus Subtotal ($)) and not an Azure Cost analysis CSV (needs a name column plus Cost or CostUSD)');
  if(route.cloud==='gcp'){if(route.part==='project'&&!('Project ID' in rows[0]))throw new Error('this is not a by-project Reports CSV');if(route.part!=='project'&&!('Service description' in rows[0]))throw new Error('this is not a by-service Reports CSV');}
  var data=normalizeRows(route.cloud,route.part,rows);if(!data.length)throw new Error('no usable rows after parsing');
  place(route.cloud,route.part,route.k,route.key,file.name,data);
  if(route.cloud==='azure'&&!S.clouds.azure.enabled){S.clouds.azure.enabled=true;syncInputs();}
  return {file:file.name,route:route};}).then(function(r){return r;},function(e){return {file:file.name,error:e.message};});}
function ingestFiles(files,forced){var list=Array.prototype.slice.call(files);Promise.all(list.map(function(f){return ingestOne(f,forced);})).then(function(results){var ok=results.filter(function(r){return r.route;}),bad=results.filter(function(r){return r.error;});
  bad.forEach(function(r){toast('Could not read '+r.file+': '+r.error,'err');});
  ok.filter(function(r){return r.route.warn;}).forEach(function(r){toast(r.file+' '+r.route.warn+'. It is filed under '+monthLabel(r.route.key)+'.','warn');});
  if(ok.length===1){var r=ok[0];toast('Loaded '+r.file+' as '+cloudName(r.route.cloud)+' · '+slotLabel(r.route.cloud,r.route.part,r.route.k),'ok');}
  else if(ok.length>1){var g=ok.filter(function(r){return r.route.cloud==='gcp';}).length,a=ok.length-g;toast('Loaded '+ok.length+' files: '+g+' Google Cloud, '+a+' Azure. The table shows where each one landed.','ok');}
  if(ok.length){var pick=ok.filter(function(r){return r.route.cloud==='gcp'&&r.route.k==='m';})[0]||ok.filter(function(r){return r.route.k==='m';})[0]||ok[0];focus={cloud:pick.route.cloud,k:pick.route.k,key:pick.route.key};onChange('full');}});}

/* ---------- step 1: the month drives the edition ---------- */
function lastDay(iso){var p=ym(iso);return new Date(p[0],p[1],0).getDate();}
function deriveEdition(){var E=S.edition,m=E.month;if(!/^\d{4}-\d{2}$/.test(m||''))return false;var ld=lastDay(m),p=ym(m),nm=nextMonth(m);
 E.dataAsOf=ld+' '+MEN[p[1]-1]+' '+p[0];E.dataAsOfAr=ld+' '+MAR[p[1]-1]+' '+p[0];E.quarterEnd=isQuarterEnd(m);
 E.labelEn=monthLabel(nm)+' edition · '+monthLabel(m)+' data';E.labelAr='إصدار '+monthLabel(nm,true)+' · بيانات '+monthLabel(m,true);
 S.clouds.gcp.tdLabelEn='October 2025 to '+monthLabel(m);S.clouds.gcp.tdLabelAr='أكتوبر 2025 إلى '+monthLabel(m,true);
 S.clouds.azure.tdLabelEn='Contract start to '+ld+' '+MEN[p[1]-1]+' '+p[0];S.clouds.azure.tdLabelAr='من بداية العقد إلى '+ld+' '+MAR[p[1]-1]+' '+p[0];
 if(!E.versionManual)E.version=derivedVersion(m);E.publishedManual=false;refreshPublished();
 syncInputs();return true;}
function derivedVersion(m){var B=BASE.edition;return Math.max(1,(+B.version||1)+monthsBetween(B.month,m)-1);}
function today(){var d=new Date();return {en:d.getDate()+' '+MEN[d.getMonth()]+' '+d.getFullYear(),ar:d.getDate()+' '+MAR[d.getMonth()]+' '+d.getFullYear()};}
function refreshPublished(){var E=S.edition;if(E.publishedManual)return false;var t=today();if(E.published===t.en&&E.publishedAr===t.ar)return false;E.published=t.en;E.publishedAr=t.ar;return true;}
function monthOptions(){var keys=Object.keys(S.clouds.gcp.periods||{}).concat(Object.keys(S.clouds.azure.periods||{})).filter(function(k){return /^\d{4}-\d{2}$/.test(k);});var start=keys.length?keys.sort()[0]:'2026-01';if(start>'2026-01')start='2026-01';var now=new Date(),end=now.getFullYear()+'-'+(now.getMonth()+1<10?'0':'')+(now.getMonth()+1);if(S.edition.month>end)end=S.edition.month;var out=[],cur=start;while(cur<=end&&out.length<60){out.push(cur);cur=nextMonth(cur);}return out.reverse();}
function fillMonthSelect(){var sel=$('#f-month'),opts=monthOptions();if(opts.indexOf(S.edition.month)<0&&/^\d{4}-\d{2}$/.test(S.edition.month||''))opts.unshift(S.edition.month);sel.innerHTML=opts.map(function(m){return '<option value="'+m+'">'+esc(monthLabel(m))+'</option>';}).join('');sel.value=S.edition.month;}
function renderDerived(){var E=S.edition,m=E.month,B=BASE.edition,chip=function(l,v){return '<span><b>'+esc(l)+'</b>'+esc(v)+'</span>';};var vn=$('#ver-note');if(vn)vn.textContent=E.versionManual?'Set by hand. "Refill everything from the month" returns to the derived number.':monthLabel(prevMonth(B.month))+' was v'+((+B.version||1)-1)+' and each month adds one, so '+monthLabel(m)+' is v'+derivedVersion(m)+'. Edit to override.';$('#derived').innerHTML=chip('Version','v'+(E.version||'?')+(E.versionManual?' (set by hand)':''))+chip('Data as of',E.dataAsOf||'')+chip('Published',(E.published||'')+(E.publishedManual?' (set by hand)':' · refreshed on download'))+chip('Quarter tab',E.quarterEnd?'on':'off ('+monthLabel(m)+' is '+(isQuarterEnd(m)?'':'not ')+'a quarter end)')+chip('GCP to date',S.clouds.gcp.tdLabelEn||'')+(S.clouds.azure.enabled?chip('Azure to date',S.clouds.azure.tdLabelEn||''):'')+chip('Label',E.labelEn||'')+chip('Rate',FX()+' Riyals per US dollar');}

/* ---------- bindings ---------- */
function scopeOf(path){if(path.indexOf('statement.')===0)return 'statement';var m=/^clouds\.(gcp|azure)\.credit\./.exec(path);if(m)return 'credit:'+m[1];return 'full';}
function syncInputs(){$$('[data-bind]').forEach(function(el){var v=get(S,el.dataset.bind);if(el.type==='checkbox')el.checked=!!v;else if(document.activeElement!==el)el.value=v==null?'':v;});}
function bindInputs(){$$('[data-bind]').forEach(function(el){var p=el.dataset.bind;var ev=(el.tagName==='SELECT'||el.type==='checkbox')?'change':'input';el.addEventListener(ev,function(){var val=el.type==='checkbox'?el.checked:el.value;if(el.type==='number')val=el.value===''?null:+el.value;set(S,p,val);
  if(p==='edition.month'){deriveEdition();toast('Dates, labels and to-date ranges set for '+monthLabel(el.value)+'. Adjust any of them below if needed.','ok');onChange('full');return;}
  if(p==='edition.version'){S.edition.versionManual=true;onChange('full');return;}
  if(p==='edition.published'||p==='edition.publishedAr'){S.edition.publishedManual=true;onChange('full');return;}
  if(p==='edition.ledgerCurrency'||p==='edition.ledgerConfirmed'){creditEditors();onChange('full');return;}
  if(p==='edition.fx'||p==='clouds.azure.enabled'||p==='edition.quarterEnd'||p==='edition.azureCurrency'){onChange('full');return;}
  onChange(scopeOf(p));});
 if(el.hasAttribute('data-stmt'))el.addEventListener('focus',function(){lastField=el;});});}
var lastField=null;
function tokenChips(){var host=$('#tokchips'),T=tokenMap(false);host.innerHTML=TOKENS.map(function(t){return '<button type="button" data-tok="'+t+'" class="'+(T[t]==null?'dead':'')+'" title="'+(T[t]==null?'no data behind this token yet':'insert at the cursor')+'">{{'+t+'}}</button>';}).join('');
 $$('button[data-tok]',host).forEach(function(b){b.addEventListener('click',function(){var el=lastField||$('#f-sb');var ins='{{'+b.dataset.tok+'}}';if(typeof el.setRangeText==='function'){el.focus();el.setRangeText(ins,el.selectionStart||0,el.selectionEnd||0,'end');}else el.value+=ins;set(S,el.dataset.bind,el.value);onChange('statement');});});}
function updateStatement(){var el=$('#report .stmt');if(el)el.outerHTML=statement();var pv=$('#stmt-preview');if(pv)pv.innerHTML=statement(true);}
function updateCredit(c){var el=$('#report .mfig-card.for-'+c);if(el)el.outerHTML=creditCard(c);else renderPreview();}

/* ---------- step 2: files table ---------- */
function filesTable(){var E=S.edition,host=$('#ftable'),h='<table><thead><tr><th>Slot</th><th>Status</th><th>File</th><th class="acts"></th></tr></thead><tbody>',extra=[];
 ['gcp','azure'].forEach(function(c){if(c==='azure'&&!S.clouds.azure.enabled)return;h+='<tr class="cloud"><td colspan="4">'+cloudName(c)+'</td></tr>';
  SLOTS[c].forEach(function(sl,i){if(sl.q&&!E.quarterEnd)return;var key=slotKey(sl.k),p=S.clouds[c].periods[key],f=p&&p.files&&p.files[sl.part];var badge=f?'<span class="badge '+(p.sample?'sample':'ok')+'">'+(p.sample?'Sample':'Loaded')+'</span>':'<span class="badge '+(sl.req?'req':'')+'">'+(sl.req?'Required':'Optional')+'</span>';
   h+='<tr><td>'+esc(sl.en)+'</td><td>'+badge+'</td><td class="fn">'+(f?esc(f):'<span style="color:var(--mut)">'+esc(sl.k==='t'?'contract start to date':sl.k==='q'?quarterLabel(key):monthLabel(key))+'</span>')+'</td><td class="acts"><label class="btn sm">'+(f?'Replace':'Choose file')+'<input type="file" accept=".csv,text/csv" data-slot="'+c+'|'+i+'"></label>'+(f?' <button class="btn sm" type="button" data-remove="'+c+'|'+key+'|'+sl.part+'">Remove</button>':'')+'</td></tr>';});
  var P=S.clouds[c].periods;Object.keys(P).forEach(function(key){var p=P[key];if(!p||p.source!=='upload')return;var k=kindKey(p);if(key===slotKey(k))return;Object.keys(p.files||{}).forEach(function(part){extra.push({c:c,key:key,part:part,name:p.files[part],p:p});});});});
 h+='</tbody></table>';
 if(extra.length){h+='<h4 style="margin:14px 0 4px;font-size:13px">Files loaded under other periods</h4><table><tbody>'+extra.map(function(o){return '<tr><td>'+esc(cloudName(o.c)+' · '+slotLabel(o.c,o.part,kindKey(o.p))+' · '+o.p.label)+'</td><td><span class="badge '+(o.p.sample?'sample':'ok')+'">'+(o.p.sample?'Sample':'Loaded')+'</span></td><td class="fn">'+esc(o.name)+'</td><td class="acts"><button class="btn sm" type="button" data-remove="'+o.c+'|'+o.key+'|'+o.part+'">Remove</button></td></tr>';}).join('')+'</tbody></table>';}
 host.innerHTML=h;
 $$('input[data-slot]',host).forEach(function(inp){inp.addEventListener('change',function(){var b=inp.dataset.slot.split('|'),sl=SLOTS[b[0]][+b[1]];if(inp.files[0])ingestFiles([inp.files[0]],{cloud:b[0],part:sl.part,k:sl.k});});});
 $$('button[data-remove]',host).forEach(function(btn){btn.addEventListener('click',function(){var b=btn.dataset.remove.split('|');unplace(b[0],b[1],b[2]);toast('Removed the file from '+cloudName(b[0])+' · '+b[2]+'.','ok');onChange('full');});});}

/* ---------- step 3: credit editors and the computed balance ---------- */
function creditEditors(){var host=$('#ceditors'),C=S.clouds.gcp.credit;CREDIT_EDITORS.forEach(function(ed){if(!Array.isArray(C[ed.path]))C[ed.path]=[];});
 var lu=ledgerUnit().trim(),sarL=ledgerCur()==='SAR';host.innerHTML=CREDIT_EDITORS.map(function(ed,ei){var rows=C[ed.path],sub=ed.path==='purchaseOrders'?(sarL?'From the procurement ledger. The ledger column is read as Riyals net of 15% VAT and used as it is.':'From the procurement ledger. The $ column is the ledger value net of 15% VAT; the Studio converts it at '+FX()+' Riyals to the US dollar.'):ed.sub;return '<div class="ceditor"><h4>'+esc(ed.title)+'<small>'+esc(sub)+'</small></h4><table><thead><tr>'+ed.cols.map(function(c){return '<th>'+esc(c.f==='usd'?c.l.replace('$',lu):c.l)+'</th>';}).join('')+'<th></th></tr></thead><tbody>'+rows.map(function(r,ri){return '<tr>'+ed.cols.map(function(c){var v=c.f==='servicesText'?(r.services||[]).join(', '):(r[c.f]==null?'':r[c.f]);if(c.t==='select')return '<td><select data-ed="'+ei+'" data-i="'+ri+'" data-f="'+c.f+'">'+c.o.map(function(o){return '<option value="'+o[0]+'"'+(o[0]===v?' selected':'')+'>'+o[1]+'</option>';}).join('')+'</select></td>';return '<td class="'+(c.t==='number'?'num':'')+'"><input type="'+(c.t==='number'?'number':'text')+'"'+(c.t==='number'?' step="0.01"':'')+' data-ed="'+ei+'" data-i="'+ri+'" data-f="'+c.f+'" value="'+esc(v)+'"></td>';}).join('')+'<td class="del"><button type="button" data-del="'+ei+'|'+ri+'" aria-label="Remove row">&times;</button></td></tr>';}).join('')+'</tbody></table><button type="button" class="add" data-add="'+ei+'">+ '+esc(ed.add)+'</button></div>';}).join('');}
function creditEditorEvents(){var host=$('#ceditors');host.addEventListener('input',function(e){var el=e.target;if(!el.dataset||el.dataset.ed==null)return;var ed=CREDIT_EDITORS[+el.dataset.ed],row=S.clouds.gcp.credit[ed.path][+el.dataset.i];if(!row)return;var f=el.dataset.f,col=ed.cols.filter(function(c){return c.f===f;})[0];
  if(f==='servicesText'){row.services=el.value.split(',').map(function(s){return s.trim();}).filter(Boolean);}else if(col&&col.t==='number'){row[f]=el.value===''?null:+el.value;}else row[f]=el.value;onChange('credit:gcp');});
 host.addEventListener('change',function(e){var el=e.target;if(el.tagName==='SELECT'&&el.dataset.ed!=null){var ed=CREDIT_EDITORS[+el.dataset.ed],row=S.clouds.gcp.credit[ed.path][+el.dataset.i];if(row){row[el.dataset.f]=el.value;onChange('credit:gcp');}}});
 host.addEventListener('click',function(e){var b=e.target.closest('button');if(!b)return;if(b.dataset.add!=null){var ed=CREDIT_EDITORS[+b.dataset.add];S.clouds.gcp.credit[ed.path].push(clone(ed.blank));creditEditors();onChange('credit:gcp');}else if(b.dataset.del!=null){var bits=b.dataset.del.split('|'),ed2=CREDIT_EDITORS[+bits[0]];S.clouds.gcp.credit[ed2.path].splice(+bits[1],1);creditEditors();onChange('credit:gcp');}});}
function balancePanel(){var r=creditCalc('gcp'),host=$('#balance'),sarL=r.ledger==='SAR',row=function(l,sar,usd,cls){return '<tr class="'+(cls||'')+'"><td>'+l+'</td><td class="n">'+(sar==null?'n/a':num(sar,0))+((usd==null||sarL)?'':'<small>$'+num(usd,0)+'</small>')+'</td></tr>';};
 var none=r.basis==='none';var h='<h4>Remaining balance · Riyals</h4><div class="big">'+(none?'n/a':RS+num(r.remainingSar,2))+'</div><table>';
 h+=row('Starting credit (purchase orders)',r.startingSar,r.startingUsd);
 r.fixed.forEach(function(f){h+=row('&minus; '+esc(f.name||'drawdown'),f.sar,f.usd,'sub');});
 h+=row('&minus; Consumption to date'+(none?'':' ('+esc(r.rangeEn)+')'),none?null:r.consumptionSar,none?null:r.consumptionUsd,'sub');
 h+=row('= Remaining balance',none?null:r.remainingSar,none?null:r.remainingUsd,'total');
 h+='<tr class="head"><td colspan="2">Remaining from commitments</td></tr>';
 r.commitments.forEach(function(k){h+=row(esc(k.name||'commitment')+(k.found?' <small style="color:rgba(228,238,255,.6)">used to date '+num(k.usedSar,0)+', read from '+esc(k.matched.join(', '))+'</small>':' <small style="color:#FFE29A">no matching service row in the to-date export</small>'),k.remainingSar,r.toL(k.remainingSar),'sub');});
 h+=row('= Remaining commitment',r.commitRemainingSar,r.toL(r.commitRemainingSar),'total');
 h+=row('= Uncommitted balance',none?null:r.uncommittedSar,none?null:r.toL(r.uncommittedSar),'total');
 h+='</table><div class="basis'+(r.basis==='upload'?'':' warn')+'">'+(none?'Waiting for the contract-to-date export (step 2): the balance is computed from its net figure.':r.basis==='baseline'?'Consumption is still read from the previous edition\'s to-date export ('+esc(r.rangeEn)+'). Drop this month\'s to-date file in step 2 to bring the balance to '+esc(monthLabel(S.edition.month))+'.':'Consumption read from the contract-to-date export you loaded ('+esc(r.rangeEn)+').')+' Ledger read as '+(sarL?'Riyals net of VAT':'US dollars at '+r.fx)+(r.ledgerConfirmed?'.':', not yet confirmed by procurement; the report says so.')+'</div>';
 host.innerHTML=h;}

/* ---------- step 4: quick maps ---------- */
function quickMaps(){var any=false;['gcp','azure'].forEach(function(c){var host=$('#qm-'+c),P=S.clouds[c].periods,un={};Object.keys(P).forEach(function(k){(P[k]&&P[k].unmapped||[]).forEach(function(u){un[u||'(blank id)']=u;});});var list=Object.keys(un);
 if(!list.length){host.innerHTML='';host.hidden=true;return;}any=true;host.hidden=false;
 host.innerHTML='<div class="qm-title">'+cloudName(c)+': '+list.length+' unmapped '+(c==='gcp'?'project':'subscription')+(list.length>1?'s':'')+'</div>'+list.map(function(label){return '<div class="qm-row"><code title="'+esc(label)+'">'+esc(label)+'</code><select data-qm="'+esc(un[label])+'" aria-label="Department for '+esc(label)+'"><option value="">Choose the owning department</option>'+DEPT_ORDER.map(function(d){return '<option value="'+d+'">'+esc(DEPT[d].en)+'</option>';}).join('')+'</select></div>';}).join('');
 $$('select[data-qm]',host).forEach(function(sel){sel.addEventListener('change',function(){if(!sel.value)return;var key=c==='gcp'?'projectMapText':'subMapText',id=sel.dataset.qm===''?'[account-level]':sel.dataset.qm;S.clouds[c][key]=(S.clouds[c][key]||'').replace(/\s*$/,'')+'\n'+id+' = '+sel.value+'\n';syncInputs();toast('Mapped '+id+' to '+DEPT[sel.value].en,'ok');onChange('full');});});});
 var loaded=['gcp','azure'].some(function(c){return Object.keys(S.clouds[c].periods).some(function(k){return S.clouds[c].periods[k]&&S.clouds[c].periods[k].source==='upload';});});$('#allmapped').hidden=any||!loaded;}

/* ---------- readiness ---------- */
function recomputeAll(){['gcp','azure'].forEach(function(c){var P=S.clouds[c].periods;Object.keys(P).forEach(function(k){var p=P[k];if(p&&p.source==='upload'){if(k==='td'){p.label=S.clouds[c].tdLabelEn||p.label;p.labelAr=S.clouds[c].tdLabelAr||p.labelAr;}if(c==='gcp')recomputeGcp(p);else recomputeAzure(p);}});});}
function checklist(){var E=S.edition,m=E.month,items=[],add=function(l,t,act){items.push({level:l,text:t,action:act||null});};if(!/^\d{4}-\d{2}$/.test(m||'')){add('err','Choose the reporting month in step 1.');return items;}
 var ML=monthLabel(m);['gcp','azure'].forEach(function(c){var C=S.clouds[c];if(c==='azure'&&!C.enabled){add('ok','Microsoft Azure is not included in this edition.');return;}var name=cloudName(c),p=C.periods[m];
  if(!p||!p.services||!p.services.length){add('err',name+': '+ML+' by-service export is missing (step 2).');}else{add('ok',name+': '+ML+' by service loaded ('+p.services.length+' services, net '+num(p.totals.net,0)+' Riyals'+(p.sample?', SAMPLE file':'')+').');
   if(c==='gcp'){if(p.discountTrap)add('err',name+': the by-service export shows no discounts at all (Subtotal equals List cost on every row). It was pulled with the credits and discounts options off; re-export with them on.');
    if(p.projects)add('ok',name+': by project loaded, department split exact'+(p.projTotal!=null&&Math.abs(p.projTotal-p.totals.net)>1?' but the project total ('+num(p.projTotal,0)+') differs from the service total ('+num(p.totals.net,0)+') by '+num(Math.abs(p.projTotal-p.totals.net),0)+' Riyals: check both files cover the same range and scope':'')+'.');else add('warn',name+': by-project export missing, so the department split is apportioned on the latest exact period.');
    if(p.acctCheck){if(Math.abs(p.acctCheck.diff)<=1)add('ok',name+': the account-level bucket reconciles with the security services to the riyal.');else add('warn',name+': the account-level bucket ('+num(p.acctCheck.bucket,0)+') differs from Chronicle + Security Command Center + Fortinet ('+num(p.acctCheck.security,0)+') by '+num(Math.abs(p.acctCheck.diff),0)+' Riyals; revisit the split before publishing.');}
    if(!p.sandbox)add('warn',name+': sandbox export missing; the sandbox figure will read as not loaded.');}
   else{if(p.subs)add('ok',name+': by subscription loaded, department split exact'+(p.subTotal!=null&&Math.abs(p.subTotal-p.totals.net)>5?' but the subscription total ('+num(p.subTotal,0)+') differs from the service total ('+num(p.totals.net,0)+'): check scope and date range':'')+'.');else add('warn',name+': by-subscription export missing, so the department chart will say so.');if(!p.regions||!p.regions.length)add('warn',name+': by-location export missing; the region table and residency note will not appear.');}
   if(p.unmapped&&p.unmapped.length)add('err',name+': unmapped '+(c==='gcp'?'projects':'subscriptions')+': '+p.unmapped.map(function(x){return x||'(blank id)';}).join(', ')+'. Pick their departments in step 4.');}
  if(!C.periods.td||!C.periods.td.services||!C.periods.td.services.length)add('err',name+': contract-to-date by-service export is missing (step 2).');else if(C.periods.td.source!=='upload')add('warn',name+': the to-date view still carries the previous edition ("'+C.periods.td.label+'"). Drop the fresh to-date export to bring it, and the credit balance, to '+ML+'.');else add('ok',name+': contract to date loaded ('+C.periods.td.label+').');
  if(E.quarterEnd){var qk=quarterKey(m);if(!C.periods[qk])add('err',name+': quarter-end edition but no '+quarterLabel(qk)+' export loaded.');}});
 var r=creditCalc('gcp');if(!r.po.length||r.startingUsd<=0)add('err','Google Cloud credit: add at least one purchase order with its $ amount (step 3).');else if(r.basis==='none')add('err','Google Cloud credit: the remaining balance is computed from the contract-to-date export; drop it in step 2.');else{if(r.remainingSar<0)add('err','Google Cloud credit: the computed balance is negative ('+num(r.remainingSar,0)+' Riyals). Check the purchase orders and the drawdowns in step 3.');else add('ok','Google Cloud credit: remaining balance '+num(r.remainingSar,0)+' Riyals, computed from '+num(r.startingSar,0)+' starting credit less '+num(r.fixedSar,0)+' of drawdowns and '+num(r.consumptionSar,0)+' of consumption ('+r.rangeEn+').');r.commitments.forEach(function(k){if(!k.found)add('warn','Commitment "'+(k.name||'unnamed')+'" maps to '+(k.services.length?k.services.join(', '):'no service')+', but no service row in the to-date export matches it (case-insensitive, part of the name is enough), so it reads as fully remaining. Check the billing service name in step 3.');});
  if(!E.ledgerConfirmed)add('warn','Google Cloud credit: the ledger is read as '+(r.ledger==='SAR'?'Riyals net of VAT':'US dollars at '+r.fx)+' and procurement has not confirmed the ledger currency yet; the report says so under the arithmetic. Tick the confirmation in step 3 once it is.');}
 if(!S.statement.headEn||!lines(S.statement.bodyEn).length)add('err','The FinOps statement of the month needs a headline and at least one paragraph (step 5).');else add('ok','Statement of the month written'+(S.statement.bodyAr&&S.statement.headAr?' in English and Arabic.':' (Arabic falls back to English).'));
 var mt=missingTokens(),where=function(list){var f=[];list.forEach(function(t){t.fields.forEach(function(x){if(f.indexOf(x)<0)f.push(x);});});return f.join(', ');},mtA=mt.filter(function(t){return t.azure;}),mtD=mt.filter(function(t){return !t.azure;});
 if(mtA.length)add('err','Microsoft Azure is not included in this edition, but the statement still uses '+mtA.map(function(t){return '{{'+t.tok+'}}';}).join(' ')+' in: '+where(mtA)+'. Remove those lines (the Arabic text counts too), or include Azure in step 1.',{id:'dropAzure',label:'Remove the Azure lines'});
 if(mtD.length)add('err','Statement tokens still waiting for data: '+mtD.map(function(t){return '{{'+t.tok+'}} in '+t.fields.join(', ');}).join('; ')+'. Drop the files in step 2 or take the tokens out.');
 var sample=['gcp','azure'].some(function(c){var P=S.clouds[c].periods;return S.clouds[c].enabled!==false&&Object.keys(P).some(function(k){return P[k]&&P[k].sample;});});if(sample)add('err','A SAMPLE_ file is loaded. The report carries a "Sample data" chip until every sample file is replaced with a real export.');
 if(E.quarterEnd!==isQuarterEnd(m))add('warn',isQuarterEnd(m)?ML+' is a quarter-end month; the Quarter tab is switched off.':ML+' is not a quarter-end month; the Quarter tab is switched on.');
 add('ok','This browser keeps every edit and file between months. After the download, also save the edition state as the backup copy to keep with the month\'s CSVs.');
 return items;}
function flowState(items){var E=S.edition,m=E.month,st={};st[1]=/^\d{4}-\d{2}$/.test(m||'')?'ok':'todo';
 var need=0,have=0;['gcp','azure'].forEach(function(c){if(c==='azure'&&!S.clouds.azure.enabled)return;Object.keys(REQ[c]).forEach(function(k){REQ[c][k].forEach(function(part){need++;var p=S.clouds[c].periods[slotKey(k)];if(p&&p.files&&p.files[part])have++;});});});
 st[2]=have===need?'ok':(have?'part':'todo');st.files=have+' of '+need+' required';
 var r=creditCalc('gcp');st[3]=(r.po.length&&r.startingUsd>0&&r.basis!=='none'&&r.remainingSar>=0)?(r.basis==='baseline'?'part':'ok'):'todo';st.credit=r.basis==='none'?'needs the to-date export':r.basis==='baseline'?'on last edition\'s spend':'computed';
 var un=items.some(function(i){return /unmapped/.test(i.text);});st[4]=un?'todo':'ok';
 st[5]=(S.statement.headEn&&lines(S.statement.bodyEn).length&&!missingTokens().length)?'ok':'todo';
 st.errs=items.filter(function(i){return i.level==='err';}).length;st[6]=st.errs?'todo':'ok';return st;}
var step=1;
function showStep(n){step=n;$$('.st-panel').forEach(function(p){p.hidden=+p.dataset.panel!==n;});$$('#st-steps button').forEach(function(b){b.classList.toggle('active',+b.dataset.step===n);});if(n===3)creditEditors();var y=$('#st-steps').getBoundingClientRect().top+window.scrollY-8;if(window.scrollY>y)window.scrollTo({top:y});}
function renderStudio(){renderDerived();filesTable();quickMaps();tokenChips();balancePanel();var pv=$('#stmt-preview');if(pv)pv.innerHTML=statement(true);
 var items=checklist(),ul=$('#checklist');ul.innerHTML=items.map(function(i){return '<li class="'+i.level+'"><span>'+esc(i.text)+(i.action?' <button type="button" class="btn sm" data-act="'+esc(i.action.id)+'">'+esc(i.action.label)+'</button>':'')+'</span></li>';}).join('');
 $$('#checklist button[data-act]',ul).forEach(function(b){b.addEventListener('click',function(){if(b.dataset.act==='dropAzure'){var n=dropAzureLines();syncInputs();toast(n?n+' line'+(n>1?'s':'')+' mentioning Azure removed from the statement, English and Arabic.':'No Azure lines found in the statement.','ok');onChange('statement');}});});
 var st=flowState(items),labels={1:st[1]==='ok'?monthLabel(S.edition.month):'choose',2:st.files,3:st.credit,4:st[4]==='ok'?'mapped':'pick departments',5:st[5]==='ok'?'ready':'needs data or text',6:st.errs?st.errs+' blocker'+(st.errs>1?'s':''):'ready'};
 $$('#st-steps button').forEach(function(b){var n=+b.dataset.step;b.classList.remove('ok','part','todo');b.classList.add(st[n]);$('em',b).textContent=labels[n];});
 var ok=!st.errs;['#btn-gen','#btn-gen-top','#btn-gen-bar'].forEach(function(s){var b=$(s);if(b)b.disabled=!ok;});$('#btn-gen').textContent='Download FinOps_Dashboard_v'+S.edition.version+'.html';
 var bs=$('#bar-status');bs.textContent=ok?'Ready to download Report v'+S.edition.version+' · '+monthLabel(S.edition.month):st.errs+' blocker'+(st.errs>1?'s':'')+' before download · see step 6';bs.className='bar-status '+(ok?'ready':'blocked');
 $('#bz-month').textContent=monthLabel(S.edition.month);}
function markSaved(){var d=new Date();$('#saved').textContent='Saved in this browser '+(d.getHours()<10?'0':'')+d.getHours()+':'+(d.getMinutes()<10?'0':'')+d.getMinutes();}
function toast(msg,kind){var host=$('#toasts');if(!host)return;var t=document.createElement('div');t.className='toast '+(kind||'');t.textContent=msg;host.appendChild(t);setTimeout(function(){t.remove();},kind==='err'?7000:4200);}
function setStatus(t,cls){toast(t,cls==='err'?'err':cls==='ok'?'ok':'warn');}
var timer=null;function onChange(scope){save();if(lastGen){lastGen=null;resultPanel();}clearTimeout(timer);timer=setTimeout(function(){if(scope==='statement'){updateStatement();}else if(scope&&scope.indexOf('credit:')===0){updateCredit(scope.slice(7));}else{recomputeAll();renderPreview();}renderStudio();markSaved();},scope==='full'?40:140);}

/* ---------- generate, preview as published, state ---------- */
function download(text,name,type){var blob=new Blob([text],{type:type||'text/html;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},2000);}
function publishedHtml(){var E=S.edition,html=buildReport(true,{cloud:'gcp',lang:false,pv:{},p:{}}),box=document.createElement('div');box.innerHTML=html;$$('.studio-only',box).forEach(function(n){n.remove();});
 var css=$('#fonts-css').textContent+'\n'+$('#report-css').textContent,title='MoEnergy Cloud FinOps Report · '+monthLabel(E.month);
 return '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n<meta name="viewport" content="width=device-width,initial-scale=1">\n<meta name="robots" content="noindex">\n<title>'+esc(title)+'</title>\n<link rel="icon" href="'+FAVICON+'">\n<style>\n'+css+'\n</style>\n</head>\n<body class="published">\n<div id="report" class="report">'+box.innerHTML+'</div>\n<!-- Report v'+esc(E.version)+' · generated by FinOps Report Studio v1.3 · zero JavaScript, no external requests -->\n</body>\n</html>\n';}
var genUrl=null,lastGen=null;
function generate(){var items=checklist();if(items.some(function(i){return i.level==='err';})){toast('Not ready: clear the red items in step 6 first.','err');showStep(6);return;}
 if(refreshPublished()){syncInputs();renderPreview();}var E=S.edition,out=publishedHtml(),name='FinOps_Dashboard_v'+E.version+'.html';download(out,name);
 if(genUrl){try{URL.revokeObjectURL(genUrl);}catch(e){}}genUrl=URL.createObjectURL(new Blob([out],{type:'text/html;charset=utf-8'}));lastGen={html:out,name:name,kb:Math.round(out.length/1024),version:E.version,month:E.month,published:E.published};
 save();renderStudio();resultPanel();toast('Downloaded '+name+'. If nothing arrived, this viewer blocks downloads: open the Studio file from disk in a normal browser tab.','ok');showStep(6);}
function resultPanel(){var r=$('#gen-result'),g=lastGen;if(!r)return;if(!g){r.hidden=true;r.innerHTML='';return;}r.hidden=false;
 r.innerHTML='<div class="gr-head"><b>'+esc(g.name)+'</b> is in your Downloads folder.<span class="gr-meta">'+g.kb+' KB · Report v'+esc(g.version)+' · '+esc(monthLabel(g.month))+' · published '+esc(g.published)+'</span></div>'
  +'<p>This is the file leadership opens: one standalone page, no scripts, no internet connection, no Studio. Nothing else has to travel with it.</p>'
  +'<div class="btnrow"><button class="btn primary" type="button" id="btn-open">Open the report in a new tab</button><button class="btn" type="button" id="btn-stable">Download the stable copy, FinOps_Dashboard.html</button><button class="btn" type="button" id="btn-state">Download the edition state</button></div>'
  +'<ol><li>Open it and read it through once, English and Arabic, the cloud switch and the month dropdown included.</li><li>Upload the stable copy to SharePoint over the previous edition so the link never changes; keep '+esc(g.name)+' as the archive copy.</li><li>Keep the edition state with the month\'s CSVs in finops/data/'+esc(g.month)+'/. This browser keeps it too, so next month starts from here.</li></ol>';
 $('#btn-open').addEventListener('click',function(){var w=null;try{w=window.open(genUrl,'_blank');}catch(e){}if(!w)toast('The browser blocked the new tab. Open '+g.name+' from your Downloads folder instead.','warn');});
 $('#btn-stable').addEventListener('click',function(){download(g.html,'FinOps_Dashboard.html');toast('Downloaded FinOps_Dashboard.html, the copy to upload over the previous edition.','ok');});
 $('#btn-state').addEventListener('click',saveState);}
function saveState(){download(JSON.stringify(S,null,1),'finops_edition_'+S.edition.month+'.json','application/json');toast('Edition state downloaded: finops_edition_'+S.edition.month+'.json.','ok');}
var pubPreview=false;
function togglePubPreview(on){pubPreview=on;document.body.classList.toggle('pub-preview',on);$('#btn-back').hidden=!on;if(on){if(refreshPublished())syncInputs();$('#report').innerHTML=buildReport(true,{cloud:'gcp',lang:false,pv:{},p:{}});$$('#report .studio-only').forEach(function(n){n.remove();});window.scrollTo({top:0});}else{renderPreview();}}
function initStudio(){fillMonthSelect();bindInputs();syncInputs();creditEditors();creditEditorEvents();
 var bz=$('#bigzone'),bzi=$('input',bz);bzi.addEventListener('change',function(){if(bzi.files.length)ingestFiles(bzi.files);bzi.value='';});['dragenter','dragover'].forEach(function(ev){bz.addEventListener(ev,function(e){e.preventDefault();bz.classList.add('over');});});['dragleave','drop'].forEach(function(ev){bz.addEventListener(ev,function(e){e.preventDefault();bz.classList.remove('over');});});bz.addEventListener('drop',function(e){if(e.dataTransfer.files.length)ingestFiles(e.dataTransfer.files);});bz.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();bzi.click();}});
 document.addEventListener('dragover',function(e){e.preventDefault();});document.addEventListener('drop',function(e){e.preventDefault();});
 $$('#st-steps button').forEach(function(b){b.addEventListener('click',function(){showStep(+b.dataset.step);});});$$('[data-next]').forEach(function(b){b.addEventListener('click',function(){showStep(+b.dataset.next);});});
 ['#btn-gen','#btn-gen-top','#btn-gen-bar'].forEach(function(s){$(s).addEventListener('click',function(){generate();});});$('#btn-print').addEventListener('click',function(){window.print();});
 $('#btn-save').addEventListener('click',saveState);$('#btn-derive').addEventListener('click',function(){S.edition.versionManual=false;S.edition.publishedManual=false;if(deriveEdition()){toast('Dates, labels, version and to-date ranges refilled from '+monthLabel(S.edition.month)+'.','ok');onChange('full');}});
 $('#btn-draft').addEventListener('click',function(){S.statement=clone(BASE.statement);syncInputs();toast('The embedded statement draft is back.','ok');onChange('statement');});
 ['#btn-pubpreview','#btn-pubpreview-bar'].forEach(function(s){$(s).addEventListener('click',function(){togglePubPreview(true);});});$('#btn-back').addEventListener('click',function(){togglePubPreview(false);});
 $('#f-load').addEventListener('change',function(){var f=this.files[0];if(!f)return;f.text().then(function(t){var s=JSON.parse(t);if(!s||!s.meta||!s.clouds)throw new Error('not a Studio state file');S=s;save();location.reload();}).catch(function(e){toast('Could not load that state file: '+e.message,'err');});});
 $('#btn-reset').addEventListener('click',function(){if(!confirm('Discard every edit and file loaded in this browser and return to the embedded baseline?'))return;try{localStorage.removeItem(STORE);}catch(e){}location.reload();});
 if(refreshPublished()){save();syncInputs();}renderPreview();renderStudio();showStep(1);
 if(RESUMED){var at=S.meta&&S.meta.savedAt?new Date(S.meta.savedAt):null;toast('Picked up where you left off'+(at&&!isNaN(at)?' (saved '+at.getDate()+' '+MEN[at.getMonth()]+', '+(at.getHours()<10?'0':'')+at.getHours()+':'+(at.getMinutes()<10?'0':'')+at.getMinutes()+')':'')+': every edit and file from your last visit is here. Reset in step 6 starts over from the embedded baseline.','ok');}}
document.addEventListener('DOMContentLoaded',initStudio);
window.FinOpsStudio={state:function(){return S;},build:buildReport,checklist:checklist,generate:generate,classify:classify,publishedHtml:publishedHtml,creditCalc:creditCalc,showStep:showStep,resultPanel:resultPanel,derivedVersion:derivedVersion,refreshPublished:refreshPublished,lastGen:function(){return lastGen;},genUrl:function(){return genUrl;},resumed:function(){return RESUMED;}};
})();
