# -*- coding: utf-8 -*-
"""Build the shareable demo from the published report.

What comes across: the whole template. Single file, no JavaScript required,
bilingual EN and AR with an RTL flip, the period control, the charts, the print
path, the responsive behaviour.

What does not: every logo (five embedded images), the licensed display font, the
organisation's names and wording, and all of the real figures. Every number in
the output is generated by data.py from a fixed seed.
"""
import os, re, sys
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(ROOT, 'finops', 'generator'))
import gen, data, blocksd

SRC = os.path.join(ROOT, 'finops', 'FinOps_Dashboard.html')
OUT = os.path.join(ROOT, 'demo', 'Retail_Sales_Dashboard_v1.html')
BRAND_EN, BRAND_AR = 'NORTHWIND', 'نورث ويند'

s = open(SRC, encoding='utf-8').read()
before = len(s)


def sub1(old, new, n=1):
    """Replace and prove it happened exactly n times."""
    global s
    c = s.count(old)
    assert c == n, ('expected %d, found %d: %r' % (n, c, old[:120]))
    s = s.replace(old, new)


def span(t, i, tag='div'):
    d = 0
    for m in re.finditer(r'<%s\b|</%s>' % (tag, tag), t[i:]):
        d += -1 if m.group(0).startswith('</') else 1
        if d == 0: return i + m.end()
    raise ValueError('unbalanced <%s>' % tag)


# ---------------------------------------------------------------- 1 · the data
months, quarters, todate = data.build()
td = todate[0]
td_net = sum(r['net'] for r in td['rows'])

for cls, specs, single in [('v-m', months, False), ('v-q', quarters, False), ('v-t', todate, True)]:
    i = s.index('<section class="view %s">' % cls)
    j = span(s, i, 'section')
    head = s[i:s.index('>', i) + 1]
    tops, bodies = [], []
    for spec in specs:
        t, b = blocksd.build(spec, single=single)
        tops.append(t); bodies.append(b)
    s = s[:i] + head + ''.join(tops) + ''.join(bodies) + '</section>' + s[j:]
    print('%s rebuilt: %d period(s)' % (cls, len(specs)))

# ---------------------------------------------------------------- 2 · the head
sub1('<title>MoEnergy GCP FinOps Report &#183; July 2026</title>'
     .replace('&#183;', '·'),
     '<title>Northwind Retail · Sales Analytics Report · July 2026</title>')
sub1('data-build="animation-restored-integrated-spark"', 'data-build="retail-sales-demo-v1"')

# favicon: a neutral bar-chart plate, no brand marks
i = s.index("<link href='data:image/svg+xml,"); j = s.index("rel=\"icon\"/>", i) + len('rel="icon"/>')
s = s[:i] + ('<link href=\'data:image/svg+xml,&lt;svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"&gt;'
             '&lt;rect width="64" height="64" rx="14" fill="%23081631"/&gt;'
             '&lt;rect x="16" y="34" width="8" height="16" rx="2" fill="%2363b3ff"/&gt;'
             '&lt;rect x="28" y="24" width="8" height="26" rx="2" fill="%2300a3a8"/&gt;'
             '&lt;rect x="40" y="16" width="8" height="34" rx="2" fill="%23ffffff"/&gt;'
             '&lt;/svg&gt;\' rel="icon"/>') + s[j:]

# ---------------------------------------------------------------- 3 · the font
# Lafet is licensed to the original organisation and must not travel. The three
# embedded IBM Plex Sans Arabic weights carry Latin and Arabic and stay.
i = s.index("@font-face{font-family:'Lafet'")
j = s.index('}', s.index('font-display:swap', i)) + 1
s = s[:i] + s[j:]
s = s.replace("--font-display:'Lafet','IBM Plex Sans Arabic',sans-serif",
              "--font-display:'IBM Plex Sans Arabic','Segoe UI',sans-serif")
s = s.replace("var(--font-display, 'Lafet', sans-serif)", "var(--font-display)")
s = s.replace("var(--font-display),'Lafet',sans-serif", "var(--font-display)")
s = s.replace("'Lafet','IBM Plex Sans Arabic',sans-serif", "'IBM Plex Sans Arabic',sans-serif")
assert 'Lafet' not in s, 'a Lafet reference survived'

# ---------------------------------------------------------------- 4 · the bars
i = s.index('<div class="gbar">'); j = span(s, i)
s = s[:i] + (
  '<div class="gbar"><span class="gmk"><b>%s</b><i aria-hidden="true" class="orb"></i></span>'
  '<span class="gdesc"><span class="en">Sales Analytics · Commercial Planning</span>'
  '<span class="ar">تحليلات المبيعات · التخطيط التجاري</span></span>'
  '<span class="gdept"><span class="en">SALES ANALYTICS REPORT · COMMERCIAL PLANNING</span>'
  '<span class="ar">تقرير تحليلات المبيعات · التخطيط التجاري</span></span>'
  '<label class="lsw" for="lang" title="English / العربية"><span class="kn"></span><b>EN</b><b>ع</b></label>'
  '</div>' % BRAND_EN) + s[j:]

# ---------------------------------------------------------------- 5 · the hero
i = s.index('<div class="brandrow">'); j = span(s, i)
s = s[:i] + (
  '<div class="brandrow"><div aria-label="%s" class="hero-motion-lockup">'
  '<span class="finops-word">%s</span><i aria-hidden="true" class="orb"></i></div>'
  '<div aria-label="Space for your own logo" class="moewrap">'
  '<div class="init"><span class="en">Commercial Planning</span>'
  '<span class="ar">التخطيط التجاري</span></div>'
  '<div class="logo-slot"><span class="en">YOUR LOGO</span><span class="ar">شعاركم هنا</span></div>'
  '</div></div>' % (BRAND_EN, BRAND_EN)) + s[j:]

sub1('<h1><span class="en">GCP FinOps Report</span><span class="ar">تقرير الإنفاق على GCP</span></h1>',
     '<h1><span class="en">Sales Analytics Report</span>'
     '<span class="ar">تقرير تحليلات المبيعات</span></h1>')

i = s.index('<p class="sub">'); j = span(s, i, 'p')
s = s[:i] + (
  '<p class="sub"><span class="en">A worked example of a recurring monthly report for leadership: '
  'one self-contained HTML file, no JavaScript required, English and Arabic in the same page, and a '
  'period control that moves the whole report between months, quarters and the year to date. Every '
  'name and every figure below is invented sample data for a fictional retailer.</span>'
  '<span class="ar">نموذج عملي لتقرير شهري دوري يُرفع للقيادة: ملف HTML واحد قائم بذاته، لا يحتاج إلى '
  'تشغيل JavaScript، ويجمع اللغتين العربية والإنجليزية في الصفحة نفسها، مع أداة تنقل تحرك التقرير '
  'بالكامل بين الأشهر والأرباع والسنة حتى تاريخه. وجميع الأسماء والأرقام الواردة أدناه بيانات '
  'افتراضية لشركة تجزئة غير حقيقية.</span></p>') + s[j:]

i = s.index('<div class="chips">'); j = span(s, i)
s = s[:i] + (
  '<div class="chips">'
  '<span class="chip"><span class="en">Data as of <bdi>31 July 2026</bdi></span>'
  '<span class="ar">البيانات حتى <bdi>31 يوليو 2026</bdi></span></span>'
  '<span class="chip"><span class="en">Published <bdi>8 August 2026</bdi></span>'
  '<span class="ar">النشر <bdi>8 أغسطس 2026</bdi></span></span>'
  '<span class="chip"><span class="en">Sample data</span><span class="ar">بيانات افتراضية</span></span>'
  '<span class="chip"><span class="en">All figures in <span class="rs" aria-hidden="true"></span></span>'
  '<span class="ar">جميع المبالغ بـ<span class="rs" aria-hidden="true"></span></span></span>'
  '</div>') + s[j:]

# ---------------------------------------------------------------- 6 · the card
PLAN = 120_000_000
td_net = round(td_net)          # the report states whole units everywhere else
done_i, done_d = td_net, 0
rem = PLAN - td_net
pct = td_net / PLAN * 100
n0 = lambda v: format(int(round(v)), ',d')
n2 = lambda v: format(round(v, 2), ',.2f')
RS = '<span class="rs" aria-hidden="true"></span>'

sub1('aria-label="Remaining contract credit"', 'aria-label="Progress against the annual sales plan"')
sub1('<span class="en">Main figure</span><span class="ar">المؤشر الرئيسي</span>',
     '<span class="en">Main figure</span><span class="ar">المؤشر الرئيسي</span>')
sub1('<bdi>%s5,654,114</bdi>' % RS, '<bdi>%s%s</bdi>' % (RS, n0(done_i)))
sub1('<bdi>.85</bdi>', '<bdi>.%02d</bdi>' % round(done_d * 100))
sub1('<span class="en">Remaining credit balance as at 31 July 2026</span>'
     '<span class="ar">رصيد الائتمان المتبقي حتى 31 يوليو 2026</span>',
     '<span class="en">Net sales against the 2026 plan as at 31 July 2026</span>'
     '<span class="ar">صافي المبيعات مقابل خطة 2026 حتى 31 يوليو 2026</span>')
sub1('<span class="en">Of <bdi>%s9,685,235.81</bdi> in purchase-order credit, '
     '<bdi>%s4,031,121.38</bdi> has been consumed to date: enhanced support, back-end drawdowns '
     'and dashboard usage combined.</span>' % (RS, RS),
     '<span class="en">Of the <bdi>%s%s</bdi> planned for 2026, <bdi>%s%s</bdi> is still to be earned '
     'in the five months to December: stores, e-commerce, wholesale and marketplaces combined.</span>'
     % (RS, n0(PLAN), RS, n2(rem)))
sub1('<span class="ar">من إجمالي ائتمان أوامر الشراء البالغ <bdi>%s9,685,235.81</bdi>، استُهلك '
     '<bdi>%s4,031,121.38</bdi> حتى تاريخه، ويشمل ذلك الدعم المتقدم والسحوبات الخلفية والاستهلاك '
     'الظاهر في لوحات الفوترة.</span>' % (RS, RS),
     '<span class="ar">من إجمالي الخطة البالغة <bdi>%s%s</bdi> لعام 2026، يتبقى تحقيق '
     '<bdi>%s%s</bdi> خلال الأشهر الخمسة حتى ديسمبر، وتشمل المتاجر والتجارة الإلكترونية والبيع '
     'بالجملة والمنصات الخارجية.</span>' % (RS, n0(PLAN), RS, n2(rem)))
sub1('<i style="width:58.4%"></i>', '<i style="width:%.1f%%"></i>' % pct)
sub1('<span class="en">58.4% of starting credit remaining · 41.6% consumed</span>'
     '<span class="ar">58.4% من الائتمان الأولي متبقٍ · 41.6% مستهلك</span>',
     '<span class="en">%.1f%% of the annual plan achieved · %.1f%% still to earn</span>'
     '<span class="ar">%.1f%% من الخطة السنوية تحقق · %.1f%% متبقٍ</span>'
     % (pct, 100 - pct, pct, 100 - pct))

sub1('<span class="en">Credit sources</span><span class="ar">مصادر الائتمان</span>',
     '<span class="en">Plan sources</span><span class="ar">مكونات الخطة</span>')
sub1('<span class="en">PO 1</span><span class="ar">أمر الشراء 1</span>',
     '<span class="en">Base plan · H1 2026</span><span class="ar">الخطة الأساسية · النصف الأول 2026</span>')
sub1('<span class="en">PO 2 · inc. enhanced support</span>'
     '<span class="ar">أمر الشراء 2 · شامل الدعم المتقدم</span>',
     '<span class="en">Base plan · H2 2026 · inc. seasonal campaign</span>'
     '<span class="ar">الخطة الأساسية · النصف الثاني 2026 · شامل الحملة الموسمية</span>')
sub1('<span class="en">Google incentive · NotebookLM</span>'
     '<span class="ar">حافز Google · NotebookLM</span>',
     '<span class="en">Marketplace expansion uplift</span>'
     '<span class="ar">إضافة التوسع في المنصات الخارجية</span>')
sub1('<span class="en">Fully utilized</span><span class="ar">مستهلك بالكامل</span>',
     '<span class="en">Closed · achieved</span><span class="ar">مغلق · تحقق</span>', n=2)
sub1('<bdi>%s333,782.21</bdi>' % RS, '<bdi>%s54,000,000.00</bdi>' % RS)
sub1('<span class="en">%s5,654,114.44 remaining</span>'
     '<span class="ar">متبقٍ 5,654,114.44 ريالاً</span>' % RS,
     '<span class="en">%s%s remaining to plan</span>'
     '<span class="ar">يتبقى %s%s على الخطة</span>' % (RS, n2(rem), RS, n2(rem)))
sub1('<bdi>%s9,351,453.60</bdi>' % RS, '<bdi>%s66,000,000.00</bdi>' % RS)
sub1('<bdi>%s1,687,500.00</bdi>' % RS, '<bdi>%s3,200,000.00</bdi>' % RS)
sub1('<span class="en">Of the remaining balance</span><span class="ar">من الرصيد المتبقي</span>',
     '<span class="en">Of the remaining plan</span><span class="ar">من الخطة المتبقية</span>')
COMMITTED = 18_400_000
sub1('<bdi>%s1,882,086.75</bdi>' % RS, '<bdi>%s%s</bdi>' % (RS, n0(COMMITTED)))
sub1('<span class="en">committed (SecOps + SCC)</span><span class="ar">مخصص (SecOps و SCC)</span>',
     '<span class="en">committed (contracted wholesale orders)</span>'
     '<span class="ar">مؤكد (طلبات جملة متعاقد عليها)</span>')
sub1('<bdi>%s3,772,027.69</bdi>' % RS, '<bdi>%s%s</bdi>' % (RS, n2(rem - COMMITTED)))
sub1('<span class="en">uncommitted</span><span class="ar">غير مخصص</span>',
     '<span class="en">still to win</span><span class="ar">لم يُحقق بعد</span>')

# ---------------------------------------------------------------- 7 · periods
sub1('<span class="en">Contract to date</span><span class="ar">منذ بداية العقد</span>',
     '<span class="en">Year to date</span><span class="ar">السنة حتى تاريخه</span>')
for en, ar in [('October 2025 to July 2026', 'أكتوبر 2025 إلى يوليو 2026')]:
    s = s.replace('<bdi>%s</bdi>' % en, '<bdi>January to July 2026</bdi>')
    s = s.replace('<bdi>%s</bdi>' % ar, '<bdi>يناير إلى يوليو 2026</bdi>')

# ---------------------------------------------------------------- 8 · footer
i = s.index('<footer class="foot">'); j = span(s, i, 'footer')
s = s[:i] + (
  '<footer class="foot"><div class="init"><span class="en">A template, not a real report</span>'
  '<span class="ar">قالب عرض، وليس تقريراً حقيقياً</span></div>'
  '<span class="en">Northwind Retail Group · Commercial Planning · fictional company, sample data</span>'
  '<span class="ar">مجموعة نورث ويند للتجزئة · التخطيط التجاري · شركة افتراضية وبيانات تجريبية</span><br/>'
  '<span class="en">Version v1 · Single file, no JavaScript required, English and Arabic · '
  'Data as of 31 July 2026 · Published 8 August 2026</span>'
  '<span class="ar">الإصدار v1 · ملف واحد لا يحتاج JavaScript، بالعربية والإنجليزية · '
  'البيانات حتى 31 يوليو 2026 · النشر 8 أغسطس 2026</span><br/>'
  '<span class="en">Replace the wordmark, the logo slot, the palette and the figures with your own.</span>'
  '<span class="ar">استبدل الاسم وخانة الشعار والألوان والأرقام بما يخص جهتك.</span></footer>') + s[j:]

# ---------------------------------------------------------------- 9 · scripts
sub1("const periodMap = { 'pv-m': 'month', 'pv-q': 'quarter', 'pv-t': 'contract' };",
     "const periodMap = { 'pv-m': 'month', 'pv-q': 'quarter', 'pv-t': 'ytd' };")
sub1("const periodLabel = { month: 'July 2026', quarter: 'H1 2026', "
     "contract: '1 Oct 2025–31 Jul 2026' };",
     "const periodLabel = { month: 'July 2026', quarter: 'H1 2026', "
     "ytd: 'January to July 2026' };")
sub1("/period=(month|quarter|contract)/", "/period=(month|quarter|ytd)/")
sub1("const baseTitle = 'MoEnergy GCP FinOps Report';",
     "const baseTitle = 'Northwind Retail · Sales Analytics Report';")
# the logo video handlers have nothing to drive any more
sub1("const v=document.querySelector('video.dew-motion');\n"
     "  if(v){v.loop=false;v.addEventListener('ended',()=>{try{v.currentTime=Math.max(0,v.duration-.05);"
     "v.pause();}catch(e){}});}", '')

# -------------------------------------------------------------- 10 · print CSS
sub1("content:'Reporting period: 1 Oct 2025 to 31 Jul 2026'",
     "content:'Reporting period: January to July 2026'")
sub1("content:'فترة التقرير: 1 أكتوبر 2025 إلى 31 يوليو 2026'",
     "content:'فترة التقرير: يناير إلى يوليو 2026'")
sub1("content:'طاقتنا رقمية'", "content:''")

# ------------------------------------------------------------- 11 · leftovers
s = s.replace('spark-flow', 'seq-flow')
s = s.replace('SPARK lockup: crisp upper-left identity + oversized quiet lower-left watermark',
              'card lockup: crisp upper-left identity + quiet lower-left watermark')
s = s.replace('Run the SPARK connector sequence once, only when the highlight enters the viewport.',
              'Run the connector sequence once, only when the highlight enters the viewport.')
s = s.replace('Animation restoration + fully integrated SPARK highlight',
              'Hero lockup and highlight styling')
s = s.replace('SPARK blade divider, sharp edged, blue to green',
              'blade divider, sharp edged, blue to green')
s = s.replace('SPARK animation: the figure fits itself with CSS media queries, so the',
              'figure animation: it fits itself with CSS media queries, so the')
# the hero ornament layer is named after the identity it came from; the demo just
# calls it an effects layer. Order matters: the longest token goes first.
for a, b in [('de-motifs', 'fx-motifs'), ('de-mo', 'fx-mo'), ('de-glass', 'fx-glass'),
             ('de-sheen', 'fx-sheen'), ('de-drift', 'fx-drift')]:
    s = s.replace(a, b)
assert not re.search(r'\bde-[a-z]', s)
# class names and code comments carried the old subject matter too
s = s.replace('summary-half--gcp', 'summary-half--a').replace('summary-half--sandbox', 'summary-half--b')
s = s.replace('Ministry lockup clear-space correction', 'logo slot clear-space correction')
s = s.replace('Exact supplied Digital Energy motion, once, then held on final frame',
              'hero lockup row')
s = s.replace('Transparent APNG version of the supplied Digital Energy motion.\n'
              '   It preserves the exact motion while removing the opaque video canvas.',
              'left over from the animated lockup this build does not ship.')
s = s.replace('the bridge between the GCP section and the sandbox section: quieter than a',
              'the bridge between a section and its sub-section: quieter than a')
s = s.replace('department donut plus an HTML readout, so the Riyal mark is the same token',
              'donut plus an HTML readout, so the currency mark is the same token')
s = s.replace('donut: a bigger ring in the same footprint, with the centre in HTML so the\n'
              '   Riyal mark sits with the figure',
              'donut: a bigger ring in the same footprint, with the centre in HTML so the\n'
              '   currency mark sits with the figure')

# ------------------------------------------------------------- 12 · new styles
STYLE = """
<style id="demo-neutral">
/* the currency mark: the original masked a drawn glyph, the demo just prints a sign */
.rs{-webkit-mask:none!important;mask:none!important;background:none!important;
  width:auto!important;height:auto!important;display:inline!important;
  vertical-align:baseline!important;margin-inline-end:.05em!important}
.rs::before{content:"$"}
/* the full stop after the wordmark: a flat accent dot, not a borrowed mark */
.orb{background:#3FC4BC!important;background-image:none!important;
  box-shadow:0 0 .5em rgba(63,196,188,.38)!important}
/* where the reader drops their own logo */
.logo-slot{display:flex;align-items:center;justify-content:center;height:44px;min-width:150px;
  padding:0 18px;border:1px dashed rgba(255,255,255,.34);border-radius:8px;
  font:600 10px/1 'IBM Plex Sans Arabic','Segoe UI',sans-serif;letter-spacing:.22em;
  text-transform:uppercase;color:rgba(228,238,255,.6);background:rgba(255,255,255,.04)}
@media(max-width:900px){.logo-slot{height:36px;min-width:118px;font-size:9px;letter-spacing:.16em}}
@media print{.logo-slot{border-color:rgba(255,255,255,.5);color:rgba(228,238,255,.7)}}
</style>
"""
i = s.rindex('</head>')
s = s[:i] + STYLE + s[i:]

# ------------------------------------------------------------- 13 · the sweep
BANNED = ['MoEnergy', 'Ministry', 'وزارة', 'Digital Energy', 'طاقتنا', 'SPARK', 'ITDT', 'Lafet',
          'GCP', 'Google', 'Chronicle', 'Fortinet', 'FortiGate', 'BIG-IP', 'NotebookLM', 'Vertex',
          'sandbox', 'Sandbox', 'Riyal', 'ريال', 'SAR', 'IT Strategy', 'FinOps', 'FINOPS',
          'moe-', 'prd-', 'prj-', 'Cybersecurity', 'purchase-order', 'أمر الشراء', 'الطاقة']
# base64 payloads are noise for a text sweep: a random woff2 blob contains 'GCP'
flat = re.sub(r'data:[a-z0-9/+.-]+;base64,[A-Za-z0-9+/=]+', '[[B64]]', s)
bad = [(w, flat.count(w)) for w in BANNED if w in flat]
if bad:
    for w, _n in bad:
        for m in re.finditer(re.escape(w), flat):
            print('LEFTOVER %-16s ...%s...' % (w, flat[max(0, m.start()-120):m.start()+120].replace('\n', ' ')))
    raise SystemExit('sweep failed: %r' % bad)
assert 'data:font/otf' not in s
assert s.count('data:image/png;base64,') == 0, s.count('data:image/png;base64,')
assert '—' not in s, 'em dash'
assert '§' not in s

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8').write(s)
print('%.2f MB -> %.2f MB   %s' % (before / 1e6, len(s) / 1e6, OUT))
print('year to date net sales: %s' % n2(td_net))
