(()=>{
const D=window.TRIP_DATA;
const icons={history:'🏛️',leisure:'🎭',food:'🍽️',shopping:'🛍️',stay:'🛏️',airport:'✈️',transfer:'🚗'};
const state={day:'ALL',routes:true,pins:true,showRecommended:true,stays:JSON.parse(localStorage.getItem('tn-stays-v3')||'{}'),activities:JSON.parse(localStorage.getItem('tn-activities-v3')||'{}')};
D.staySegments.forEach(s=>{if(!state.stays[s.id])state.stays[s.id]=s.default});
D.activities.forEach(a=>{if(state.activities[a.id]===undefined)state.activities[a.id]=a.selected});
const save=()=>{localStorage.setItem('tn-stays-v3',JSON.stringify(state.stays));localStorage.setItem('tn-activities-v3',JSON.stringify(state.activities));};
function photoRail(images,alt){return `<div class="photo-rail">${(images||[]).map((u,i)=>`<img loading="lazy" src="${u}" alt="${alt} photo ${i+1}" onerror="this.style.display='none'">`).join('')}</div>`}
function stayBySegment(id){const seg=D.staySegments.find(s=>s.id===id);return seg?.options.find(o=>o.id===state.stays[id])}
function catIcon(c){return icons[c]||'•'}
function renderDays(){const items=[{id:'ALL',date:'Overall'},...D.days];document.querySelector('#topDays').innerHTML=items.map(x=>`<button class="day-chip ${state.day===x.id?'active':''}" data-day="${x.id}">${x.id==='ALL'?'Overall':x.id+' · '+x.date}</button>`).join('');document.querySelectorAll('.day-chip').forEach(b=>b.onclick=()=>{state.day=b.dataset.day;renderDays();renderMap()});}
function renderStays(){document.querySelector('#staySegments').innerHTML=D.staySegments.map(seg=>`<div class="stay-segment"><div class="segment-head"><div><h3>${seg.label}</h3><p>${seg.dates}</p></div><span class="segment-badge">${seg.badge}</span></div><div class="stay-rail">${seg.options.map(o=>`<article class="stay-card ${state.stays[seg.id]===o.id?'selected':''}">${photoRail(o.images,o.name)}<div class="stay-body"><div class="stay-tags"><span class="tag private">${o.type}</span>${o.hybrid?'<span class="tag hybrid">DAR + SEA</span>':''}<span class="tag">${o.tag}</span></div><div class="stay-title-row"><h3>${o.name}</h3><span class="stay-score">${o.score}</span></div><div class="stay-meta">${o.guests} · ${o.rating}</div><p>${o.note}</p><div class="stay-actions"><button class="choose-stay ${state.stays[seg.id]===o.id?'selected':''}" data-seg="${seg.id}" data-stay="${o.id}">${state.stays[seg.id]===o.id?'✓ Chosen':'Choose'}</button><a class="open-link" href="${o.url}" target="_blank" rel="noopener">Open listing ↗</a></div></div></article>`).join('')}</div></div>`).join('');document.querySelectorAll('.choose-stay').forEach(b=>b.onclick=()=>{state.stays[b.dataset.seg]=b.dataset.stay;save();renderStays();renderSchedule();renderMap()});}
function dayStops(day){let arr=D.fixed.filter(x=>x.day===day).map(x=>({...x}));D.activities.filter(a=>a.day===day&&state.activities[a.id]).forEach(a=>arr.push({...a}));const dayDef=D.days.find(d=>d.id===day);if(dayDef?.overnight){const s=stayBySegment(dayDef.overnight);if(s)arr.push({id:`stay-${day}`,day,time:'Night',order:98,name:s.name,category:'stay',lat:s.lat,lng:s.lng,description:`Selected overnight: ${s.name}`,images:s.images,url:s.url});}return arr.sort((a,b)=>(a.order||0)-(b.order||0));}
function renderSchedule(){document.querySelector('#schedule').innerHTML=D.days.map((d,i)=>{const stops=dayStops(d.id);const overnight=d.overnight?stayBySegment(d.overnight):null;return `<article class="day-card"><div class="day-summary" data-expand="${d.id}"><div class="day-summary-left"><div class="day-num">${i+1}</div><div><b>${d.date} · ${d.title}</b><small>${stops.filter(s=>s.category!=='stay').length} planned stops${overnight?' · '+overnight.name:''}</small></div></div><span>⌄</span></div><div class="day-details ${i>1?'hidden':''}" id="detail-${d.id}">${stops.filter(s=>s.category!=='stay').map(s=>`<div class="timeline-row"><time>${s.time||''}</time><span class="timeline-icon">${catIcon(s.category)}</span><div><b>${s.name}</b><p>${s.description||''}</p></div></div>`).join('')}${overnight?`<div class="overnight">🛏 <b>Overnight:</b> ${overnight.name}</div>`:''}</div></article>`}).join('');document.querySelectorAll('[data-expand]').forEach(x=>x.onclick=()=>document.querySelector('#detail-'+x.dataset.expand).classList.toggle('hidden'));}
function renderChoices(){['history','leisure'].forEach(kind=>{let list=D.activities.filter(a=>a.kind===kind&&(state.showRecommended?a.recommended:true));document.querySelector('#'+kind+'List').innerHTML=list.map(a=>{const imgs=D.images[a.img]||[];const on=!!state.activities[a.id];return `<article class="choice-card ${on?'':'off'}">${photoRail(imgs,a.name)}<div class="choice-body"><div class="choice-head"><div><h3>${a.name}</h3><div class="choice-chips"><span>${a.day}</span><span>${a.city}</span><span>${catIcon(a.category)} ${a.category}</span></div></div><button class="choice-toggle" data-act="${a.id}">${on?'✓ Included':'+ Add'}</button></div><p class="choice-desc">${a.description}</p>${a.relation?`<div class="relation"><b>Relates to:</b> ${a.relation}</div>`:''}${a.history?`<details><summary class="more">History behind it</summary><p class="choice-desc">${a.history} <a href="${a.source}" target="_blank" rel="noopener">Source ↗</a></p></details>`:''}</div></article>`}).join('');});document.querySelectorAll('.choice-toggle').forEach(b=>b.onclick=()=>{state.activities[b.dataset.act]=!state.activities[b.dataset.act];save();renderChoices();renderSchedule();renderMap()});}
let map,markerLayer,routeLayer;
function markerIcon(category,color){return L.divIcon({className:'',html:`<div class="emoji-marker" style="--marker:${color}">${catIcon(category)}</div>`,iconSize:[36,36],iconAnchor:[18,18],popupAnchor:[0,-17]})}
function popup(s){const imgs=s.images?.length?s.images:(s.img?D.images[s.img]:[]);return `${imgs?.length?`<div class="popup-gallery">${imgs.slice(0,3).map(u=>`<img src="${u}" alt="${s.name}" onerror="this.style.display='none'">`).join('')}</div>`:''}<div class="popup-meta">${s.day||''} · ${s.time||''} · ${catIcon(s.category)} ${s.category}</div><b>${s.name}</b><div class="popup-text">${s.description||''}</div>${s.relation?`<div class="popup-text"><b>Relates to:</b> ${s.relation}</div>`:''}${s.url?`<a class="open-link" href="${s.url}" target="_blank">Open ↗</a>`:''}`}
async function addRoute(stops,color){if(stops.length<2)return;const coords=stops.map(s=>`${s.lng},${s.lat}`).join(';');try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`);const j=await r.json();if(j.routes?.[0]){L.geoJSON(j.routes[0].geometry,{style:{color,weight:4,opacity:.62}}).addTo(routeLayer);return}}catch(e){}L.polyline(stops.map(s=>[s.lat,s.lng]),{color,weight:4,opacity:.45,dashArray:'7 8'}).addTo(routeLayer);}
async function renderMap(){if(!map){map=L.map('tripMap',{scrollWheelZoom:false}).setView([36.25,10.35],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map)}markerLayer.clearLayers();routeLayer.clearLayers();const days=state.day==='ALL'?D.days.map(d=>d.id):[state.day];let all=[];for(const day of days){let stops=dayStops(day);all.push(...stops);if(state.pins){stops.forEach(s=>L.marker([s.lat,s.lng],{icon:markerIcon(s.category,D.dayColors[day])}).bindPopup(popup(s),{maxWidth:285}).addTo(markerLayer))}if(state.routes){await addRoute(stops,D.dayColors[day])}}if(all.length){const b=L.latLngBounds(all.map(s=>[s.lat,s.lng]));map.fitBounds(b.pad(.16),{maxZoom:state.day==='ALL'?8:11})}setTimeout(()=>map.invalidateSize(),80);}
function renderSources(){document.querySelector('#sources').innerHTML=`<div class="sources-grid">${D.sources.map(s=>`<a href="${s[1]}" target="_blank">${s[0]} ↗</a>`).join('')}</div><p class="choice-desc">Stay availability and ratings are a planning snapshot checked 12 Sep 2026. Private-rental listings can change or disappear; verify the exact listing, accessibility and cancellation rules before paying.</p>`}
function bindUI(){document.querySelector('#routesToggle').onclick=e=>{state.routes=!state.routes;e.currentTarget.classList.toggle('active',state.routes);renderMap()};document.querySelector('#pinsToggle').onclick=e=>{state.pins=!state.pins;e.currentTarget.classList.toggle('active',state.pins);renderMap()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#historyList').classList.toggle('hidden',b.dataset.tab!=='history');document.querySelector('#leisureList').classList.toggle('hidden',b.dataset.tab!=='leisure')});document.querySelector('#recommendedBtn').onclick=e=>{state.showRecommended=!state.showRecommended;e.currentTarget.textContent=state.showRecommended?'Recommended only':'Showing all options';renderChoices()};document.querySelector('#restoreBtn').onclick=()=>{D.staySegments.forEach(s=>state.stays[s.id]=s.default);D.activities.forEach(a=>state.activities[a.id]=a.selected);save();renderStays();renderSchedule();renderChoices();renderMap()};}
renderDays();renderStays();renderSchedule();renderChoices();renderSources();bindUI();renderMap();save();
})();