(()=>{
const D=window.TRIP_DATA;
if(!D)return;

const icons={history:'🏛️',leisure:'🎭',food:'🍽️',shopping:'🛍️',stay:'🛏️',airport:'✈️',transfer:'🚗'};
const state={
  day:'ALL',
  routes:true,
  pins:true,
  showRecommended:false,
  stays:JSON.parse(localStorage.getItem('tn-stays-v3')||'{}'),
  activities:JSON.parse(localStorage.getItem('tn-activities-v3')||'{}')
};

D.staySegments.forEach(s=>{if(!state.stays[s.id])state.stays[s.id]=s.default});
D.activities.forEach(a=>{if(state.activities[a.id]===undefined)state.activities[a.id]=a.selected});
const slotSeen=new Set();
D.activities.forEach(a=>{if(!a.slot||!state.activities[a.id])return;if(slotSeen.has(a.slot))state.activities[a.id]=false;else slotSeen.add(a.slot)});
const save=()=>{localStorage.setItem('tn-stays-v3',JSON.stringify(state.stays));localStorage.setItem('tn-activities-v3',JSON.stringify(state.activities))};
const notify=()=>document.dispatchEvent(new CustomEvent('trip:updated'));
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function photoRail(images,alt){const safe=(images||[]).filter(Boolean);return `<div class="photo-rail">${safe.map((u,i)=>`<img loading="lazy" src="${esc(u)}" alt="${esc(alt)} photo ${i+1}" onerror="this.style.display='none'">`).join('')}</div>`}
function stayBySegment(id){const seg=D.staySegments.find(s=>s.id===id);return seg?.options.find(o=>o.id===state.stays[id])||seg?.options[0]}
function catIcon(c){return icons[c]||'•'}
function score(v){return Number.isFinite(Number(v))?`${Number(v).toFixed(Number(v)%1?1:0)}/10`:'—'}
function safeLink(url){return /^https:\/\//i.test(url||'')}
function renderDays(){const items=[{id:'ALL',date:'Overall'},...D.days];document.querySelector('#topDays').innerHTML=items.map(x=>`<button class="day-chip ${state.day===x.id?'active':''}" data-day="${x.id}">${x.id==='ALL'?'Overall':x.id+' · '+x.date}</button>`).join('');document.querySelectorAll('.day-chip').forEach(b=>b.onclick=()=>{state.day=b.dataset.day;renderDays();renderMap();notify()})}
function renderStays(){const host=document.querySelector('#staySegments');host.innerHTML=D.staySegments.map(seg=>{const options=[...seg.options].sort((a,b)=>(b.score||0)-(a.score||0));return `<div class="stay-segment" data-segment="${esc(seg.id)}"><div class="segment-head"><div><h3>${esc(seg.label)}</h3><p>${esc(seg.dates)}</p></div><span class="segment-badge">${esc(seg.badge)}</span></div><div class="stay-rail">${options.map((o,i)=>{const selected=state.stays[seg.id]===o.id;return `<article class="stay-card ${selected?'selected':''}">${i===0?'<div class="best-ribbon">BEST OPTION</div>':''}${photoRail(o.images,o.name)}<div class="stay-body"><div class="stay-tags"><span class="tag private">${esc(o.type||'Stay')}</span>${o.hybrid?'<span class="tag hybrid">DAR + SEA</span>':''}${o.fromWhatsApp?'<span class="tag whatsapp-tag">WHATSAPP GROUP</span>':''}<span class="tag">${esc(o.tag||'Option')}</span></div><div class="stay-title-row"><h3>${esc(o.name)}</h3><span class="stay-score">${Number.isFinite(Number(o.score))?Math.round(Number(o.score)):'—'}</span></div><div class="stay-meta">${esc(o.guests||'Verify capacity')} · ${esc(o.rating||'Verify availability')}</div><div class="stay-metrics"><div><span>✨ Experience</span><b>${score(o.experience)}</b></div><div><span>🔒 Privacy</span><b>${score(o.privacy)}</b></div><div><span>💰 Price</span><b>${score(o.priceScore)}</b><small>${esc(o.priceTier||'Verify')}</small></div></div><p>${esc(o.note||'Verify the exact property details before booking.')}</p><div class="stay-actions"><button class="choose-stay ${selected?'selected':''}" data-seg="${esc(seg.id)}" data-stay="${esc(o.id)}">${selected?'✓ Chosen':'Choose'}</button>${safeLink(o.url)?`<a class="open-link" href="${esc(o.url)}" target="_blank" rel="noopener">Open listing ↗</a>`:''}</div></div></article>`}).join('')}</div></div>`}).join('');document.querySelectorAll('.choose-stay').forEach(b=>b.onclick=()=>{state.stays[b.dataset.seg]=b.dataset.stay;save();renderStays();renderSchedule();renderMap();notify()})}
function dayStops(day){const arr=D.fixed.filter(x=>x.day===day).map(x=>({...x}));D.activities.filter(a=>a.day===day&&state.activities[a.id]).forEach(a=>arr.push({...a}));const dayDef=D.days.find(d=>d.id===day);if(dayDef?.overnight){const s=stayBySegment(dayDef.overnight);if(s)arr.push({id:`stay-${day}`,day,time:'Night',order:98,name:s.name,category:'stay',lat:s.lat,lng:s.lng,description:`Selected overnight: ${s.name}`,images:s.images,url:s.url})}return arr.sort((a,b)=>(a.order||0)-(b.order||0))}
function renderSchedule(){document.querySelector('#schedule').innerHTML=D.days.map((d,i)=>{const stops=dayStops(d.id),overnight=d.overnight?stayBySegment(d.overnight):null,planStops=stops.filter(s=>s.category!=='stay');return `<article class="day-card"><div class="day-summary" data-expand="${d.id}"><div class="day-summary-left"><div class="day-num">${i+1}</div><div><b>${esc(d.date)} · ${esc(d.title)}</b><small>${planStops.length} planned stops${overnight?' · '+esc(overnight.name):''}</small></div></div><span>⌄</span></div><div class="day-details ${i>1?'hidden':''}" id="detail-${d.id}">${planStops.map(s=>`<div class="timeline-row"><time>${esc(s.time||'')}</time><span class="timeline-icon">${catIcon(s.category)}</span><div><b>${esc(s.name)}</b><p>${esc(s.description||'')}</p></div></div>`).join('')}${overnight?`<div class="overnight">🛏 <b>Overnight:</b> ${esc(overnight.name)}</div>`:''}</div></article>`}).join('');document.querySelectorAll('[data-expand]').forEach(x=>x.onclick=()=>document.querySelector('#detail-'+x.dataset.expand).classList.toggle('hidden'))}
function activityCard(a){const imgs=D.images[a.img]||[],on=!!state.activities[a.id];return `<article class="choice-card ${on?'selected-choice':'off'}" data-slot="${esc(a.slot||'')}">${photoRail(imgs,a.name)}<div class="choice-body"><div class="choice-head"><div><h3>${esc(a.name)}</h3><div class="choice-chips"><span>${esc(a.day)}</span><span>${esc(a.city)}</span><span>${catIcon(a.category)} ${esc(a.category)}</span></div></div><button class="choice-toggle" data-act="${esc(a.id)}">${on?'✓ Selected':'Choose'}</button></div><p class="choice-desc">${esc(a.description)}</p>${a.relation?`<div class="relation"><b>Relates to:</b> ${esc(a.relation)}</div>`:''}${a.history?`<details><summary class="more">History behind it</summary><p class="choice-desc">${esc(a.history)} ${safeLink(a.source)?`<a href="${esc(a.source)}" target="_blank" rel="noopener">Source ↗</a>`:''}</p></details>`:''}${safeLink(a.url)?`<a class="activity-book-link" href="${esc(a.url)}" target="_blank" rel="noopener">Open / book ↗</a>`:''}</div></article>`}
function renderChoices(){['history','leisure'].forEach(kind=>{let list=D.activities.filter(a=>a.kind===kind);if(state.showRecommended)list=list.filter(a=>a.recommended);const groups=new Map();list.forEach(a=>{const key=a.slot||`${a.day}-${a.time}-${a.kind}`;if(!groups.has(key))groups.set(key,{label:a.slotLabel||`${a.day} · ${a.time}`,items:[]});groups.get(key).items.push(a)});document.querySelector('#'+kind+'List').innerHTML=[...groups.entries()].map(([slot,g])=>`<section class="slot-group" data-slot-group="${esc(slot)}"><div class="slot-group-head"><div><span class="slot-kicker">${esc(g.items[0]?.day||'')} · ${esc(g.items[0]?.time||'')}</span><h4>${esc(g.label)}</h4></div><button class="skip-slot" data-skip-slot="${esc(slot)}">Skip this slot</button></div><div class="slot-options">${g.items.map(activityCard).join('')}</div></section>`).join('')});document.querySelectorAll('.choice-toggle').forEach(b=>b.onclick=()=>{const a=D.activities.find(x=>x.id===b.dataset.act);if(!a||state.activities[a.id])return;if(a.slot)D.activities.filter(x=>x.slot===a.slot).forEach(x=>state.activities[x.id]=false);state.activities[a.id]=true;save();renderChoices();renderSchedule();renderMap();notify()});document.querySelectorAll('.skip-slot').forEach(b=>b.onclick=()=>{D.activities.filter(x=>x.slot===b.dataset.skipSlot).forEach(x=>state.activities[x.id]=false);save();renderChoices();renderSchedule();renderMap();notify()})}
let map,markerLayer,routeLayer;
function markerIcon(category,color){return L.divIcon({className:'',html:`<div class="emoji-marker" style="--marker:${color}">${catIcon(category)}</div>`,iconSize:[36,36],iconAnchor:[18,18],popupAnchor:[0,-17]})}
function popup(s){const imgs=s.images?.length?s.images:(s.img?D.images[s.img]:[]);return `${imgs?.length?`<div class="popup-gallery">${imgs.slice(0,3).map(u=>`<img src="${esc(u)}" alt="${esc(s.name)}" onerror="this.style.display='none'">`).join('')}</div>`:''}<div class="popup-meta">${esc(s.day||'')} · ${esc(s.time||'')} · ${catIcon(s.category)} ${esc(s.category)}</div><b>${esc(s.name)}</b><div class="popup-text">${esc(s.description||'')}</div>${s.relation?`<div class="popup-text"><b>Relates to:</b> ${esc(s.relation)}</div>`:''}${safeLink(s.url)?`<a class="open-link" href="${esc(s.url)}" target="_blank" rel="noopener">Open ↗</a>`:''}`}
async function addRoute(stops,color){const usable=stops.filter(s=>Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng)));if(usable.length<2)return;const coords=usable.map(s=>`${s.lng},${s.lat}`).join(';');try{const r=await fetch(`https://router.project-osrm.org/route/v1/driving/${coords}?overview=full&geometries=geojson`),j=await r.json();if(j.routes?.[0]){L.geoJSON(j.routes[0].geometry,{style:{color,weight:4,opacity:.62}}).addTo(routeLayer);return}}catch(e){}L.polyline(usable.map(s=>[s.lat,s.lng]),{color,weight:4,opacity:.45,dashArray:'7 8'}).addTo(routeLayer)}
async function renderMap(){if(!map){map=L.map('tripMap',{scrollWheelZoom:false}).setView([36.05,10.35],8);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map)}markerLayer.clearLayers();routeLayer.clearLayers();const days=state.day==='ALL'?D.days.map(d=>d.id):[state.day],all=[];for(const day of days){const stops=dayStops(day).filter(s=>Number.isFinite(Number(s.lat))&&Number.isFinite(Number(s.lng)));all.push(...stops);if(state.pins)stops.forEach(s=>L.marker([s.lat,s.lng],{icon:markerIcon(s.category,D.dayColors[day]||'#0b6b62')}).bindPopup(popup(s),{maxWidth:285}).addTo(markerLayer));if(state.routes)await addRoute(stops,D.dayColors[day]||'#0b6b62')}if(all.length){const b=L.latLngBounds(all.map(s=>[s.lat,s.lng]));map.fitBounds(b.pad(.16),{maxZoom:state.day==='ALL'?8:11})}setTimeout(()=>map.invalidateSize(),80)}
function renderSources(){document.querySelector('#sources').innerHTML=`<div class="sources-grid">${(D.sources||[]).map(s=>`<a href="${esc(s[1])}" target="_blank" rel="noopener">${esc(s[0])} ↗</a>`).join('')}</div><p class="choice-desc">Availability, fares and private-rental listings can change quickly. Recheck the exact dates, accessibility, baggage, cancellation rules and one-ticket protection before paying.</p>`}
function bindUI(){document.querySelector('#routesToggle').onclick=e=>{state.routes=!state.routes;e.currentTarget.classList.toggle('active',state.routes);renderMap();notify()};document.querySelector('#pinsToggle').onclick=e=>{state.pins=!state.pins;e.currentTarget.classList.toggle('active',state.pins);renderMap();notify()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#historyList').classList.toggle('hidden',b.dataset.tab!=='history');document.querySelector('#leisureList').classList.toggle('hidden',b.dataset.tab!=='leisure');notify()});document.querySelector('#recommendedBtn').onclick=e=>{state.showRecommended=!state.showRecommended;e.currentTarget.textContent=state.showRecommended?'Show all 3 per slot':'Show recommended only';renderChoices();notify()};document.querySelector('#restoreBtn').onclick=()=>{D.staySegments.forEach(s=>state.stays[s.id]=s.default);D.activities.forEach(a=>state.activities[a.id]=a.selected);state.showRecommended=false;save();renderStays();renderSchedule();renderChoices();renderMap();notify()}}
function renderAll(){renderDays();renderStays();renderSchedule();renderChoices();renderSources();renderMap();save();notify()}
window.TRIP_APP={D,state,save,renderDays,renderStays,renderSchedule,renderChoices,renderMap,renderSources,renderAll,stayBySegment,dayStops};
renderDays();renderStays();renderSchedule();renderChoices();renderSources();bindUI();renderMap();save();notify();
})();