(()=>{
const carKey='tn-car-v1';
const cars=[
 {id:'jetour-t2',name:'Jetour T2',overall:100,tag:'BEST OPTION',type:'SUV · 5 seats',fit:10,comfort:9.6,priceScore:8.2,price:'Exact rental quote needed',availability:'Request exact model',note:'Your preferred road-trip choice. Spacious, high driving position and well suited to Tunis → Hammamet → Kairouan → Sousse → El Jem. I did not find the T2 in the current Tunis-airport aggregator results, so only book it if the agency guarantees the exact model.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'skoda-kushaq',name:'Škoda Kushaq / Karoq-class SUV',overall:97,tag:'SECOND CHOICE',type:'Compact SUV · 5 seats',fit:9.6,comfort:9.2,priceScore:9.0,price:'Live airport quote',availability:'Kushaq or similar currently listed at TUN',note:'The most grounded backup to the Jetour preference. Good size for three adults, easier in Tunis streets than a very large SUV, and current Tunis-airport search results include a Škoda Kushaq-or-similar SUV class.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'jetour-x70',name:'Jetour X70 / X70 Plus',overall:95,tag:'JETOUR FAMILY SUV',type:'SUV · up to 7 seats',fit:9.5,comfort:9.4,priceScore:8.4,price:'Exact rental quote needed',availability:'Request exact model',note:'More family-oriented than the T2 and excellent if luggage volume matters. Strong Jetour alternative if a Tunis rental agency can source it.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'vw-troc',name:'Volkswagen T-Roc or similar',overall:92,tag:'BEST LIVE VALUE',type:'Compact SUV · 5 seats',fit:9.0,comfort:8.7,priceScore:9.5,price:'From ~SAR 158/day seen on current search',availability:'Currently surfaced at TUN',note:'Very sensible balance of road-trip comfort, easy city size and price. A strong fallback if exact Jetour/Škoda inventory is unavailable.',link:'https://www.skyscanner.com.sa/sa/en-gb/sar/car-hire-from/tun/car-hire-from-tunis-carthage-airport.html'},
 {id:'skoda-karoq',name:'Škoda Karoq',overall:91,tag:'ŠKODA UPGRADE',type:'Compact SUV · 5 seats',fit:9.2,comfort:9.2,priceScore:8.4,price:'Live check',availability:'Ask supplier for exact model',note:'A slightly more premium Škoda SUV choice with a practical cabin and strong long-distance fit.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'peugeot-3008',name:'Peugeot 3008 or similar',overall:89,tag:'COMFORTABLE FRENCH SUV',type:'SUV · 5 seats',fit:9.0,comfort:9.1,priceScore:8.1,price:'Live check',availability:'Common class; exact model varies',note:'Comfortable cabin, good motorway manners and suitable luggage space for three adults.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'hyundai-tucson',name:'Hyundai Tucson or similar',overall:88,tag:'EASY FAMILY PICK',type:'SUV · 5 seats',fit:9.0,comfort:9.0,priceScore:8.0,price:'Live check',availability:'SUV class candidate',note:'Very straightforward family-road-trip option if you value comfort and easy ergonomics over character.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'kia-sportage',name:'Kia Sportage or similar',overall:87,tag:'BALANCED',type:'SUV · 5 seats',fit:8.9,comfort:8.9,priceScore:8.0,price:'Live check',availability:'SUV class candidate',note:'A balanced choice for long driving, luggage and city use.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'nissan-qashqai',name:'Nissan Qashqai or similar',overall:86,tag:'CITY + ROAD',type:'Crossover · 5 seats',fit:8.7,comfort:8.6,priceScore:8.3,price:'Live check',availability:'Crossover class candidate',note:'Easy around Tunis and still comfortable enough for Kairouan and El Jem road days.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'dacia-stepway',name:'Dacia Sandero Stepway or similar',overall:84,tag:'VALUE SUV',type:'Economy SUV · 5 seats',fit:8.2,comfort:7.7,priceScore:9.0,price:'From ~SAR 249/day seen on current search',availability:'Currently surfaced at TUN',note:'Good value and ground clearance, but less refined than the top SUV choices for long family days.',link:'https://www.skyscanner.com.sa/sa/en-gb/sar/car-hire-from/tun/car-hire-from-tunis-carthage-airport.html'},
 {id:'jeep-renegade',name:'Jeep Renegade or similar',overall:83,tag:'AUTOMATIC SUV',type:'SUV · 5 seats',fit:8.4,comfort:8.1,priceScore:6.8,price:'From ~SAR 310/day seen on current search',availability:'Currently surfaced at TUN',note:'Useful if automatic transmission is non-negotiable and the top picks are unavailable, though current pricing can be noticeably higher.',link:'https://www.skyscanner.com.sa/sa/en-gb/sar/car-hire-from/tun/car-hire-from-tunis-carthage-airport.html'},
 {id:'toyota-corolla-cross',name:'Toyota Corolla Cross or similar',overall:82,tag:'RELIABLE',type:'SUV · 5 seats',fit:8.7,comfort:8.5,priceScore:7.6,price:'Live check',availability:'Ask for exact class',note:'A calm, practical family option if a supplier has it in the compact-SUV fleet.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'renault-austral',name:'Renault Austral / Arkana class',overall:81,tag:'FRENCH CROSSOVER',type:'Crossover · 5 seats',fit:8.4,comfort:8.6,priceScore:7.7,price:'Live check',availability:'Ask supplier',note:'Good road comfort and sensible footprint for the Tunis/Hammamet parts of the trip.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'mg-hs',name:'MG HS or similar',overall:80,tag:'ROOMY VALUE',type:'SUV · 5 seats',fit:8.3,comfort:8.5,priceScore:7.8,price:'Live check',availability:'Ask supplier',note:'Worth considering if you find a strong rental quote and want a roomy cabin.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'seat-ateca',name:'SEAT Ateca or similar',overall:79,tag:'DRIVER-FRIENDLY',type:'SUV · 5 seats',fit:8.4,comfort:8.3,priceScore:7.5,price:'Live check',availability:'Ask supplier',note:'A capable compact SUV with a practical size for mixed city and highway driving.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'citroen-c5',name:'Citroën C5 Aircross or similar',overall:78,tag:'SOFT COMFORT',type:'SUV · 5 seats',fit:8.2,comfort:9.0,priceScore:7.1,price:'Live check',availability:'Ask supplier',note:'Strong comfort-focused alternative if your mother prefers a softer ride.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'peugeot-2008',name:'Peugeot 2008 or similar',overall:76,tag:'SMALLER SUV',type:'Compact crossover · 5 seats',fit:7.8,comfort:7.8,priceScore:8.2,price:'Live check',availability:'Ask supplier',note:'Easy to park, but luggage space can become the limiting factor for three adults on a moving trip.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'vw-tiguan',name:'Volkswagen Tiguan or similar',overall:75,tag:'PREMIUM PRACTICAL',type:'SUV · 5 seats',fit:8.6,comfort:9.0,priceScore:6.3,price:'Live check',availability:'Ask supplier',note:'Very good trip fit, but typically worth it only if the price gap versus T-Roc/Škoda is modest.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'toyota-rav4',name:'Toyota RAV4 or similar',overall:74,tag:'LARGE RELIABLE SUV',type:'SUV · 5 seats',fit:8.8,comfort:8.7,priceScore:5.9,price:'Live check',availability:'Ask supplier',note:'Excellent road-trip tool if available, though potentially more expensive and larger than necessary for three adults.',link:'https://www.booking.com/cars/airport/tn/tun.en-gb.html'},
 {id:'suzuki-jimny',name:'Suzuki Jimny or similar',overall:68,tag:'FUN BUT SMALL',type:'Small SUV · 4 seats',fit:6.8,comfort:6.2,priceScore:5.5,price:'From ~US$164/day seen on current search',availability:'Currently surfaced at TUN',note:'Interesting vehicle, but not recommended for this trip because luggage and long-distance comfort are weaker for three adults.',link:'https://www.kayak.com/Tunis-Carthage-Airport-Car-Rentals.TUN.cap.ksp'}
];
let selected=localStorage.getItem(carKey)||cars[0].id;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function render(){
 const host=document.querySelector('#carOptions'),summary=document.querySelector('#carSelected');if(!host||!summary)return;
 const chosen=cars.find(c=>c.id===selected)||cars[0];selected=chosen.id;localStorage.setItem(carKey,selected);
 summary.innerHTML=`<div class="selected-car"><div><span class="selected-label">YOUR CURRENT CAR PICK</span><h4>${esc(chosen.name)}</h4><p>${esc(chosen.type)} · ${esc(chosen.availability)}</p></div><div class="selected-car-score">${chosen.overall}<small>/100</small></div></div>`;
 host.innerHTML=cars.map((c,i)=>`<article class="car-card ${c.id===selected?'chosen':''}">
  ${i===0?'<div class="best-ribbon">BEST OPTION</div>':''}
  <div class="car-card-top"><div><span class="car-rank">#${i+1}</span><span class="car-tag">${esc(c.tag)}</span></div><span class="car-overall">${c.overall}</span></div>
  <h4>${esc(c.name)}</h4><div class="car-type">${esc(c.type)}</div>
  <div class="car-metrics"><div><span>🛣 Road-trip fit</span><b>${c.fit}/10</b></div><div><span>🛋 Comfort</span><b>${c.comfort}/10</b></div><div><span>💰 Price/value</span><b>${c.priceScore}/10</b><small>${esc(c.price)}</small></div></div>
  <div class="car-availability">${esc(c.availability)}</div><p class="car-note-text">${esc(c.note)}</p>
  <div class="car-actions"><button class="choose-car ${c.id===selected?'selected':''}" data-car="${esc(c.id)}">${c.id===selected?'✓ Chosen':'Choose'}</button><a href="${esc(c.link)}" target="_blank" rel="noopener">Check rentals ↗</a></div>
 </article>`).join('');
 host.querySelectorAll('.choose-car').forEach(b=>b.onclick=()=>{selected=b.dataset.car;localStorage.setItem(carKey,selected);render()});
}
const reset=document.querySelector('#restoreBtn');if(reset)reset.addEventListener('click',()=>{selected=cars[0].id;localStorage.setItem(carKey,selected);setTimeout(render,0)});
render();
})();