window.TRIP_DATA = {
  dayColors:{D1:'#3168b3',D2:'#c46a23',D3:'#0b8d81',D4:'#7a56c8',D5:'#a94442',D6:'#3d7b55',D7:'#b5782d',D8:'#656b75'},
  days:[
    {id:'D1',label:'Day 1',date:'Fri 18 Sep',title:'Arrive Tunis + first Medina night',overnight:'Tunis'},
    {id:'D2',label:'Day 2',date:'Sat 19 Sep',title:'Tunis heritage + mother’s shopping spree',overnight:'Tunis'},
    {id:'D3',label:'Day 3',date:'Sun 20 Sep',title:'Carthage + Sidi Bou Said → Hammamet',overnight:'Hammamet'},
    {id:'D4',label:'Day 4',date:'Mon 21 Sep',title:'Hammamet + Nabeul crafts, clothes & coast',overnight:'Hammamet'},
    {id:'D5',label:'Day 5',date:'Tue 22 Sep',title:'Hammamet → Kairouan → Sousse',overnight:'Sousse'},
    {id:'D6',label:'Day 6',date:'Wed 23 Sep',title:'Sousse + El Jem → Tunis',overnight:'Tunis'},
    {id:'D7',label:'Day 7',date:'Thu 24 Sep',title:'Bardo + final Tunis shopping & dinner',overnight:'Tunis'},
    {id:'D8',label:'Day 8',date:'Fri 25 Sep',title:'Fly home',overnight:'Riyadh'}
  ],
  sources:[
    {id:'unesco-tunis',label:'UNESCO — Medina of Tunis',url:'https://whc.unesco.org/en/list/36'},
    {id:'unesco-carthage',label:'UNESCO — Archaeological Site of Carthage',url:'https://whc.unesco.org/en/list/37'},
    {id:'unesco-kairouan',label:'UNESCO — Kairouan',url:'https://whc.unesco.org/en/list/499'},
    {id:'unesco-sousse',label:'UNESCO — Medina of Sousse',url:'https://whc.unesco.org/en/list/498'},
    {id:'unesco-eljem',label:'UNESCO — Amphitheatre of El Jem',url:'https://whc.unesco.org/en/list/38'},
    {id:'heritage-hammamet',label:'Tunisia Heritage Agency — Hammamet Citadel',url:'https://www.patrimoinedetunisie.com.tn/en/monuments/the-citadel-borj-of-hammamet/overview/'},
    {id:'inp-tunis',label:'National Heritage Institute — Tunis Medina / Chechia souks',url:'https://www.inp2020.tn/en/2020/01/28/medina-de-tunis/'},
    {id:'discover-nabeul',label:'Discover Tunisia — Nabeul & Cap Bon shopping',url:'https://www.discovertunisia.com/en/discover/nabeul-and-cap-bon'},
    {id:'discover-hammamet',label:'Discover Tunisia — Hammamet shopping',url:'https://www.discovertunisia.com/ar/%D8%A5%D9%83%D8%AA%D8%B4%D9%81/%D8%AD%D9%88%D9%84-%D8%A7%D9%84%D8%AD%D9%85%D8%A7%D9%85%D8%A7%D8%AA'},
    {id:'discover-kairouan',label:'Discover Tunisia — Around Kairouan',url:'https://www.discovertunisia.com/en/discover/around-kairouan'},
    {id:'discover-sousse',label:'Discover Tunisia — Sousse & Port El Kantaoui',url:'https://www.discovertunisia.com/en/discover/around-sousse-and-port-el-kantaoui'},
    {id:'souk-leffa',label:'Souk El Leffa — textiles and Tunisian clothing',url:'https://en.wikipedia.org/wiki/Souk_El_Leffa'},
    {id:'souk-kmach',label:'Souk El Kmach — fabric market',url:'https://en.wikipedia.org/wiki/Souk_El_Kmach'},
    {id:'artounsi',label:'Souk El Kahina — ArTounsi locally made clothing',url:'https://soukelkahina.tn/en/shop/artounsi?id_category=135'}
  ],
  stays:{
    Tunis:{nights:'18–19 Sep + 23–24 Sep',options:[
      {id:'tunis-gacem',name:'Dar Ben Gacem',score:97,tag:'Most authentic',note:'Restored Medina house and strongest “live inside old Tunis” feeling.',lat:36.8018,lng:10.1686,wiki:'Medina of Tunis',url:'https://www.darbengacem.com/'},
      {id:'tunis-turkia',name:'Dar Ben Turkia',score:95,tag:'Best for 3 + mother',note:'Traditional house with spacious suites and hammam; easier comfort profile.',lat:36.7985,lng:10.1689,wiki:'Medina of Tunis',url:'https://www.darbenturkia.com/en/home-en-dar-ben-turkia/'},
      {id:'tunis-jeld',name:'Dar El Jeld Hotel & Spa',score:92,tag:'Most comfortable',note:'Historic setting, large suites, spa and polished service.',lat:36.8006,lng:10.1680,wiki:'Medina of Tunis',url:'https://www.dareljeld.com/'}]},
    Hammamet:{nights:'20–21 Sep',options:[
      {id:'ham-dar',name:'Dar Hammamet Guest House & Hammam',score:96,tag:'Best authentic Hammamet',note:'Small traditional guesthouse inside the old Medina, rooftop and hammam atmosphere.',lat:36.3999,lng:10.6143,wiki:'Hammamet, Tunisia',url:'https://www.dar-hammamet.com/index.html'},
      {id:'ham-sindbad',name:'The Sindbad',score:87,tag:'Comfort + beach',note:'Better if your mother wants easier resort comfort while staying close to old Hammamet.',lat:36.4075,lng:10.5942,wiki:'Hammamet, Tunisia',url:'https://www.google.com/search?q=The+Sindbad+Hammamet'},
      {id:'ham-badira',name:'La Badira',score:84,tag:'Luxury seaside',note:'A polished beachfront option; less traditional than a dar, much easier for pure comfort.',lat:36.4295,lng:10.6800,wiki:'Hammamet, Tunisia',url:'https://www.google.com/search?q=La+Badira+Hammamet'}]},
    Sousse:{nights:'22 Sep',options:[
      {id:'sou-lekbira',name:'Dar Lekbira Boutique Hôtel',score:95,tag:'Best traditional Sousse',note:'Traditional-style Medina boutique stay close to souqs and monuments.',lat:35.8268,lng:10.6370,wiki:'Medina of Sousse',url:'https://www.google.com/search?q=Dar+Lekbira+Boutique+Hotel+Sousse'},
      {id:'sou-baaziz',name:'Dar Baaziz',score:93,tag:'Most intimate',note:'Authentic Medina guesthouse with courtyard character and local feel.',lat:35.8260,lng:10.6360,wiki:'Medina of Sousse',url:'https://www.google.com/search?q=Dar+Baaziz+Sousse'},
      {id:'sou-antonia',name:'Dar Antonia',score:88,tag:'Boutique comfort',note:'Artful Medina riad/hotel with more design-forward rooms.',lat:35.8269,lng:10.6385,wiki:'Medina of Sousse',url:'https://www.google.com/search?q=Dar+Antonia+Sousse'}]}
  },
  fixedStops:[
    {id:'arrive',day:'D1',time:'12:00',order:1,name:'Tunis–Carthage Airport',category:'airport',lat:36.8510,lng:10.2272,wiki:'Tunis–Carthage International Airport',description:'Land in Tunis, collect bags and meet the pre-booked driver.'},
    {id:'d3-transfer',day:'D3',time:'19:00',order:90,name:'Drive to Hammamet',category:'transfer',lat:36.4010,lng:10.6150,wiki:'Hammamet, Tunisia',description:'Leave Sidi Bou Said after sunset and continue south to your Hammamet base.'},
    {id:'d5-transfer',day:'D5',time:'07:30',order:1,name:'Hammamet → Kairouan',category:'transfer',lat:35.9800,lng:10.3600,wiki:'Kairouan',description:'Private driver with luggage. This is the start of the central-Tunisia leg.'},
    {id:'d5-sousse',day:'D5',time:'15:00',order:70,name:'Kairouan → Sousse',category:'transfer',lat:35.8270,lng:10.6380,wiki:'Sousse',description:'Continue east to Sousse and check in before the late-afternoon Medina walk.'},
    {id:'d6-return',day:'D6',time:'14:30',order:80,name:'El Jem → Tunis',category:'transfer',lat:36.7900,lng:10.1800,wiki:'Tunis',description:'Return north to Tunis for the final two nights.'},
    {id:'depart',day:'D8',time:'Flight',order:90,name:'Tunis–Carthage Airport',category:'airport',lat:36.8510,lng:10.2272,wiki:'Tunis–Carthage International Airport',description:'Return flight to Riyadh. Reconfirm whether your itinerary lands in Riyadh Friday or Saturday.'}
  ],
  activities:[
    {id:'h-tunis-medina',kind:'history',selected:true,day:'D1',time:'16:00',order:20,name:'Medina of Tunis orientation',city:'Tunis',category:'history',lat:36.7986,lng:10.1710,wiki:'Medina of Tunis',relation:'Almohad & Hafsid Tunis; later Ottoman/Husainid layers; classical Arabo-Muslim urban form.',history:'Tunis became one of the great and wealthy cities of the Islamic world under the Almohads and Hafsids. UNESCO notes roughly 700 monuments across its palaces, mosques, madrasas, mausoleums and fountains.',description:'Start with Bab Bhar and the old lanes to understand the city before the deeper tour tomorrow.',source:'unesco-tunis'},
    {id:'h-zitouna',kind:'history',selected:true,day:'D2',time:'09:00',order:10,name:'Zitouna Mosque quarter',city:'Tunis',category:'history',lat:36.7976,lng:10.1705,wiki:'Al-Zaytuna Mosque',relation:'Religious and scholarly life of medieval Tunis; the core around which major souqs developed.',history:'UNESCO identifies Zitouna among the Medina’s most important monuments. The surrounding specialized souqs show how worship, learning and commerce were woven together in the old city.',description:'Go early, then flow directly into the fabric and chechia souqs.',source:'unesco-tunis'},
    {id:'h-dars',kind:'history',selected:true,day:'D2',time:'10:30',order:20,name:'Historic dars + Tourbet El Bey',city:'Tunis',category:'history',lat:36.7939,lng:10.1701,wiki:'Medina of Tunis',relation:'Ottoman/Husainid elite domestic architecture and royal funerary culture.',history:'The Medina’s later centuries added palaces, noble residences, zaouias and madrasas. This stop connects the courtyard-house “dar” experience to the city’s political and family history.',description:'Guide-led look at traditional courtyard architecture, tilework and elite urban life.',source:'unesco-tunis'},
    {id:'h-carthage',kind:'history',selected:true,day:'D3',time:'09:00',order:10,name:'Carthage — Byrsa Hill',city:'Carthage',category:'history',lat:36.8535,lng:10.3233,wiki:'Carthage',relation:'Phoenician/Punic Mediterranean empire; Hannibal; Punic Wars; Roman refoundation.',history:'Founded in the 9th century BC, Carthage grew into a major Mediterranean trading power. Rome destroyed Punic Carthage in 146 BC and later built a Roman city on the site.',description:'Start here for the full timeline before visiting the baths and ports.',source:'unesco-carthage'},
    {id:'h-antonine',kind:'history',selected:true,day:'D3',time:'10:30',order:20,name:'Antonine Baths',city:'Carthage',category:'history',lat:36.8480,lng:10.3299,wiki:'Baths of Antoninus',relation:'Roman Africa and the imperial urban culture that followed Punic Carthage.',history:'The Roman layers of Carthage illustrate the city’s second life after Rome rebuilt on the ruins of its former rival.',description:'Large coastal ruins with strong visual impact and sea views.',source:'unesco-carthage'},
    {id:'h-punicports',kind:'history',selected:true,day:'D3',time:'11:45',order:30,name:'Punic Ports',city:'Carthage',category:'history',lat:36.8406,lng:10.3272,wiki:'Punic ports of Carthage',relation:'Carthaginian maritime trade, naval power and Mediterranean exchange.',history:'Carthage’s ports are part of the UNESCO archaeological property and symbolize the city’s long role in commercial and cultural exchange across the Mediterranean.',description:'Shorter visit; the story matters more than the surviving structures.',source:'unesco-carthage'},
    {id:'h-hammamet',kind:'history',selected:true,day:'D4',time:'09:30',order:10,name:'Hammamet Kasbah & Medina',city:'Hammamet',category:'history',lat:36.3997,lng:10.6145,wiki:'Hammamet, Tunisia',relation:'Ribat/coastal defence; Hafsid rule; later adaptation to gunpowder warfare.',history:'Tunisia’s heritage agency dates the original Hammamet fortress to 893. It was substantially enlarged under the Hafsids around 1463 and later adapted for firearms in the 16th–17th centuries.',description:'Walk the compact old town and ramparts before the shopping-and-coast afternoon.',source:'heritage-hammamet'},
    {id:'h-kairouan-mosque',kind:'history',selected:true,day:'D5',time:'09:30',order:20,name:'Great Mosque of Kairouan (جامع عقبة)',city:'Kairouan',category:'history',lat:35.68139,lng:10.10417,wiki:'Great Mosque of Kairouan',relation:'Uqba ibn Nafi; Arab-Muslim expansion into the Maghreb; Aghlabid architecture; model for Maghreban mosques.',history:'Kairouan was founded in 670 and flourished under the Aghlabids in the 9th century. UNESCO calls the Great Mosque a major masterpiece that influenced later Maghreban mosque design.',description:'One of the trip’s most important historical stops. Give it a proper guided visit.',source:'unesco-kairouan'},
    {id:'h-kairouan-basins',kind:'history',selected:true,day:'D5',time:'11:00',order:30,name:'Aghlabid Basins',city:'Kairouan',category:'history',lat:35.6787,lng:10.0955,wiki:'Aghlabid Basins',relation:'9th-century Aghlabid engineering and urban water management.',history:'UNESCO highlights the basins as an exceptional hydraulic ensemble created to supply Kairouan with water.',description:'A short stop that explains how an inland capital sustained itself.',source:'unesco-kairouan'},
    {id:'h-kairouan-medina',kind:'history',selected:true,day:'D5',time:'11:45',order:40,name:'Kairouan Medina',city:'Kairouan',category:'history',lat:35.6802,lng:10.1014,wiki:'Kairouan',relation:'Early Islamic Ifriqiya; spiritual importance in the Maghreb; courtyard-house urban form.',history:'UNESCO describes Kairouan as the most ancient Arabo-Muslim base in the Maghreb and a principal holy city. Its Medina preserves winding streets, walls and courtyard houses.',description:'Walk the lanes, then combine lunch with carpets and makroudh shopping.',source:'unesco-kairouan'},
    {id:'h-sousse-ribat',kind:'history',selected:true,day:'D5',time:'17:00',order:80,name:'Ribat + Medina of Sousse',city:'Sousse',category:'history',lat:35.8271,lng:10.6382,wiki:'Ribat of Sousse',relation:'Aghlabid coastal defence network; early Islamic military-religious architecture.',history:'Sousse was an important Aghlabid commercial and military port. UNESCO identifies its ribat, Great Mosque, kasbah and walls as an exceptional early Islamic coastal defence ensemble.',description:'Late-afternoon walk after check-in; keep the evening inside the Medina.',source:'unesco-sousse'},
    {id:'h-eljem',kind:'history',selected:true,day:'D6',time:'10:00',order:30,name:'Amphitheatre of El Jem',city:'El Jem',category:'history',lat:35.2964,lng:10.7069,wiki:'Amphitheatre of El Jem',relation:'Roman Africa; prosperous Thysdrus; imperial spectacle and architecture.',history:'Built in the 3rd century, the amphitheatre could hold about 35,000 spectators. UNESCO calls it the largest colosseum in North Africa and a major witness to Roman Africa’s prosperity.',description:'Walk the arena and underground passages before lunch and the drive north.',source:'unesco-eljem'},
    {id:'h-bardo',kind:'history',selected:true,day:'D7',time:'09:30',order:10,name:'Bardo National Museum',city:'Tunis',category:'history',lat:36.8092,lng:10.1349,wiki:'Bardo National Museum',relation:'Material history of Tunisia, especially Roman Africa and its mosaics.',history:'Use the Bardo as the final synthesis: it reconnects the Roman cities you have seen on the road with the art and material culture of ancient Tunisia.',description:'Two focused hours rather than a museum marathon.',source:'unesco-carthage'},

    {id:'l-rooftop',kind:'leisure',selected:true,day:'D1',time:'18:00',order:30,name:'Medina rooftop mint tea',city:'Tunis',category:'leisure',lat:36.7990,lng:10.1695,wiki:'Medina of Tunis',description:'Low-effort first-evening view over minarets and rooftops.',why:'Relax after the flight without wasting the evening.'},
    {id:'l-dinner-dar',kind:'leisure',selected:true,day:'D1',time:'20:00',order:40,name:'Dinner in a historic dar',city:'Tunis',category:'food',lat:36.8005,lng:10.1682,wiki:'Medina of Tunis',description:'A polished traditional Tunisian dinner in a restored historic setting.',why:'Your first serious introduction to Tunisian food.'},
    {id:'l-kmach',kind:'leisure',selected:true,day:'D2',time:'12:30',order:35,name:'Souk El Kmach — fabric shopping',city:'Tunis',category:'shopping',lat:36.7975,lng:10.1697,wiki:'Souk El Kmach',description:'Fabric market beside Zitouna. Look for Tunisian cloth, linen, silk blends and material for tailoring.',why:'Core stop for your mother’s clothing-focused spree.',source:'souk-kmach'},
    {id:'l-leffa',kind:'leisure',selected:true,day:'D2',time:'13:30',order:40,name:'Souk El Leffa — wool, clothing & local textiles',city:'Tunis',category:'shopping',lat:36.7979,lng:10.1689,wiki:'Souk El Leffa',description:'Historically associated with Djerbian wool traders; today it sells textiles, covers, clothes, shoes and crafts.',why:'Strong chance of finding regionally woven products and traditional pieces.',source:'souk-leffa'},
    {id:'l-chechia',kind:'leisure',selected:true,day:'D2',time:'14:30',order:50,name:'Souk Ech-Chaouachia — chechia makers',city:'Tunis',category:'shopping',lat:36.8010,lng:10.1690,wiki:'Souk Ech-Chaouachine',description:'Watch and buy Tunisia’s traditional felt chechia from the specialized makers’ quarter.',why:'A genuinely Tunisian wearable souvenir with a deep craft story.',source:'inp-tunis'},
    {id:'l-artounsi',kind:'leisure',selected:true,day:'D2',time:'15:30',order:60,name:'Locally made Tunisian clothing',city:'Tunis',category:'shopping',lat:36.8002,lng:10.1684,wiki:'Medina of Tunis',description:'Look for contemporary Tunisian-made jebbas, dresses, kachabiyas, farmlas and locally designed pieces around the Kasbah/Medina.',why:'Adds wearable modern-Tunisian pieces, not just souvenirs.',source:'artounsi'},
    {id:'l-la-goulette',kind:'leisure',selected:true,day:'D3',time:'13:00',order:40,name:'Seafood lunch in La Goulette',city:'La Goulette',category:'food',lat:36.8189,lng:10.3050,wiki:'La Goulette',description:'Seafood break between the archaeology and Sidi Bou Said.',why:'Keeps Day 3 energetic without making lunch another museum stop.'},
    {id:'l-sidi',kind:'leisure',selected:true,day:'D3',time:'15:30',order:50,name:'Sidi Bou Said lanes + bambalouni',city:'Sidi Bou Said',category:'leisure',lat:36.8704,lng:10.3418,wiki:'Sidi Bou Said',description:'Blue-and-white village walk, galleries, bambalouni and sea views.',why:'The visual, relaxed counterweight to Carthage.'},
    {id:'l-sidi-tea',kind:'leisure',selected:true,day:'D3',time:'18:00',order:60,name:'Sidi Bou Said sunset tea',city:'Sidi Bou Said',category:'food',lat:36.8711,lng:10.3440,wiki:'Sidi Bou Said',description:'Sit for sunset rather than continuing to climb the village.',why:'A mother-friendly pause before the drive to Hammamet.'},
    {id:'l-hammamet-beach',kind:'leisure',selected:true,day:'D4',time:'11:00',order:20,name:'Hammamet beach + café',city:'Hammamet',category:'leisure',lat:36.3986,lng:10.6122,wiki:'Hammamet, Tunisia',description:'Beachfront coffee and slow walk after the Kasbah.',why:'You are staying in Hammamet, so the coast deserves real time rather than a rushed day trip.'},
    {id:'l-nabeul-shop',kind:'leisure',selected:true,day:'D4',time:'13:00',order:30,name:'Nabeul souks + local fashion / leather',city:'Nabeul',category:'shopping',lat:36.4513,lng:10.7348,wiki:'Nabeul',description:'Shop town-centre boutiques and craft souks for locally produced ceramics, leather garments, shoes, jewellery and fashion.',why:'The official tourism guide specifically highlights fashion, leather garments and shoes in Nabeul.',source:'discover-nabeul'},
    {id:'l-hammamet-shop',kind:'leisure',selected:true,day:'D4',time:'16:30',order:40,name:'Hammamet Medina shopping',city:'Hammamet',category:'shopping',lat:36.4002,lng:10.6151,wiki:'Hammamet, Tunisia',description:'Look for fouta towels, kilims, carpets, leather, shoes, jewellery and Nabeul ceramics in Hammamet’s souks.',why:'Good second shopping wave without leaving your overnight city.',source:'discover-hammamet'},
    {id:'l-hammam',kind:'leisure',selected:true,day:'D4',time:'19:00',order:50,name:'Traditional hammam / spa',city:'Hammamet',category:'leisure',lat:36.4012,lng:10.6162,wiki:'Hammamet, Tunisia',description:'Book a comfortable hammam or spa session after a walking/shopping day.',why:'A deliberate recovery block before the Kairouan road day.'},
    {id:'l-kairouan-shop',kind:'leisure',selected:true,day:'D5',time:'13:00',order:50,name:'Kairouan carpets + makroudh',city:'Kairouan',category:'shopping',lat:35.6800,lng:10.1005,wiki:'Kairouan',description:'Shop for Kairouan carpets, then taste/buy makroudh before leaving the city.',why:'Turns the historical stop into a craft-and-food experience too.',source:'discover-kairouan'},
    {id:'l-sousse-souk',kind:'leisure',selected:true,day:'D5',time:'18:15',order:90,name:'Sousse Medina souks',city:'Sousse',category:'shopping',lat:35.8259,lng:10.6361,wiki:'Medina of Sousse',description:'Browse the souks after the Ribat for textiles, leather goods, baskets, blankets and other regional crafts.',why:'Another local-market stop while you are actually sleeping in the old city.',source:'discover-sousse'},
    {id:'l-sousse-dinner',kind:'leisure',selected:true,day:'D5',time:'20:00',order:100,name:'Sousse Medina dinner',city:'Sousse',category:'food',lat:35.8268,lng:10.6375,wiki:'Sousse',description:'Dinner inside or just outside the Medina before your one night in Sousse.',why:'No extra transfer after a long road day.'},
    {id:'l-sousse-morning',kind:'leisure',selected:true,day:'D6',time:'08:30',order:10,name:'Sousse café + short souk revisit',city:'Sousse',category:'leisure',lat:35.8272,lng:10.6374,wiki:'Medina of Sousse',description:'Short breakfast and last browse before checking out.',why:'Uses the overnight properly instead of treating Sousse as a drive-through.'},
    {id:'l-eljem-lunch',kind:'leisure',selected:true,day:'D6',time:'12:15',order:40,name:'El Jem lunch',city:'El Jem',category:'food',lat:35.2980,lng:10.7060,wiki:'El Jem',description:'Simple lunch near the amphitheatre before the long drive to Tunis.',why:'Breaks up a transport-heavy day.'},
    {id:'l-central-market',kind:'leisure',selected:true,day:'D7',time:'12:30',order:30,name:'Tunis Central Market',city:'Tunis',category:'shopping',lat:36.7967,lng:10.1800,wiki:'Tunis',description:'Food market for spices, olives, dates and edible gifts.',why:'Different from the clothing souqs and good for gifts.'},
    {id:'l-final-textiles',kind:'leisure',selected:true,day:'D7',time:'14:30',order:40,name:'Final clothing & textile sweep in the Medina',city:'Tunis',category:'shopping',lat:36.7978,lng:10.1692,wiki:'Souk El Leffa',description:'Return only to the best fabric/clothing shops discovered on Day 2 and make final purchases.',why:'Avoids buying everything before you know prices and quality.'},
    {id:'l-final-dinner',kind:'leisure',selected:true,day:'D7',time:'20:00',order:60,name:'Final Tunisian dinner',city:'Tunis',category:'food',lat:36.8005,lng:10.1682,wiki:'Medina of Tunis',description:'Your final celebratory dinner in a traditional setting.',why:'Keep the last night special but logistically easy.'},
    {id:'l-nabeul-friday',kind:'leisure',selected:false,day:'D8',time:'08:00',order:10,name:'OPTION: Nabeul Friday weekly market',city:'Nabeul',category:'shopping',lat:36.4510,lng:10.7350,wiki:'Nabeul',description:'Nabeul’s weekly market is Friday. Only add this if your return flight is late enough to allow a safe airport buffer.',why:'Best match for the “local market shopping spree” brief, but risky with an early/midday flight.',source:'discover-nabeul'}
  ],
  shopping:[
    {city:'Tunis Medina',icon:'🧵',priority:'#1 clothing stop',items:['Souk El Kmach for fabrics and textiles','Souk El Leffa for wool, clothing, shoes and regional woven goods','Souk Ech-Chaouachia for locally made chechia caps','Look for Tunisian-made jebbas, dresses, kachabiyas and contemporary artisan clothing'],tip:'Do the research pass first, then return on Day 7 for final buying. Ask where each item was made.'},
    {city:'Nabeul',icon:'👗',priority:'#2 fashion + crafts',items:['Local fashion and leather garments','Shoes and jewellery','Nabeul ceramics and tableware','Regular craft souks and town-centre shops'],tip:'The weekly Nabeul market is Friday; your Monday visit uses the everyday souks/shops. Add the Friday-market option only if the flight is late.'},
    {city:'Hammamet Medina',icon:'🛍️',priority:'Coastal shopping',items:['Fouta bath towels','Kilims and carpets','Leather and shoes','Jewellery and Nabeul ceramics'],tip:'Good for relaxed comparison shopping after the Kasbah and beach.'},
    {city:'Kairouan + Sousse',icon:'🧶',priority:'Regional crafts',items:['Kairouan carpets','Makroudh and food gifts','Sousse textiles, blankets and leather goods','Woven baskets and Medina crafts'],tip:'For expensive carpets, ask for material, knot/weave type, origin and a written receipt before paying.'}
  ]
};