window.TRIP_DATA={
 dayColors:{D1:'#3168b3',D2:'#c46a23',D3:'#0b8d81',D4:'#7a56c8',D5:'#a94442',D6:'#3d7b55',D7:'#b5782d',D8:'#656b75'},
 days:[
  {id:'D1',date:'Fri 18',title:'Arrive Tunis + settle into the dar',overnight:'tunisRiad'},
  {id:'D2',date:'Sat 19',title:'Tunis history + major local-clothing shopping',overnight:'tunisRiad'},
  {id:'D3',date:'Sun 20',title:'Carthage + Sidi Bou Said → Hammamet',overnight:'hammametBeach'},
  {id:'D4',date:'Mon 21',title:'Hammamet Medina + beach + Nabeul',overnight:'hammametBeach'},
  {id:'D5',date:'Tue 22',title:'Kairouan + Sousse road day',overnight:'hammametBeach'},
  {id:'D6',date:'Wed 23',title:'El Jem → Sidi Bou Said final base',overnight:'finalHybrid'},
  {id:'D7',date:'Thu 24',title:'Bardo + final Tunis shopping + farewell dinner',overnight:'finalHybrid'},
  {id:'D8',date:'Fri 25',title:'Airport + Riyadh',overnight:null}
 ],
 sources:[
  ['UNESCO — Medina of Tunis','https://whc.unesco.org/en/list/36'],['UNESCO — Carthage','https://whc.unesco.org/en/list/37'],['UNESCO — Kairouan','https://whc.unesco.org/en/list/499'],['UNESCO — Sousse','https://whc.unesco.org/en/list/498'],['UNESCO — El Jem','https://whc.unesco.org/en/list/38'],['Tunisia Heritage — Hammamet Citadel','https://www.patrimoinedetunisie.com.tn/en/monuments/the-citadel-borj-of-hammamet/overview/'],['National Heritage Institute — Tunis Medina','https://www.inp2020.tn/en/2020/01/28/medina-de-tunis/'],['Discover Tunisia — Nabeul & Cap Bon','https://www.discovertunisia.com/en/discover/nabeul-and-cap-bon'],['Discover Tunisia — Kairouan','https://www.discovertunisia.com/en/discover/around-kairouan'],['Discover Tunisia — Sousse','https://www.discovertunisia.com/en/discover/around-sousse-and-port-el-kantaoui'],['Bardo Museum','https://www.bardomuseum.tn/'],['Airbnb — private Tunisia stays','https://www.airbnb.com/']
 ],
 images:{
  tunis:['https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg','https://st.depositphotos.com/1001939/61112/i/450/depositphotos_611121066-stock-photo-tunis-tunisia-august-2022-people.jpg','https://i.dawn.com/primary/2019/12/5de65b11de6f4.jpg'],
  carthage:['https://cdn.getyourguide.com/image/format%3Dauto%2Cfit%3Dcrop%2Cgravity%3Dauto%2Cquality%3D60%2Cwidth%3D400%2Cheight%3D265%2Cdpr%3D2/tour_img/63a570d3ca8d7aeb786483e5abf5ba17600c8a6197bb457c168364cdc68391b7.jpg','https://deih43ym53wif.cloudfront.net/archaeological_site_carthage_baths_antoninus_tunis_shutterstock_1316626655_6e52175de9.jpg'],
  sidi:['https://www.tourmag.com/photo/art/grande/62892045-45466310.jpg?v=1646750665','https://images.mnstatic.com/2d/b5/2db56c81854e9140249438f7c7211b72.jpg?aspect_ratio=980%3A880&fit=crop&format=pjpg&height=880&quality=75&width=980'],
  hammamet:['https://img.ab-ins-blaue.de/img/cms/galleryx1/ec/67/a1/ec67a1371580ef80680365e311ae091f.jpg','https://www.tunrooms.com/images/rooms/12036/tiiukeuiyuwacekjeh0l.jpeg','https://ims.easyvoyage.info/medium_shutterstock_2548848233_b967a79f69/medium_shutterstock_2548848233_b967a79f69.jpg'],
  nabeul:['https://cdn.getyourguide.com/image/format%3Dauto%2Cfit%3Dcrop%2Cgravity%3Dauto%2Cquality%3D60%2Cwidth%3D400%2Cheight%3D265%2Cdpr%3D2/tour_img/3ea5119731aa08626dc7c08ba31828d17bc6913e4e1844360977ef8849e4f96c.jpg','https://primary.jwwb.nl/public/g/r/v/temp-sfkkytzaxczmlchggtef/dar-r-bat-057-high.jpg?enable-io=true&fit=crop&height=600&width=1200'],
  kairouan:['https://cdn.bookaway.com/media/files/6746124a64092e5955a0fb74.jpeg?quality=50&width=2000','https://static-cms.routard.com/web-routard/uploads/large_kairouan_tunisie_de7970fa2c.jpg','https://static-forums.routard.com/optimized/4X/1/7/8/1780c01eddf89b8892d3a0079f14278ac5d5eee7_2_666x500.jpeg'],
  sousse:['https://i0.wp.com/www.engagingcultures.com/wp-content/uploads/2019/09/The-Ribat-in-the-Sousse-Medina.jpg?resize=1000%2C667&ssl=1'],
  eljem:['https://www.christravelblog.com/wp-content/uploads/2020/01/outside-full-amphitheatre-tunisia-el-jem-day-trip-from-sousse-or-tunis-sfax-medina-tour-IMG_6334.jpg'],
  bardo:['https://blog.mailasail.com/ul/blog/mailasail.com/wanderingdragon%40mailasail.com/362/jpgjXYPgsDvy6.jpg']
 },
 staySegments:[
  {id:'tunisRiad',label:'Experience 1 · Tunis Medina',dates:'18–19 Sep · 2 nights',badge:'PRIVATE DAR EXPERIENCE',default:'dar24',options:[
   {id:'dar24',name:'Dar 24 · whole 18th-century Medina house',score:99,type:'Entire home',tag:'Top pick',hybrid:false,guests:'7 guests · 3 bedrooms · 3 baths',rating:'4.97 · 152 reviews',note:'The cleanest match to a Tunisian riad of your own: an entire renovated 18th-century house with patio, rooftop and three bedrooms.',lat:36.8016,lng:10.1688,url:'https://www.airbnb.com/rooms/13846170',images:['https://a0.muscache.com/im/pictures/058989a2-712a-429a-ba2a-f100a114f6b5.jpg?im_w=720','https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg']},
   {id:'typical-medina',name:'Typical Medina House · whole traditional home',score:97,type:'Entire home',tag:'Most traditional',hybrid:false,guests:'6 guests · 4 bedrooms · 3 baths',rating:'4.95 · 19 reviews',note:'Restored with antique tiles and period objects; stronger old-house character than a conventional guesthouse.',lat:36.7988,lng:10.1700,url:'https://www.airbnb.com/rooms/1000626548921981810',images:['https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg','https://tunisie.co/uploads/images/content/beit-dhiafa-071013-6.jpg']},
   {id:'dar-nabiha',name:'Dar Nabiha · Tourbet El Bey',score:96,type:'Entire home',tag:'Best size for 3',hybrid:false,guests:'4 guests · 2 bedrooms · 2 baths',rating:'4.96 · 46 reviews',note:'Historic whole house facing Tourbet El Bey, with patio and rooftop. Two bedrooms fit the three of you naturally.',lat:36.7941,lng:10.1702,url:'https://www.airbnb.com/rooms/786252231713372133',images:['https://tunisie.co/uploads/images/content/beit-dhiafa-071013-6.jpg','https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg']},
   {id:'dar-saida',name:'Dar Saïda · private Medina villa',score:94,type:'Entire townhouse',tag:'Best rooftop',hybrid:false,guests:'4 guests · 2 bedrooms · 2 baths',rating:'4.78 · 36 reviews',note:'Fully private traditional villa in the UNESCO Medina; a strong compromise between authenticity and independence.',lat:36.7980,lng:10.1695,url:'https://www.airbnb.com/rooms/1522323563808716231',images:['https://a0.muscache.com/im/pictures/hosting/Hosting-1522323563808716231/original/35849fad-1e9a-48f0-9250-30283987663e.jpeg','https://st.depositphotos.com/1001939/61112/i/450/depositphotos_611121066-stock-photo-tunis-tunisia-august-2022-people.jpg']},
   {id:'medina-condo',name:'Authentic Medina private condo',score:91,type:'Entire condo',tag:'Easiest private stay',hybrid:false,guests:'4 guests · 2 bedrooms · 1 bath',rating:'4.97 · 32 reviews',note:'Less palatial than a full dar, but exclusive use, two bedrooms and a traditional patio make it practical for your mother.',lat:36.7979,lng:10.1720,url:'https://www.airbnb.com/rooms/1498749589479453958',images:['https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg','https://i.dawn.com/primary/2019/12/5de65b11de6f4.jpg']}
  ]},
  {id:'hammametBeach',label:'Experience 2 · Hammamet',dates:'20–22 Sep · 3 nights',badge:'BEACH + DAR HYBRID',default:'dar-sandra',options:[
   {id:'dar-sandra',name:'Dar Sandra · traditional house 100 m from beach',score:100,type:'Entire home',tag:'Best of both',hybrid:true,guests:'6 guests · 2 bedrooms · 3.5 baths',rating:'4.86 · 42 reviews',note:'The best parallel experience: a private traditional Hammamet house with hammam and rooftop jacuzzi, roughly 100 m from the beach and close to the Medina.',lat:36.4050,lng:10.6080,url:'https://www.airbnb.com/rooms/5833417',images:['https://flashmode.tn/wp-content/uploads/2016/11/Dar-El-Bhar-Maison-dh%C3%B4tes-a-Hammamet-1024x681.jpg','https://www.tunrooms.com/images/rooms/12036/tiiukeuiyuwacekjeh0l.jpeg','https://img.ab-ins-blaue.de/img/cms/galleryx1/ec/67/a1/ec67a1371580ef80680365e311ae091f.jpg']},
   {id:'dar-el-nour',name:'Dar El Nour · authentic home steps from sea',score:99,type:'Entire home',tag:'Best for exactly 3',hybrid:true,guests:'4 guests · 2 bedrooms · 2 baths',rating:'5.0 · 7 reviews',note:'Private courtyard, carved doors, antique furniture and decorated ceilings, about 100 m from the sea.',lat:36.4130,lng:10.6300,url:'https://www.airbnb.com/rooms/1525311066959517055',images:['https://www.tunrooms.com/images/rooms/12036/jpsxrfi7edzdk8mpogyt.jpeg','https://www.tunrooms.com/images/rooms/12036/tiiukeuiyuwacekjeh0l.jpeg']},
   {id:'medina-pool-villa',name:'Medina villa · pool + sea view',score:98,type:'Entire villa',tag:'Hybrid + pool',hybrid:true,guests:'9 guests · 3 bedrooms · 2 baths',rating:'4.8',note:'Traditional dar renovated in Medina style, a few dozen meters from the sea, with a private pool and sea view.',lat:36.4003,lng:10.6146,url:'https://www.airbnb.com/rooms/3725112',images:['https://tunisie.co/uploads/images/content/1-011019.jpg','https://www.tunrooms.com/images/rooms/12036/tiiukeuiyuwacekjeh0l.jpeg']},
   {id:'feet-water',name:'Traditional Medina home · 80 m from beach',score:96,type:'Entire home',tag:'Walk everywhere',hybrid:true,guests:'5 guests · 2 bedrooms · 1 bath',rating:'5.0 · 5 reviews',note:'Arabesque-style private house in Hammamet Medina, roughly 80 m from beach, restaurants and market.',lat:36.3998,lng:10.6148,url:'https://www.airbnb.com/rooms/1666196726506983656',images:['https://www.tunrooms.com/images/rooms/12036/jpsxrfi7edzdk8mpogyt.jpeg','https://ims.easyvoyage.info/medium_shutterstock_2548848233_b967a79f69/medium_shutterstock_2548848233_b967a79f69.jpg']},
   {id:'perfect-beach',name:'Perfect Beach House · direct sea access + pool',score:94,type:'Entire villa',tag:'Pure beach luxury',hybrid:false,guests:'8 guests · 4 suites · 4.5 baths',rating:'New listing',note:'Best if beach matters most: direct garden-to-sand access, heated pool and rooftop jacuzzi.',lat:36.4380,lng:10.6850,url:'https://www.airbnb.com/rooms/1387187738394617333',images:['https://a0.muscache.com/im/pictures/prohost-api/Hosting-1387187738394617333/original/53f625bc-0c8b-4145-9132-e3fae2eea2eb.jpeg','https://img.ab-ins-blaue.de/img/cms/galleryx1/ec/67/a1/ec67a1371580ef80680365e311ae091f.jpg']},
   {id:'waterfront-villa',name:'Waterfront villa · garden + direct sea feel',score:92,type:'Entire villa',tag:'Large private villa',hybrid:false,guests:'12 guests · 5 bedrooms · 3 baths',rating:'4.83',note:'A larger private option if you want more room, garden and a stronger standalone beach-house feel.',lat:36.4320,lng:10.6750,url:'https://www.airbnb.com/rooms/23662274',images:['https://a0.muscache.com/im/pictures/hosting/Hosting-23662274/original/e1fb9c41-8310-4466-a12e-73e3827f1f2b.jpeg','https://www.tunrooms.com/images/rooms/12036/tiiukeuiyuwacekjeh0l.jpeg']},
   {id:'triplex-pool',name:'Beach triplex · private pool · 200 m beach',score:90,type:'Entire home',tag:'Best value beach home',hybrid:false,guests:'8 guests · 3 bedrooms · 3 baths',rating:'4.97 · 31 reviews',note:'Modern private option with pool and a short beach walk; less traditional, very easy as a family base.',lat:36.4200,lng:10.6500,url:'https://www.airbnb.com/rooms/1023026721428369661',images:['https://img.ab-ins-blaue.de/img/cms/galleryx1/ec/67/a1/ec67a1371580ef80680365e311ae091f.jpg','https://ims.easyvoyage.info/medium_shutterstock_2548848233_b967a79f69/medium_shutterstock_2548848233_b967a79f69.jpg']}
  ]},
  {id:'finalHybrid',label:'Finale · Sidi Bou Said / Tunis',dates:'23–24 Sep · 2 nights',badge:'SEA-VIEW TRADITIONAL HOME',default:'sidi-authentic',options:[
   {id:'sidi-authentic',name:'Authentic Sidi Bou Said house · sea-view rooftop',score:98,type:'Entire home',tag:'Top finale',hybrid:true,guests:'5 guests · 2 bedrooms · 2 baths',rating:'4.83',note:'A whole traditional-style home with sea-view rooftop in the blue-and-white village: cultural atmosphere and coastal feeling together.',lat:36.8698,lng:10.3414,url:'https://www.airbnb.com/rooms/893507389634553970',images:['https://www.tourmag.com/photo/art/grande/62892045-45466310.jpg?v=1646750665','https://images.mnstatic.com/2d/b5/2db56c81854e9140249438f7c7211b72.jpg?aspect_ratio=980%3A880&fit=crop&format=pjpg&height=880&quality=75&width=980']},
   {id:'sidi-etoile',name:'Maison l’Étoile · 360° sea-view private villa',score:96,type:'Entire villa',tag:'Best view',hybrid:true,guests:'2 bedrooms · private terraces',rating:'Newer listing',note:'Private Sidi Bou Said villa focused on panoramic sea views and outdoor terraces, while remaining in the village.',lat:36.8710,lng:10.3432,url:'https://www.airbnb.com/rooms/1452847756045816196',images:['https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTQ1Mjg0Nzc1NjA0NTgxNjE5Ng%3D%3D/original/be908191-e190-4a1e-827b-29c9e1271b1d.png','https://www.tourmag.com/photo/art/grande/62892045-45466310.jpg?v=1646750665']},
   {id:'sidi-charming',name:'Charming little Sidi Bou Said house',score:94,type:'Entire villa',tag:'Most intimate',hybrid:true,guests:'5 guests · 2 bedrooms · 1 bath',rating:'4.91 · 43 reviews',note:'Compact whole-house option with strong village character and easy access to cafés and viewpoints.',lat:36.8692,lng:10.3421,url:'https://www.airbnb.com/rooms/722922109419252805',images:['https://images.mnstatic.com/2d/b5/2db56c81854e9140249438f7c7211b72.jpg?aspect_ratio=980%3A880&fit=crop&format=pjpg&height=880&quality=75&width=980','https://www.tourmag.com/photo/art/grande/62892045-45466310.jpg?v=1646750665']},
   {id:'dar24-return',name:'Return to Dar 24 in Tunis Medina',score:90,type:'Entire home',tag:'Least luggage complexity',hybrid:false,guests:'7 guests · 3 bedrooms · 3 baths',rating:'4.97 · 152 reviews',note:'Choose this if your mother prefers fewer unknowns and you want one familiar Medina home for the final nights.',lat:36.8016,lng:10.1688,url:'https://www.airbnb.com/rooms/13846170',images:['https://a0.muscache.com/im/pictures/058989a2-712a-429a-ba2a-f100a114f6b5.jpg?im_w=720','https://a0.muscache.com/im/pictures/miso/Hosting-1273014287129551258/original/570536bc-4a8e-4917-859b-26bbd6170125.jpeg']}
  ]}
 ],
 fixed:[
  {id:'arrive',day:'D1',time:'12:00',order:1,name:'Tunis–Carthage Airport',category:'airport',lat:36.8510,lng:10.2272,description:'Land in Tunis, collect bags and meet the driver.'},
  {id:'to-hammamet',day:'D3',time:'19:00',order:90,name:'Drive Sidi Bou Said → Hammamet',category:'transfer',lat:36.4050,lng:10.6080,description:'Move south after sunset and check into the selected private beach home.'},
  {id:'to-kairouan',day:'D5',time:'07:30',order:1,name:'Hammamet → Kairouan',category:'transfer',lat:35.6810,lng:10.1020,description:'Private road-day start; keep the Hammamet house for the night so luggage can stay light.'},
  {id:'to-sousse',day:'D5',time:'15:00',order:70,name:'Kairouan → Sousse',category:'transfer',lat:35.8270,lng:10.6380,description:'Continue to Sousse for Ribat, Medina and dinner.'},
  {id:'back-hammamet',day:'D5',time:'19:30',order:97,name:'Sousse → Hammamet',category:'transfer',lat:36.4050,lng:10.6080,description:'Return to the same beach home for a third night — no hotel change.'},
  {id:'to-eljem',day:'D6',time:'08:15',order:1,name:'Hammamet → El Jem',category:'transfer',lat:35.2964,lng:10.7069,description:'Check out and drive south for the amphitheatre.'},
  {id:'north-final',day:'D6',time:'14:00',order:70,name:'El Jem → Sidi Bou Said / Tunis',category:'transfer',lat:36.8698,lng:10.3414,description:'Long northbound drive to the selected final two-night home.'},
  {id:'depart',day:'D8',time:'Flight',order:90,name:'Tunis–Carthage Airport',category:'airport',lat:36.8510,lng:10.2272,description:'Return flight to Riyadh. Confirm the actual Riyadh arrival date before paying.'}
 ],
 activities:[
  {id:'tunis-medina',kind:'history',recommended:true,selected:true,day:'D1',time:'16:00',order:20,name:'Medina of Tunis orientation',city:'Tunis',category:'history',lat:36.7986,lng:10.1710,relation:'Almohad and Hafsid Tunis; Ottoman/Husainid layers; classical Arabo-Muslim city form.',description:'Start with Bab Bhar and the old lanes so the house, souqs and monuments make sense tomorrow.',history:'Under the Almohads and Hafsids, Tunis became one of the major cities of the Islamic world. The UNESCO Medina contains palaces, mosques, madrasas, mausoleums and traditional houses.',source:'https://whc.unesco.org/en/list/36',img:'tunis'},
  {id:'zitouna',kind:'history',recommended:true,selected:true,day:'D2',time:'09:00',order:10,name:'Zitouna Mosque quarter',city:'Tunis',category:'history',lat:36.7976,lng:10.1705,relation:'Religious and scholarly life of medieval Tunis; specialized souqs grew around it.',description:'Go early, then flow directly into the textile and clothing souqs.',history:'Zitouna is one of the Medina’s key monuments and anchors the commercial streets around it.',source:'https://whc.unesco.org/en/list/36',img:'tunis'},
  {id:'dars-tourbet',kind:'history',recommended:true,selected:true,day:'D2',time:'10:30',order:20,name:'Historic dars + Tourbet El Bey',city:'Tunis',category:'history',lat:36.7940,lng:10.1702,relation:'Husainid elite houses and royal funerary culture.',description:'Connect the private dar you are sleeping in to the architecture and family history of old Tunis.',history:'Traditional Medina houses turn inward around courtyards for privacy, climate and family life; elite houses elaborate the pattern with richly decorated reception spaces.',source:'https://www.inp2020.tn/en/2020/01/28/medina-de-tunis/',img:'tunis'},
  {id:'carthage-byrsa',kind:'history',recommended:true,selected:true,day:'D3',time:'09:00',order:10,name:'Carthage · Byrsa Hill',city:'Carthage',category:'history',lat:36.8535,lng:10.3233,relation:'Phoenician/Punic Carthage; Hannibal; Punic Wars; Roman refoundation.',description:'Begin on the hill for the full Punic-to-Roman story and Gulf views.',history:'Carthage grew into a major Mediterranean power, was destroyed by Rome in 146 BCE, then rebuilt as a Roman city.',source:'https://whc.unesco.org/en/list/37',img:'carthage'},
  {id:'antonine',kind:'history',recommended:true,selected:true,day:'D3',time:'10:30',order:20,name:'Antonine Baths',city:'Carthage',category:'history',lat:36.8480,lng:10.3299,relation:'Roman Africa and imperial urban culture.',description:'The most visually dramatic Roman stop, directly beside the sea.',history:'The baths represent Carthage’s Roman phase and the scale of imperial public architecture in North Africa.',source:'https://whc.unesco.org/en/list/37',img:'carthage'},
  {id:'punic-ports',kind:'history',recommended:false,selected:false,day:'D3',time:'11:45',order:25,name:'Punic Ports',city:'Carthage',category:'history',lat:36.8406,lng:10.3272,relation:'Carthaginian maritime trade and naval power.',description:'Add if the group wants more Punic history after Byrsa.',history:'The harbors symbolize how Carthage built commercial and naval power across the Mediterranean.',source:'https://whc.unesco.org/en/list/37',img:'carthage'},
  {id:'sidi-palace',kind:'history',recommended:false,selected:false,day:'D3',time:'15:30',order:55,name:'Ennejma Ezzahra Palace',city:'Sidi Bou Said',category:'history',lat:36.8687,lng:10.3470,relation:'Baron d’Erlanger; Arab-Andalusian revival; Tunisian music heritage.',description:'Add if architecture and music history interest you before sunset.',history:'The palace is associated with Rodolphe d’Erlanger and the study and preservation of Arab music traditions.',source:'https://www.cmam.tn/',img:'sidi'},
  {id:'hammamet-kasbah',kind:'history',recommended:true,selected:true,day:'D4',time:'09:30',order:10,name:'Hammamet Kasbah + Medina',city:'Hammamet',category:'history',lat:36.3997,lng:10.6145,relation:'Coastal defence; Hafsid fortification; later gunpowder-era adaptation.',description:'Compact old-town history before the beach and Nabeul shopping.',history:'Hammamet’s fortifications evolved over centuries as the settlement guarded the Cap Bon coast.',source:'https://www.patrimoinedetunisie.com.tn/en/monuments/the-citadel-borj-of-hammamet/overview/',img:'hammamet'},
  {id:'kairouan-mosque',kind:'history',recommended:true,selected:true,day:'D5',time:'09:30',order:20,name:'Great Mosque of Kairouan · جامع عقبة',city:'Kairouan',category:'history',lat:35.68139,lng:10.10417,relation:'Uqba ibn Nafi; early Islamic expansion into the Maghreb; Aghlabids; model for Maghreban mosques.',description:'One of the trip’s most important historical stops; use a guide here.',history:'Kairouan was founded in 670. The Great Mosque’s present form is strongly associated with the Aghlabid 9th-century rebuilding and became highly influential in western Islamic architecture.',source:'https://whc.unesco.org/en/list/499',img:'kairouan'},
  {id:'aghlabid',kind:'history',recommended:true,selected:true,day:'D5',time:'11:00',order:30,name:'Aghlabid Basins',city:'Kairouan',category:'history',lat:35.6787,lng:10.0955,relation:'9th-century Aghlabid engineering and urban water management.',description:'Short but important infrastructure stop before the Medina.',history:'The reservoirs are among the clearest surviving examples of Aghlabid hydraulic engineering.',source:'https://whc.unesco.org/en/list/499',img:'kairouan'},
  {id:'kairouan-medina',kind:'history',recommended:true,selected:true,day:'D5',time:'11:45',order:40,name:'Kairouan Medina',city:'Kairouan',category:'history',lat:35.6802,lng:10.1014,relation:'Early Islamic Ifriqiya and a spiritual center of the Maghreb.',description:'Walk the old streets and traditional houses, then combine with carpets and makroudh.',history:'UNESCO recognizes Kairouan as one of the principal holy cities of the Maghreb with exceptional early Islamic urban heritage.',source:'https://whc.unesco.org/en/list/499',img:'kairouan'},
  {id:'sousse-ribat',kind:'history',recommended:true,selected:true,day:'D5',time:'16:00',order:80,name:'Ribat of Sousse + Medina',city:'Sousse',category:'history',lat:35.8264,lng:10.6385,relation:'Aghlabid coastal defence and fortified religious frontier architecture.',description:'Fast late-afternoon stop: Ribat, walls and a Medina walk before dinner.',history:'Sousse preserves a compact fortified urban ensemble where the Ribat and Medina illustrate early Islamic coastal defence.',source:'https://whc.unesco.org/en/list/498',img:'sousse'},
  {id:'eljem',kind:'history',recommended:true,selected:true,day:'D6',time:'10:30',order:20,name:'El Jem Amphitheatre',city:'El Jem',category:'history',lat:35.2964,lng:10.7069,relation:'Roman Africa; imperial spectacle; provincial wealth.',description:'Go inside the arena and upper levels; this is one of Tunisia’s visual highlights.',history:'The 3rd-century amphitheatre is among the largest Roman amphitheatres in the world and a sign of the prosperity of Roman Africa.',source:'https://whc.unesco.org/en/list/38',img:'eljem'},
  {id:'bardo',kind:'history',recommended:true,selected:true,day:'D7',time:'09:00',order:10,name:'Bardo National Museum',city:'Tunis',category:'history',lat:36.8092,lng:10.1349,relation:'Roman Africa mosaics and archaeological context for Carthage and Tunisia.',description:'Use the museum to connect the ruins you saw with art and daily life.',history:'The Bardo is especially known for Roman mosaics drawn from archaeological sites across Tunisia.',source:'https://www.bardomuseum.tn/',img:'bardo'},

  {id:'rooftop-tea',kind:'leisure',recommended:true,selected:true,day:'D1',time:'18:00',order:35,name:'Medina rooftop tea',city:'Tunis',category:'food',lat:36.7990,lng:10.1700,description:'Low-effort first-evening ritual above the old city.',img:'tunis'},
  {id:'tunis-shopping',kind:'leisure',recommended:true,selected:true,day:'D2',time:'12:00',order:35,name:'Mother’s Medina clothing spree',city:'Tunis',category:'shopping',lat:36.7980,lng:10.1698,description:'Prioritize Souk El Kmach fabrics, Souk El Leffa textiles, chechia makers and Tunisian-made garments. This is a real shopping block, not a quick stop.',img:'tunis'},
  {id:'dar-lunch',kind:'leisure',recommended:true,selected:true,day:'D2',time:'14:30',order:45,name:'Traditional dar lunch',city:'Tunis',category:'food',lat:36.7970,lng:10.1715,description:'Sit down properly after shopping for brik, couscous, ojja or seasonal Tunisian dishes.',img:'tunis'},
  {id:'lagoulette-lunch',kind:'leisure',recommended:true,selected:true,day:'D3',time:'13:00',order:40,name:'La Goulette seafood lunch',city:'La Goulette',category:'food',lat:36.8189,lng:10.3050,description:'Fresh fish and Tunisian coastal cooking between Carthage and Sidi Bou Said.',img:'sidi'},
  {id:'sidi-sunset',kind:'leisure',recommended:true,selected:true,day:'D3',time:'16:30',order:60,name:'Sidi Bou Said · tea + sunset',city:'Sidi Bou Said',category:'leisure',lat:36.8704,lng:10.3418,description:'Blue-and-white lanes, bambalouni, a sea-view café and sunset before driving to Hammamet.',img:'sidi'},
  {id:'sidi-gallery',kind:'leisure',recommended:false,selected:false,day:'D3',time:'17:15',order:65,name:'Sidi Bou Said gallery browsing',city:'Sidi Bou Said',category:'leisure',lat:36.8700,lng:10.3425,description:'Easy optional filler if the group still has energy before sunset.',img:'sidi'},
  {id:'hammamet-beach',kind:'leisure',recommended:true,selected:true,day:'D4',time:'11:00',order:25,name:'Hammamet beach time',city:'Hammamet',category:'leisure',lat:36.4060,lng:10.6120,description:'Keep a real 90-minute beach window rather than turning Hammamet into another sightseeing stop.',img:'hammamet'},
  {id:'nabeul-shopping',kind:'leisure',recommended:true,selected:true,day:'D4',time:'14:00',order:45,name:'Nabeul local market + clothing + crafts',city:'Nabeul',category:'shopping',lat:36.4513,lng:10.7355,description:'Second major shopping session: local garments, leather, shoes, embroidery and ceramics, with a focus on items made in Tunisia.',img:'nabeul'},
  {id:'nabeul-ceramics',kind:'leisure',recommended:false,selected:false,day:'D4',time:'15:30',order:55,name:'Nabeul ceramics workshop / pottery stop',city:'Nabeul',category:'shopping',lat:36.4518,lng:10.7370,description:'Add if ceramics matter as much as clothing; otherwise keep the shopping block broader.',img:'nabeul'},
  {id:'hammam',kind:'leisure',recommended:true,selected:true,day:'D4',time:'18:30',order:75,name:'Private hammam / spa',city:'Hammamet',category:'leisure',lat:36.4040,lng:10.6130,description:'Ideal recovery after walking and shopping. Dar Sandra itself includes hammam facilities.',img:'hammamet'},
  {id:'beach-dinner',kind:'leisure',recommended:false,selected:false,day:'D4',time:'20:30',order:90,name:'Private dinner at the beach house',city:'Hammamet',category:'food',lat:36.4100,lng:10.6200,description:'Use your private home properly: arrange groceries or a cook and eat at the house instead of going out.',img:'hammamet'},
  {id:'kairouan-carpets',kind:'leisure',recommended:true,selected:true,day:'D5',time:'12:30',order:55,name:'Kairouan carpets + makroudh',city:'Kairouan',category:'shopping',lat:35.6800,lng:10.1000,description:'See woven carpets and traditional sweets; buy only if provenance and price feel transparent.',img:'kairouan'},
  {id:'sousse-dinner',kind:'leisure',recommended:true,selected:true,day:'D5',time:'18:00',order:90,name:'Sousse Medina dinner',city:'Sousse',category:'food',lat:35.8272,lng:10.6380,description:'Early dinner inside or beside the Medina before returning to Hammamet.',img:'sousse'},
  {id:'eljem-lunch',kind:'leisure',recommended:true,selected:true,day:'D6',time:'12:30',order:45,name:'El Jem lunch + coffee',city:'El Jem',category:'food',lat:35.2960,lng:10.7050,description:'Rest after the amphitheatre before the long northbound drive.',img:'eljem'},
  {id:'final-shopping',kind:'leisure',recommended:true,selected:true,day:'D7',time:'13:00',order:35,name:'Final Tunis clothing / textile sweep',city:'Tunis',category:'shopping',lat:36.7983,lng:10.1703,description:'Return only to the shops worth revisiting; this is the buffer for anything your mother decided on after comparing quality.',img:'tunis'},
  {id:'cooking',kind:'leisure',recommended:false,selected:false,day:'D7',time:'16:00',order:55,name:'Private Tunisian cooking class',city:'Tunis',category:'leisure',lat:36.7975,lng:10.1710,description:'Optional hands-on family activity if you want less shopping on the final day.',img:'tunis'},
  {id:'farewell',kind:'leisure',recommended:true,selected:true,day:'D7',time:'20:00',order:80,name:'Farewell Tunisian dinner',city:'Sidi Bou Said / Tunis',category:'food',lat:36.8688,lng:10.3420,description:'Choose a traditional Tunisian dinner with a strong setting rather than another generic hotel restaurant.',img:'sidi'}
 ]
};