// Tunisia · 18–25 Sep 2026 · trip data
// One file, no patches. Text fields carry English (n/b) and Arabic (na/ba).
// Coordinates are approximate and are used for the map and Directions links only.
window.TRIP = (() => {
  const P = [];
  // add(cat, area, id, name, nameAr, blurb, blurbAr, [lat,lng], {slot, dur, price, tags, book, url})
  const add = (cat, area, id, n, na, b, ba, ll, x = {}) => P.push({ id, cat, area, n, na, b, ba, ll, slot: x.slot || 'midday', dur: x.dur || '1 h', price: x.price || '', tags: x.tags || [], book: x.book || null, url: x.url || null, q: x.q || null });

  /* ───────────── FOOD ───────────── */
  add('food', 'tunis', 'dar-el-jeld', 'Dar El Jeld', 'دار الجلد', 'Tunisian classics served in an 18th-century Medina house; the city’s best-known table. Reserve.', 'أطباق تونسية كلاسيكية في دار من القرن الثامن عشر داخل المدينة العتيقة؛ أشهر مطعم في العاصمة. يلزم الحجز.', [36.8000, 10.1690], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['reserve'], book: 'reserve', url: 'https://www.dareljeld.com/' });
  add('food', 'tunis', 'dar-slah', 'Dar Slah', 'دار صلاح', 'Honest traditional lunch near the souks: couscous, brik, seasonal fish. Small, so arrive early.', 'غداء تقليدي قرب الأسواق: كسكسي، بريك، سمك موسمي. المكان صغير فاحضروا مبكرًا.', [36.7970, 10.1705], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['reserve'], book: 'reserve' });
  add('food', 'tunis', 'fondouk-attarine', 'Fondouk El Attarine', 'فندق العطارين', 'Lunch in a restored caravanserai courtyard, steps from the perfume souk.', 'غداء في فناء فندق تجاري قديم مرمّم، على خطوات من سوق العطارين.', [36.7982, 10.1702], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['reserve'], book: 'reserve' });
  add('food', 'tunis', 'el-ali', 'El Ali', 'العلي', 'Café-restaurant on Rue Jamaa Zitouna with a rooftop over the Medina; good for a light lunch or mint tea.', 'مقهى ومطعم في نهج جامع الزيتونة بسطح يطل على المدينة العتيقة؛ مناسب لغداء خفيف أو شاي بالنعناع.', [36.7978, 10.1712], { slot: 'afternoon', dur: '1 h', price: '$$', tags: ['view', 'tea'] });
  add('food', 'tunis', 'cafe-mrabet', 'Café M’rabet', 'مقهى مرابط', 'Historic café in Souk Ettrouk; mats, columns and a terrace restaurant upstairs.', 'مقهى تاريخي في سوق الترك؛ حصائر وأعمدة ومطعم على السطح.', [36.7975, 10.1705], { slot: 'afternoon', dur: '45 min', price: '$', tags: ['tea'] });
  add('food', 'tunis', 'essaraya', 'Essaraya', 'السرايا', 'Palace-restaurant with painted ceilings and a courtyard; refined Tunisian dinner.', 'مطعم في قصر بسقوف مزخرفة وفناء داخلي؛ عشاء تونسي راقٍ.', [36.7980, 10.1690], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['reserve'], book: 'reserve' });
  add('food', 'tunis', 'chez-slah', 'Chez Slah', 'شي صلاح', 'Downtown institution for seafood and French-Tunisian cooking since the 1950s.', 'مطعم عريق وسط المدينة للمأكولات البحرية والمطبخ الفرنسي التونسي منذ الخمسينيات.', [36.8010, 10.1850], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['reserve'], book: 'reserve' });
  add('food', 'tunis', 'marche-central', 'Marché Central', 'السوق المركزي', 'Covered market for fish, olives, harissa and spices; eat a bowl of lablabi at a stall nearby.', 'سوق مسقوف للسمك والزيتون والهريسة والتوابل؛ جرّبوا صحن لبلابي في الجوار.', [36.7995, 10.1800], { slot: 'morning', dur: '1 h', price: '$', tags: ['easy'] });
  add('food', 'tunis', 'street-food', 'Street food: brik, fricassé, lablabi', 'أكل الشارع: بريك، فريكاسي، لبلابي', 'The three things to try at least once: crisp brik with egg, a fricassé sandwich, and lablabi chickpea soup.', 'ثلاثة أشياء يجب تجربتها: بريك مقرمش بالبيض، ساندويتش فريكاسي، وشوربة اللبلابي بالحمص.', [36.7990, 10.1760], { slot: 'midday', dur: '30 min', price: '$', tags: ['easy'] });
  add('food', 'coast', 'cafe-vert', 'Le Café Vert · La Goulette', 'الكافي فير · حلق الوادي', 'La Goulette’s classic fish restaurant: grilled catch, complet poisson, a table on the avenue.', 'مطعم السمك الكلاسيكي في حلق الوادي: سمك مشوي و«كومبلي بواسون» وطاولة على الشارع.', [36.8175, 10.3060], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea'] });
  add('food', 'coast', 'bon-vieux-temps', 'Au Bon Vieux Temps', 'أو بون فيو تان', 'Sidi Bou Said’s old-school restaurant with a terrace over the Gulf; book a window table for sunset.', 'مطعم سيدي بوسعيد العريق بشرفة تطل على الخليج؛ احجزوا طاولة قرب النافذة للغروب.', [36.8705, 10.3425], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['view', 'reserve', 'sunset'], book: 'reserve' });
  add('food', 'coast', 'dar-zarrouk', 'Dar Zarrouk', 'دار زروق', 'Garden terrace above the marina; Tunisian and Mediterranean dishes with the best view in the village.', 'شرفة حديقة فوق المرسى؛ أطباق تونسية ومتوسطية مع أجمل إطلالة في القرية.', [36.8712, 10.3430], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['view', 'reserve'], book: 'reserve' });
  add('food', 'coast', 'cafe-nattes', 'Café des Nattes', 'مقهى النطاطة', 'The postcard café at the top of the main street; mint tea with pine nuts on the mats.', 'المقهى الأشهر في أعلى الشارع الرئيسي؛ شاي بالنعناع والصنوبر على الحصائر.', [36.8703, 10.3418], { slot: 'afternoon', dur: '45 min', price: '$', tags: ['tea'] });
  add('food', 'coast', 'sidi-chabaane', 'Café Sidi Chabaane', 'مقهى سيدي شبعان', 'Terraces stepping down the cliff over the sea; tea, bambalouni and sunset.', 'شرفات متدرجة على الجرف فوق البحر؛ شاي وبمبالوني وغروب.', [36.8720, 10.3440], { slot: 'evening', dur: '1 h', price: '$', tags: ['view', 'sunset', 'tea'] });
  add('food', 'coast', 'bambalouni', 'Bambalouni stand', 'بمبالوني', 'Hot sugared doughnuts fried to order at the foot of Sidi Bou Said’s main street. Cash.', 'عجينة مقلية ساخنة مع السكر عند بداية الشارع الرئيسي لسيدي بوسعيد. نقدًا.', [36.8698, 10.3410], { slot: 'afternoon', dur: '15 min', price: '$', tags: ['easy'] });
  add('food', 'coast', 'le-golfe', 'Le Golfe · La Marsa', 'لوقولف · المرسى', 'Seafood on the La Marsa corniche; flat walk, easy parking, a calmer alternative to Sidi Bou Said.', 'مأكولات بحرية على كورنيش المرسى؛ ممشى مستوٍ ومواقف سهلة وبديل أهدأ من سيدي بوسعيد.', [36.8800, 10.3280], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['sea', 'easy', 'reserve'], book: 'reserve' });
  add('food', 'coast', 'le-pirate', 'Le Pirate · Gammarth', 'لوبيرات · قمرت', 'Fish straight from the Gammarth port next door; simple, outdoors, very popular on weekends.', 'سمك من ميناء قمرت المجاور؛ بسيط وفي الهواء الطلق ومزدحم في العطل.', [36.9200, 10.2960], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea', 'reserve'], book: 'reserve' });
  add('food', 'kairouan', 'makroudh', 'Makroudh from a Kairouan pâtisserie', 'مقروض القيروان', 'The city’s date-filled semolina pastry, best warm from a shop near the Great Mosque. Buy a box for the road.', 'حلوى المدينة من السميد والتمر، ألذ ما تكون دافئة من محل قرب الجامع الكبير. اشتروا علبة للطريق.', [35.6775, 10.1005], { slot: 'afternoon', dur: '20 min', price: '$', tags: ['easy'] });
  add('food', 'kairouan', 'dar-koraich', 'Dar Koraich', 'دار قريش', 'Traditional house with a rooftop café and home-style Kairouan cooking; call ahead for lunch.', 'دار تقليدية بمقهى على السطح وطبخ قيرواني بيتي؛ اتصلوا مسبقًا للغداء.', [35.6780, 10.1005], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['reserve'], book: 'reserve', url: 'https://darkoraich.com/' });
  add('food', 'kairouan', 'la-kasbah-lunch', 'Hotel La Kasbah restaurant', 'مطعم فندق القصبة', 'The easy full-service option in Kairouan: parking, air-conditioning, a set menu.', 'الخيار السهل بخدمة كاملة في القيروان: مواقف وتكييف وقائمة ثابتة.', [35.6800, 10.1020], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['easy'] });
  add('food', 'sousse', 'le-lido', 'Le Lido · Sousse port', 'لو ليدو · ميناء سوسة', 'Long-running fish restaurant by the harbour; a short walk from the Medina walls.', 'مطعم سمك قديم عند المرفأ؛ على مسافة قصيرة من أسوار المدينة العتيقة.', [35.8300, 10.6410], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea', 'reserve'], book: 'reserve' });
  add('food', 'sousse', 'dar-antonia-dinner', 'Dar Antonia', 'دار أنطونيا', 'Design-led guesthouse restaurant inside the Medina; the nicest dinner in old Sousse. Reserve.', 'مطعم دار ضيافة أنيقة داخل المدينة العتيقة؛ ألطف عشاء في سوسة القديمة. يلزم الحجز.', [35.8268, 10.6378], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['reserve'], book: 'reserve', url: 'https://darantonia.com/' });
  add('food', 'sousse', 'medina-couscous', 'Couscous in the Sousse Medina', 'كسكسي في مدينة سوسة العتيقة', 'Pick a busy family place inside the walls for lamb or fish couscous; cheap, quick, local.', 'اختاروا مطعمًا عائليًا مزدحمًا داخل الأسوار لكسكسي اللحم أو السمك؛ رخيص وسريع ومحلي.', [35.8260, 10.6375], { slot: 'midday', dur: '1 h', price: '$', tags: ['easy'] });
  add('food', 'sousse', 'kantaoui-marina-lunch', 'Port El Kantaoui marina restaurants', 'مطاعم مرسى القنطاوي', 'A row of terraces on the marina; sea views, easy parking, relaxed resort atmosphere.', 'صف من الشرفات على المرسى؛ إطلالة بحرية ومواقف سهلة وأجواء استجمام.', [35.8920, 10.5960], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea', 'easy'] });
  add('food', 'monastir', 'mahdia-port-grills', 'Mahdia harbour seafood', 'مأكولات بحرية في ميناء المهدية', 'Grilled fish where the boats come in; Mahdia is the best seafood town on this coast.', 'سمك مشوي حيث ترسو القوارب؛ المهدية أفضل مدينة للمأكولات البحرية على هذا الساحل.', [35.5075, 11.0700], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea'] });
  add('food', 'monastir', 'monastir-marina-lunch', 'Monastir marina lunch', 'غداء في مرسى المنستير', 'Cafés and fish restaurants beside the yachts, a five-minute walk from the Ribat.', 'مقاهٍ ومطاعم سمك بجانب اليخوت، على خمس دقائق سيرًا من الرباط.', [35.7740, 10.8380], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['sea', 'easy'] });
  add('food', 'eljem', 'eljem-lunch', 'Lunch facing the amphitheatre', 'غداء مقابل المسرح', 'Simple grills and salads across from the arena; rest before the drive north.', 'مشاوي وسلطات بسيطة مقابل المسرح؛ استريحوا قبل الطريق شمالًا.', [35.2960, 10.7050], { slot: 'midday', dur: '1 h', price: '$', tags: ['easy'] });
  add('food', 'hammamet', 'barberousse', 'Le Barberousse', 'لو باربروس', 'On the Medina ramparts over the sea; Hammamet’s signature dinner. Book a terrace table.', 'على أسوار المدينة العتيقة فوق البحر؛ عشاء الحمامات المميز. احجزوا طاولة في الشرفة.', [36.3948, 10.6135], { slot: 'evening', dur: '2 h', price: '$$$', tags: ['view', 'sea', 'reserve'], book: 'reserve' });
  add('food', 'hammamet', 'chez-achour', 'Chez Achour', 'شي عاشور', 'Family seafood restaurant a few streets from the Medina; big grilled platters, no fuss.', 'مطعم عائلي للمأكولات البحرية على بعد شوارع من المدينة العتيقة؛ أطباق مشوية كبيرة بلا تكلّف.', [36.3985, 10.6100], { slot: 'midday', dur: '1.5 h', price: '$$', tags: ['reserve'], book: 'reserve' });
  add('food', 'hammamet', 'sidi-bou-hdid', 'Café Sidi Bou Hdid', 'مقهى سيدي بوحديد', 'Tea and shisha on cushions against the sea wall below the Kasbah. No alcohol, all atmosphere.', 'شاي وشيشة على الوسائد عند سور البحر أسفل القصبة. بلا كحول وبأجواء كاملة.', [36.3940, 10.6130], { slot: 'evening', dur: '1 h', price: '$', tags: ['sea', 'tea', 'sunset'] });
  add('food', 'hammamet', 'villa-dinner', 'Dinner at the house', 'عشاء في البيت', 'Use the private stay: groceries from Monoprix or a cook arranged through the host; no driving after dark.', 'استفيدوا من البيت الخاص: مشتريات من مونوبري أو طبّاخ عبر المضيف؛ لا قيادة بعد الغروب.', [36.4050, 10.6150], { slot: 'evening', dur: '2 h', price: '$', tags: ['easy'] });
  add('food', 'hammamet', 'yasmine-marina-dinner', 'Yasmine Hammamet marina', 'مرسى ياسمين الحمامات', 'A dozen restaurants around the marina; the easy choice when nobody wants to decide.', 'عشرات المطاعم حول المرسى؛ الخيار السهل عندما لا يريد أحد أن يقرر.', [36.3710, 10.5370], { slot: 'evening', dur: '2 h', price: '$$', tags: ['sea', 'easy'] });
  add('food', 'nabeul', 'nabeul-lunch', 'Nabeul market lunch', 'غداء في سوق نابل', 'Rotisserie chicken, salads and harissa near the market; Nabeul is the harissa capital.', 'دجاج مشوي وسلطات وهريسة قرب السوق؛ نابل عاصمة الهريسة.', [36.4540, 10.7350], { slot: 'midday', dur: '1 h', price: '$', tags: ['easy'] });

  /* ───────────── SIGHTS ───────────── */
  add('sights', 'tunis', 'medina-walk', 'Medina of Tunis', 'مدينة تونس العتيقة', 'UNESCO old city: enter at Bab Bhar, follow Rue Jamaa Zitouna to the mosque, then lose yourselves in the souks.', 'المدينة العتيقة (يونسكو): ادخلوا من باب البحر واتبعوا نهج جامع الزيتونة إلى الجامع ثم توهوا في الأسواق.', [36.7985, 10.1740], { slot: 'midday', dur: '2–3 h', price: '', tags: ['unesco'], url: 'https://whc.unesco.org/en/list/36' });
  add('sights', 'tunis', 'zitouna', 'Zitouna Mosque', 'جامع الزيتونة', 'The great mosque of Tunis, founded in the 8th century; courtyard and prayer hall, columns from Carthage.', 'الجامع الكبير في تونس، أُسّس في القرن الثامن؛ صحن وبيت صلاة وأعمدة من قرطاج.', [36.7972, 10.1710], { slot: 'morning', dur: '45 min', price: '', tags: ['easy'] });
  add('sights', 'tunis', 'tourbet-el-bey', 'Tourbet El Bey', 'تربة الباي', 'Mausoleum of the Husainid beys: marble, tiles and painted domes in the southern Medina.', 'ضريح البايات الحسينيين: رخام وخزف وقباب مزخرفة في جنوب المدينة العتيقة.', [36.7940, 10.1700], { slot: 'morning', dur: '30 min', price: '$', tags: ['tickets'] });
  add('sights', 'tunis', 'dar-ben-abdallah', 'Dar Ben Abdallah', 'دار بن عبد الله', 'Museum of traditional life inside an 18th-century palace; the best way to understand the house you sleep in.', 'متحف الحياة التقليدية داخل قصر من القرن الثامن عشر؛ أفضل طريقة لفهم الدار التي تنامون فيها.', [36.7945, 10.1715], { slot: 'morning', dur: '45 min', price: '$', tags: ['museum', 'tickets'] });
  add('sights', 'tunis', 'dar-lasram', 'Dar Lasram', 'دار الأصرم', 'Restored palace housing the Medina conservation association; often quiet, often free to peek in.', 'قصر مرمّم تشغله جمعية صيانة المدينة؛ هادئ غالبًا ويمكن إلقاء نظرة مجانًا.', [36.7995, 10.1690], { slot: 'morning', dur: '30 min', price: '', tags: ['free'] });
  add('sights', 'tunis', 'bardo', 'Bardo National Museum', 'المتحف الوطني بباردو', 'The world’s finest Roman mosaic collection in a beylical palace; two hours minimum. Closed Mondays.', 'أعظم مجموعة فسيفساء رومانية في العالم داخل قصر بايليكي؛ ساعتان على الأقل. مغلق يوم الاثنين.', [36.8093, 10.1348], { slot: 'morning', dur: '2–3 h', price: '$$', tags: ['museum', 'tickets', 'closedMon'], book: 'tickets', url: 'https://www.bardomuseum.tn/' });
  add('sights', 'tunis', 'bourguiba-avenue', 'Avenue Habib Bourguiba', 'شارع الحبيب بورقيبة', 'The ficus-lined main avenue: cathedral, Théâtre Municipal, the clock tower and café terraces.', 'الشارع الرئيسي المظلل بأشجار الفيكوس: الكاتدرائية والمسرح البلدي وساعة الميدان والمقاهي.', [36.8000, 10.1830], { slot: 'afternoon', dur: '1 h', price: '', tags: ['easy', 'free'] });
  add('sights', 'coast', 'byrsa', 'Carthage · Byrsa Hill', 'قرطاج · هضبة بيرصا', 'The heart of Punic Carthage with the Gulf below; Punic quarter and the old cathedral on top.', 'قلب قرطاج البونية والخليج من تحتها؛ الحي البوني والكاتدرائية القديمة في الأعلى.', [36.8530, 10.3233], { slot: 'morning', dur: '1 h', price: '$', tags: ['unesco', 'view', 'tickets'], book: 'tickets', url: 'https://whc.unesco.org/en/list/37' });
  add('sights', 'coast', 'antonine-baths', 'Antonine Baths', 'حمامات أنطونيوس', 'Vast Roman baths right on the shore; the most photogenic stop in Carthage.', 'حمامات رومانية ضخمة على الشاطئ مباشرة؛ أجمل محطة للتصوير في قرطاج.', [36.8583, 10.3325], { slot: 'morning', dur: '1 h', price: '$', tags: ['unesco', 'sea', 'tickets'], book: 'tickets' });
  add('sights', 'coast', 'punic-ports', 'Punic Ports & Tophet', 'الموانئ البونية والتوفة', 'The circular naval harbour and the Tophet sanctuary; quiet, atmospheric, ten minutes from the baths.', 'الميناء الحربي الدائري ومعبد التوفة؛ هادئ ومؤثر وعلى عشر دقائق من الحمامات.', [36.8410, 10.3240], { slot: 'midday', dur: '45 min', price: '$', tags: ['unesco'] });
  add('sights', 'coast', 'roman-villas', 'Roman villas & theatre', 'الفيلات الرومانية والمسرح', 'Mosaic floors, the Villa of the Aviary and the restored theatre on the slope of Odeon hill.', 'أرضيات فسيفساء وفيلا الطيور والمسرح المرمّم على سفح هضبة الأوديون.', [36.8555, 10.3265], { slot: 'midday', dur: '45 min', price: '$', tags: ['unesco'] });
  add('sights', 'coast', 'sidi-bou-said', 'Sidi Bou Said village', 'قرية سيدي بوسعيد', 'Blue doors, white walls, bougainvillea and sea views. Go late afternoon when the tour buses leave.', 'أبواب زرقاء وجدران بيضاء وجهنمية وإطلالات بحرية. اذهبوا آخر العصر بعد رحيل الحافلات السياحية.', [36.8700, 10.3415], { slot: 'afternoon', dur: '2 h', price: '', tags: ['view', 'sunset', 'free'] });
  add('sights', 'coast', 'dar-el-annabi', 'Dar El Annabi', 'دار العنابي', 'A private 18th-century family house in Sidi Bou Said opened as a museum; rooftop over the whole bay.', 'بيت عائلي خاص من القرن الثامن عشر في سيدي بوسعيد صار متحفًا؛ سطح يطل على الخليج كله.', [36.8700, 10.3420], { slot: 'afternoon', dur: '30 min', price: '$', tags: ['view', 'tickets'] });
  add('sights', 'coast', 'ennejma-ezzahra', 'Ennejma Ezzahra', 'قصر النجمة الزهراء', 'Baron d’Erlanger’s palace of Arab-Andalusian revival; gardens, music museum, silence.', 'قصر البارون دارلانجي بطراز أندلسي عربي؛ حدائق ومتحف موسيقى وهدوء.', [36.8688, 10.3470], { slot: 'afternoon', dur: '1 h', price: '$', tags: ['museum', 'tickets'], url: 'https://www.cmam.tn/' });
  add('sights', 'coast', 'la-marsa-corniche', 'La Marsa corniche', 'كورنيش المرسى', 'Flat seaside promenade with cafés; the easiest evening walk near Tunis.', 'ممشى بحري مستوٍ مع مقاهٍ؛ أسهل نزهة مسائية قرب تونس.', [36.8785, 10.3250], { slot: 'evening', dur: '1 h', price: '', tags: ['sea', 'easy', 'free'] });
  add('sights', 'road', 'dougga', 'Dougga (day trip)', 'دقة (رحلة يوم)', 'The best-preserved Roman town in North Africa, on a hillside 1 h 45 from Tunis. A full alternative to the Carthage day.', 'أفضل مدينة رومانية محفوظة في شمال إفريقيا على سفح تلّ، على بعد ساعة و45 دقيقة من تونس. بديل كامل ليوم قرطاج.', [36.4230, 9.2200], { slot: 'morning', dur: 'Full day', price: '$', tags: ['unesco', 'view', 'tickets'], url: 'https://whc.unesco.org/en/list/794' });
  add('sights', 'road', 'zaghouan-temple', 'Zaghouan Water Temple', 'معبد المياه بزغوان', 'Roman nymphaeum at the spring that fed Carthage’s aqueduct; 20 minutes off the Tunis–Kairouan road.', 'معبد المياه الروماني عند النبع الذي غذّى قناة قرطاج؛ على 20 دقيقة من طريق تونس–القيروان.', [36.3980, 10.1420], { slot: 'morning', dur: '45 min', price: '$', tags: ['view'] });
  add('sights', 'road', 'takrouna', 'Takrouna', 'تكرونة', 'Tiny Berber village on a rock above the plain, between Sousse and Hammamet; a 30-minute detour with a big view.', 'قرية أمازيغية صغيرة على صخرة فوق السهل بين سوسة والحمامات؛ انعطافة 30 دقيقة بإطلالة كبيرة.', [36.1560, 10.3970], { slot: 'afternoon', dur: '45 min', price: '', tags: ['view', 'free'] });
  add('sights', 'kairouan', 'great-mosque', 'Great Mosque of Kairouan', 'جامع عقبة بن نافع', 'Founded 670 by Uqba ibn Nafi; the Aghlabid courtyard and forest of columns are the trip’s single most important stop. Hire a guide at the gate.', 'أسّسه عقبة بن نافع سنة 670؛ الصحن الأغلبي وغابة الأعمدة أهم محطة في الرحلة كلها. استعينوا بمرشد عند الباب.', [35.6814, 10.1042], { slot: 'morning', dur: '1.5 h', price: '$', tags: ['unesco', 'tickets'], book: 'tickets', url: 'https://whc.unesco.org/en/list/499' });
  add('sights', 'kairouan', 'barber-mosque', 'Mosque of the Barber (Sidi Sahib)', 'مقام أبي زمعة البلوي (سيدي الصحبي)', 'Zaouia of a companion of the Prophet; the most beautiful tilework and stucco in Kairouan.', 'زاوية صحابي رسول الله؛ أجمل خزف وجبس في القيروان.', [35.6840, 10.0975], { slot: 'morning', dur: '45 min', price: '$', tags: ['unesco'] });
  add('sights', 'kairouan', 'aghlabid-basins', 'Aghlabid Basins', 'فسقيات الأغالبة', 'Ninth-century reservoirs that kept the desert city alive; ten minutes, best from the viewing terrace.', 'خزّانات من القرن التاسع أبقت مدينة الصحراء حية؛ عشر دقائق، والأفضل من شرفة المشاهدة.', [35.6790, 10.0960], { slot: 'morning', dur: '20 min', price: '$', tags: ['unesco', 'easy'] });
  add('sights', 'kairouan', 'kairouan-medina', 'Kairouan Medina & ramparts', 'مدينة القيروان العتيقة وأسوارها', 'Walk from Bab Ech Chouhada through the souks to the Great Mosque; carpets, wool, copper and quiet lanes.', 'امشوا من باب الشهداء عبر الأسواق إلى الجامع الكبير؛ سجاد وصوف ونحاس وأزقة هادئة.', [35.6780, 10.1000], { slot: 'midday', dur: '1.5 h', price: '', tags: ['unesco', 'free'] });
  add('sights', 'kairouan', 'bir-barrouta', 'Bir Barrouta', 'بئر بروطة', 'Upstairs well turned by a blindfolded camel; legend links it to Zamzam. Five minutes, memorable.', 'بئر في الطابق العلوي يديره جمل معصوب العينين؛ تربطه الأسطورة بزمزم. خمس دقائق لا تُنسى.', [35.6772, 10.1000], { slot: 'midday', dur: '15 min', price: '$', tags: ['easy'] });
  add('sights', 'kairouan', 'three-doors', 'Mosque of the Three Doors', 'مسجد الأبواب الثلاثة', 'Ninth-century façade with carved Kufic inscriptions; a two-minute stop on the way through the Medina.', 'واجهة من القرن التاسع بنقوش كوفية محفورة؛ وقفة دقيقتين في طريقكم عبر المدينة.', [35.6760, 10.1010], { slot: 'midday', dur: '10 min', price: '', tags: ['free', 'easy'] });
  add('sights', 'kairouan', 'raqqada', 'Raqqada Museum of Islamic Art', 'متحف رقادة للفنون الإسلامية', 'Quiet national museum 9 km south with Aghlabid ceramics and the Kairouan Qur’an pages on blue parchment.', 'متحف وطني هادئ على بعد 9 كم جنوبًا يضم خزفًا أغلبيًا وصفحات المصحف القيرواني على الرقّ الأزرق.', [35.6200, 10.0800], { slot: 'afternoon', dur: '1 h', price: '$', tags: ['museum', 'tickets'] });
  add('sights', 'sousse', 'sousse-ribat', 'Ribat of Sousse', 'رباط سوسة', 'Climb the watchtower for the Medina, the Great Mosque and the sea in one frame.', 'اصعدوا برج المراقبة لتروا المدينة العتيقة والجامع الكبير والبحر في إطار واحد.', [35.8270, 10.6385], { slot: 'morning', dur: '1 h', price: '$', tags: ['unesco', 'view', 'tickets'], book: 'tickets', url: 'https://whc.unesco.org/en/list/498' });
  add('sights', 'sousse', 'sousse-mosque', 'Great Mosque of Sousse', 'جامع سوسة الكبير', 'Fortress-like Aghlabid mosque without a minaret, just across from the Ribat.', 'جامع أغلبي يشبه القلعة بلا مئذنة، مقابل الرباط مباشرة.', [35.8265, 10.6395], { slot: 'morning', dur: '30 min', price: '$', tags: ['unesco', 'easy'] });
  add('sights', 'sousse', 'sousse-museum', 'Sousse Archaeological Museum (Kasbah)', 'متحف سوسة الأثري (القصبة)', 'Second only to the Bardo for mosaics, in the Kasbah at the top of the Medina.', 'الثاني بعد باردو في الفسيفساء، داخل القصبة أعلى المدينة العتيقة.', [35.8235, 10.6350], { slot: 'midday', dur: '1 h', price: '$', tags: ['museum', 'tickets'], book: 'tickets' });
  add('sights', 'sousse', 'sousse-medina', 'Sousse Medina walls & souks', 'أسوار مدينة سوسة وأسواقها', 'Compact walled town: Souk er-Ribba, the Kalaout el-Koubba dome, the ramparts at sunset.', 'مدينة مسوّرة صغيرة: سوق الربع وقبة القبّة والأسوار عند الغروب.', [35.8260, 10.6375], { slot: 'afternoon', dur: '1.5 h', price: '', tags: ['unesco', 'free'] });
  add('sights', 'sousse', 'catacombs', 'Catacombs of Sousse', 'سراديب سوسة', 'Early Christian catacombs on the edge of town; a short section is open. Cool on a hot afternoon.', 'سراديب مسيحية مبكرة على أطراف المدينة؛ جزء قصير مفتوح. بارد في عصر حار.', [35.8180, 10.6200], { slot: 'afternoon', dur: '30 min', price: '$', tags: ['tickets'] });
  add('sights', 'monastir', 'monastir-ribat', 'Ribat of Monastir', 'رباط المنستير', 'The grandest ribat on the coast; climb the nador tower for the sea and the mausoleum. 25 min from Sousse.', 'أعظم رباط على الساحل؛ اصعدوا برج النادور لرؤية البحر والضريح. 25 دقيقة من سوسة.', [35.7765, 10.8340], { slot: 'afternoon', dur: '1 h', price: '$', tags: ['view', 'sea', 'tickets'], book: 'tickets' });
  add('sights', 'monastir', 'bourguiba-mausoleum', 'Bourguiba Mausoleum', 'ضريح بورقيبة', 'Gilded domes and marble avenue of the republic’s founder; five minutes from the Ribat.', 'قباب مذهّبة ورواق رخامي لمؤسس الجمهورية؛ خمس دقائق من الرباط.', [35.7785, 10.8300], { slot: 'afternoon', dur: '30 min', price: '', tags: ['free', 'easy'] });
  add('sights', 'monastir', 'skifa-kahla', 'Mahdia · Skifa el Kahla & Medina', 'المهدية · السقيفة الكحلة والمدينة', 'Fatimid gate, silk weavers’ Medina and the old harbour on a narrow peninsula. 1 h from Sousse.', 'باب فاطمي ومدينة حائكي الحرير والميناء القديم على شبه جزيرة ضيقة. ساعة من سوسة.', [35.5045, 11.0625], { slot: 'morning', dur: '2 h', price: '', tags: ['sea', 'free'] });
  add('sights', 'monastir', 'borj-el-kebir', 'Mahdia · Borj el Kebir & Cape Africa', 'المهدية · البرج الكبير ورأس إفريقيا', 'Ottoman fort, lighthouse and the whitewashed marine cemetery at the tip of the peninsula.', 'حصن عثماني ومنارة والمقبرة البحرية البيضاء عند طرف شبه الجزيرة.', [35.5040, 11.0690], { slot: 'midday', dur: '1 h', price: '$', tags: ['view', 'sea'] });
  add('sights', 'eljem', 'eljem-amphitheatre', 'El Jem Amphitheatre', 'مسرح الجم', 'Third-century arena for 35,000, better preserved than the Colosseum. Walk the arena floor, the galleries and the top tier.', 'مسرح من القرن الثالث يتسع لـ35 ألفًا، محفوظ أفضل من الكولوسيوم. امشوا في الحلبة والأروقة والطابق الأعلى.', [35.2964, 10.7069], { slot: 'morning', dur: '1.5 h', price: '$', tags: ['unesco', 'tickets'], book: 'tickets', url: 'https://whc.unesco.org/en/list/38' });
  add('sights', 'eljem', 'eljem-museum', 'El Jem Archaeological Museum', 'متحف الجم الأثري', 'Mosaics from Roman Thysdrus and a reconstructed villa; same ticket as the amphitheatre, 10 min walk.', 'فسيفساء من تيسدروس الرومانية وفيلا معاد بناؤها؛ بنفس تذكرة المسرح، 10 دقائق سيرًا.', [35.2920, 10.7040], { slot: 'midday', dur: '45 min', price: '', tags: ['museum'] });
  add('sights', 'hammamet', 'hammamet-kasbah', 'Hammamet Kasbah', 'قصبة الحمامات', 'Small fort at the corner of the Medina; ramparts walk with the beach on both sides.', 'حصن صغير في زاوية المدينة العتيقة؛ ممشى على الأسوار والشاطئ على الجانبين.', [36.3946, 10.6120], { slot: 'afternoon', dur: '45 min', price: '$', tags: ['view', 'sea', 'tickets'] });
  add('sights', 'hammamet', 'hammamet-medina', 'Hammamet Medina', 'مدينة الحمامات العتيقة', 'Whitewashed lanes, blue shutters, the Great Mosque and Sidi Bou Hdid’s tomb; twenty minutes end to end.', 'أزقة بيضاء ونوافذ زرقاء والجامع الكبير وضريح سيدي بوحديد؛ عشرون دقيقة من طرف إلى طرف.', [36.3950, 10.6135], { slot: 'afternoon', dur: '1 h', price: '', tags: ['free', 'easy'] });
  add('sights', 'hammamet', 'dar-sebastian', 'Dar Sebastian · International Cultural Centre', 'دار سيباستيان · المركز الثقافي الدولي', 'The 1920s villa and gardens that made Hammamet fashionable; Frank Lloyd Wright called it the most beautiful house he knew.', 'الفيلا والحدائق التي جعلت الحمامات وجهة راقية في العشرينيات؛ وصفها فرانك لويد رايت بأجمل بيت عرفه.', [36.3925, 10.6015], { slot: 'morning', dur: '1 h', price: '$', tags: ['tickets'] });
  add('sights', 'nabeul', 'nabeul-museum', 'Nabeul Archaeological Museum & Neapolis', 'متحف نابل الأثري ونيابوليس', 'Punic and Roman Nabeul: the Nymphs mosaics in the museum, the Neapolis ruins by the beach.', 'نابل البونية والرومانية: فسيفساء الحوريات في المتحف وأطلال نيابوليس عند الشاطئ.', [36.4550, 10.7370], { slot: 'morning', dur: '1 h', price: '$', tags: ['museum', 'tickets'] });
  add('sights', 'nabeul', 'kerkouane', 'Kerkouane (Cap Bon day trip)', 'كركوان (رحلة رأس الطيب)', 'The only Punic town never rebuilt by Rome; floors, baths and sea. 1 h 15 from Hammamet via Kelibia.', 'المدينة البونية الوحيدة التي لم تُعد روما بناءها؛ أرضيات وحمامات وبحر. ساعة و15 دقيقة من الحمامات عبر قليبية.', [36.9460, 11.0990], { slot: 'morning', dur: 'Half day', price: '$', tags: ['unesco', 'sea', 'tickets'], url: 'https://whc.unesco.org/en/list/332' });
  add('sights', 'nabeul', 'kelibia-fort', 'Kelibia fort', 'قلعة قليبية', 'Byzantine-Ottoman fortress on a rock over the harbour; the finest view on Cap Bon.', 'حصن بيزنطي عثماني على صخرة فوق الميناء؛ أجمل إطلالة في رأس الطيب.', [36.8380, 11.1160], { slot: 'midday', dur: '45 min', price: '$', tags: ['view', 'sea'] });

  /* ───────────── SHOPPING ───────────── */
  add('shopping', 'tunis', 'souk-attarine', 'Souk El Attarine', 'سوق العطارين', 'Perfume oils, orange-blossom and rose water, jasmine, henna; beside the Zitouna.', 'زيوت عطرية وماء الزهر وماء الورد وياسمين وحناء؛ بجانب الزيتونة.', [36.7978, 10.1703], { slot: 'midday', dur: '45 min', price: '$$', tags: ['easy'] });
  add('shopping', 'tunis', 'souk-kmach', 'Souk El Kmach & Souk El Leffa', 'سوق القماش وسوق اللفة', 'Fabrics, embroidered kaftans, jebbas, wool blankets; the place for clothing and tailoring contacts.', 'أقمشة وقفاطين مطرزة وجبب وبطانيات صوف؛ المكان للملابس وعناوين الخياطين.', [36.7973, 10.1707], { slot: 'midday', dur: '1.5 h', price: '$$', tags: [] });
  add('shopping', 'tunis', 'souk-chaouachine', 'Souk Ech-Chaouachine', 'سوق الشواشين', 'The chechia makers: watch the red felt caps being blocked and brushed, then buy one.', 'صنّاع الشاشية: شاهدوا القبعات الحمراء تُقولب وتُمشّط ثم اشتروا واحدة.', [36.7985, 10.1700], { slot: 'midday', dur: '30 min', price: '$', tags: ['easy'] });
  add('shopping', 'tunis', 'souk-berka', 'Souk El Berka', 'سوق البركة', 'Gold and silver jewellery under the painted arcade; bargain, and ask for the hallmark.', 'مجوهرات ذهب وفضة تحت الرواق المزخرف؛ فاصلوا واسألوا عن الدمغة.', [36.7975, 10.1700], { slot: 'midday', dur: '30 min', price: '$$$', tags: [] });
  add('shopping', 'tunis', 'onat', 'ONAT crafts showroom (fixed prices)', 'معرض الديوان الوطني للصناعات التقليدية (أسعار ثابتة)', 'State handicraft showroom downtown: carpets, ceramics, brass, olive wood at marked prices; good for calibrating what the souks charge.', 'معرض الصناعات التقليدية الحكومي وسط المدينة: سجاد وخزف ونحاس وخشب زيتون بأسعار محددة؛ مفيد لمعرفة أسعار الأسواق.', [36.7985, 10.1830], { slot: 'afternoon', dur: '45 min', price: '$$', tags: ['easy'], q: 'ONAT Office National de l\'Artisanat Tunis' });
  add('shopping', 'tunis', 'tunisia-mall', 'Tunisia Mall · Lac 2', 'تونيزيا مول · البحيرة 2', 'Modern mall near the airport for anything forgotten; pharmacies, a Monoprix and international brands.', 'مول حديث قرب المطار لأي شيء نسيتموه؛ صيدليات ومونوبري وعلامات عالمية.', [36.8425, 10.2660], { slot: 'afternoon', dur: '1 h', price: '$$', tags: ['easy'] });
  add('shopping', 'coast', 'sidi-artisans', 'Sidi Bou Said artisan shops', 'محلات الحرفيين في سيدي بوسعيد', 'Birdcages, ceramics, silver and small galleries along Rue Habib Thameur; fixed-ish prices, easy browsing.', 'أقفاص طيور وخزف وفضة ومعارض صغيرة على طول شارع الحبيب ثامر؛ أسعار شبه ثابتة وتصفح سهل.', [36.8700, 10.3420], { slot: 'afternoon', dur: '1 h', price: '$$', tags: ['easy'] });
  add('shopping', 'coast', 'zephyr', 'Zephyr · La Marsa', 'زفير · المرسى', 'Small seaside mall with Tunisian designers and cafés; a calm, air-conditioned shopping hour.', 'مول صغير على البحر بمصممين تونسيين ومقاهٍ؛ ساعة تسوق هادئة ومكيفة.', [36.8790, 10.3240], { slot: 'afternoon', dur: '1 h', price: '$$', tags: ['easy'] });
  add('shopping', 'kairouan', 'kairouan-carpets', 'Kairouan carpets', 'سجاد القيروان', 'The city’s knotted carpets and margoum kilims; visit two or three showrooms before deciding, and get a certificate.', 'سجاد القيروان المعقود والمرقوم؛ زوروا معرضين أو ثلاثة قبل القرار واطلبوا شهادة.', [35.6790, 10.1030], { slot: 'afternoon', dur: '1 h', price: '$$$', tags: [] });
  add('shopping', 'kairouan', 'kairouan-souks', 'Kairouan souks: copper, leather, wool', 'أسواق القيروان: نحاس وجلد وصوف', 'Cheaper and calmer than Tunis; copper trays, babouches, wool burnous.', 'أرخص وأهدأ من تونس؛ صواني نحاس وبلغة وبرنس صوف.', [35.6780, 10.1010], { slot: 'afternoon', dur: '45 min', price: '$', tags: ['easy'] });
  add('shopping', 'sousse', 'soula-center', 'Soula Center', 'مركز سولة', 'Multi-storey fixed-price souvenir store at the Medina gate; no bargaining, everything under one roof.', 'متجر هدايا متعدد الطوابق بأسعار ثابتة عند باب المدينة؛ بلا مفاصلة وكل شيء تحت سقف واحد.', [35.8280, 10.6395], { slot: 'afternoon', dur: '45 min', price: '$$', tags: ['easy'] });
  add('shopping', 'sousse', 'sousse-souks', 'Sousse Medina souks', 'أسواق مدينة سوسة', 'Embroidered dresses, leather slippers, olive wood; compare with the Soula Center before buying.', 'فساتين مطرزة وأحذية جلدية وخشب زيتون؛ قارنوا مع مركز سولة قبل الشراء.', [35.8262, 10.6380], { slot: 'afternoon', dur: '1 h', price: '$', tags: [] });
  add('shopping', 'sousse', 'mall-of-sousse', 'Mall of Sousse', 'مول سوسة', 'Large modern mall on the Tunis road; Carrefour, pharmacies, cinema.', 'مول حديث كبير على طريق تونس؛ كارفور وصيدليات وسينما.', [35.8590, 10.5960], { slot: 'afternoon', dur: '1 h', price: '$$', tags: ['easy'] });
  add('shopping', 'nabeul', 'nabeul-pottery', 'Nabeul pottery workshops', 'ورش الفخار في نابل', 'Buy ceramics from the workshops on Avenue Habib Thameur, not the resort shops; watch pieces being glazed.', 'اشتروا الخزف من الورش في شارع الحبيب ثامر لا من محلات المنتجعات؛ شاهدوا التزجيج.', [36.4560, 10.7380], { slot: 'morning', dur: '1 h', price: '$$', tags: [] });
  add('shopping', 'nabeul', 'nabeul-souk', 'Nabeul souk & harissa', 'سوق نابل والهريسة', 'Everyday market town: spices, harissa, orange-blossom water, embroidery. The big market is Fridays.', 'مدينة سوق يومية: توابل وهريسة وماء زهر وتطريز. السوق الكبير يوم الجمعة.', [36.4540, 10.7350], { slot: 'morning', dur: '1 h', price: '$', tags: ['easy'] });
  add('shopping', 'nabeul', 'nabeul-friday-market', 'Nabeul Friday market', 'سوق الجمعة في نابل', 'Sprawling weekly market (Fridays only): clothes, crafts, produce; go before 11.', 'سوق أسبوعي واسع (الجمعة فقط): ملابس وحرف ومنتجات؛ اذهبوا قبل 11.', [36.4540, 10.7350], { slot: 'morning', dur: '1.5 h', price: '$', tags: ['friday'] });
  add('shopping', 'nabeul', 'dar-chaabane', 'Dar Chaabane stone carving', 'نحت الحجر في دار شعبان', 'Village of stone carvers just north of Nabeul; fountains, lintels, small pieces to carry.', 'قرية نحّاتي الحجر شمال نابل مباشرة؛ نوافير وعتبات وقطع صغيرة تُحمل.', [36.4700, 10.7550], { slot: 'morning', dur: '30 min', price: '$$', tags: [] });
  add('shopping', 'hammamet', 'hammamet-souk', 'Hammamet Medina souk', 'سوق مدينة الحمامات', 'Compact tourist souk inside the walls; leather, kaftans, spices. Bargain hard.', 'سوق سياحي صغير داخل الأسوار؛ جلد وقفاطين وتوابل. فاصلوا بقوة.', [36.3952, 10.6130], { slot: 'afternoon', dur: '45 min', price: '$', tags: ['easy'] });
  add('shopping', 'hammamet', 'medina-mediterranea', 'Yasmine Hammamet · Medina Mediterranea', 'ياسمين الحمامات · المدينة المتوسطية', 'Purpose-built “medina” with boutiques, cafés and evening shows; polished and easy, not authentic.', '«مدينة» مبنية حديثًا بمحلات ومقاهٍ وعروض مسائية؛ أنيقة وسهلة لكنها ليست أصيلة.', [36.3700, 10.5390], { slot: 'evening', dur: '1 h', price: '$$', tags: ['easy'] });

  /* ───────────── NIGHTLIFE ───────────── */
  add('nightlife', 'tunis', 'bar-jamaica', 'Bar Jamaïca · El Hana International', 'بار جامايكا · فندق الهناء', 'Tenth-floor hotel bar on Avenue Bourguiba with the city at your feet; a pre-dinner drink classic.', 'بار في الطابق العاشر على شارع بورقيبة والمدينة تحت أقدامكم؛ كلاسيكي لمشروب قبل العشاء.', [36.8005, 10.1840], { slot: 'night', dur: '1 h', price: '$$', tags: ['view', 'alcohol'] });
  add('nightlife', 'tunis', 'boeuf-sur-le-toit', 'Le Bœuf sur le Toit', 'لوبوف سور لوتوا', 'Tunis’s old-guard bar-restaurant in Mutuelleville; live music, late kitchen.', 'بار ومطعم عريق في المتوعلية؛ موسيقى حية ومطبخ يعمل حتى وقت متأخر.', [36.8200, 10.1750], { slot: 'night', dur: '2 h', price: '$$', tags: ['alcohol', 'reserve'], book: 'reserve' });
  add('nightlife', 'coast', 'villa-didon', 'Villa Didon · Carthage', 'فيلا ديدون · قرطاج', 'Boutique hotel bar on Byrsa Hill; cocktails over the ruins and the Gulf at dusk.', 'بار فندق بوتيك على هضبة بيرصا؛ كوكتيلات فوق الأطلال والخليج عند الغسق.', [36.8535, 10.3225], { slot: 'night', dur: '1.5 h', price: '$$$', tags: ['view', 'sunset', 'alcohol'] });
  add('nightlife', 'coast', 'plaza-corniche', 'Plaza Corniche · La Marsa', 'بلازا كورنيش · المرسى', 'Hotel garden bar and club that fills up after midnight; the La Marsa scene.', 'بار حديقة وملهى في فندق يمتلئ بعد منتصف الليل؛ مشهد المرسى.', [36.8815, 10.3245], { slot: 'night', dur: '2 h', price: '$$$', tags: ['alcohol'] });
  add('nightlife', 'coast', 'carpe-diem', 'Le Carpe Diem · Gammarth', 'كارب ديام · قمرت', 'Restaurant-lounge on the Gammarth hill road; dinner that turns into drinks and music.', 'مطعم ولاونج على طريق تلة قمرت؛ عشاء يتحول إلى مشروبات وموسيقى.', [36.9080, 10.3080], { slot: 'night', dur: '2 h', price: '$$$', tags: ['alcohol', 'reserve'], book: 'reserve' });
  add('nightlife', 'coast', 'gammarth-hotel-bars', 'Gammarth hotel bars', 'بارات فنادق قمرت', 'The Residence, Mövenpick and neighbours have terrace bars open to non-guests; quiet, sea-facing, late.', 'ذا ريزيدنس وموفنبيك وجيرانهما لديهم بارات على الشرفات مفتوحة لغير النزلاء؛ هادئة ومطلة على البحر وحتى وقت متأخر.', [36.9200, 10.2905], { slot: 'night', dur: '1.5 h', price: '$$$', tags: ['sea', 'alcohol'], q: 'The Residence Tunis Gammarth' });
  add('nightlife', 'coast', 'sidi-bou-said-evening', 'Sidi Bou Said after dark', 'سيدي بوسعيد بعد الغروب', 'Wine on the Dar Zarrouk or Bon Vieux Temps terraces, then tea at Sidi Chabaane; the calmest night out on the coast.', 'نبيذ على شرفة دار زروق أو بون فيو تان ثم شاي في سيدي شبعان؛ أهدأ سهرة على الساحل.', [36.8708, 10.3428], { slot: 'night', dur: '2 h', price: '$$', tags: ['view', 'alcohol', 'tea'] });
  add('nightlife', 'kairouan', 'kairouan-evening', 'Kairouan evening: tea on the ramparts', 'مساء القيروان: شاي على الأسوار', 'Kairouan is a holy city with essentially no bars. Evenings mean tea, makroudh and a walk along the lit walls.', 'القيروان مدينة مقدسة بلا بارات تقريبًا. المساء يعني شاي ومقروض ونزهة على الأسوار المضاءة.', [35.6780, 10.1000], { slot: 'night', dur: '1 h', price: '$', tags: ['tea', 'noAlcohol', 'easy'] });
  add('nightlife', 'sousse', 'bora-bora', 'Bora Bora beach club · Sousse', 'بورا بورا بيتش كلوب · سوسة', 'Loungers by day, DJs and cocktails by night on the Boujaffar shore.', 'أسرّة شمس نهارًا ودي جي وكوكتيلات ليلًا على شاطئ بوجعفر.', [35.8450, 10.6300], { slot: 'night', dur: '2 h', price: '$$', tags: ['beach', 'alcohol'] });
  add('nightlife', 'sousse', 'saloon', 'Saloon · Sousse', 'صالون · سوسة', 'Wild-west themed club that has outlived every trend in town; live bands, dancing, late.', 'ملهى بطابع الغرب الأمريكي عاش أطول من كل الموضات في المدينة؛ فرق حية ورقص حتى وقت متأخر.', [35.8560, 10.6180], { slot: 'night', dur: '2 h', price: '$$', tags: ['alcohol'] });
  add('nightlife', 'sousse', 'kantaoui-night', 'Port El Kantaoui by night', 'مرسى القنطاوي ليلًا', 'Marina terraces, shisha lounges and a couple of bars; safe, easy, everything walkable.', 'شرفات المرسى ولاونجات شيشة وبعض البارات؛ آمن وسهل وكل شيء قريب سيرًا.', [35.8920, 10.5960], { slot: 'night', dur: '1.5 h', price: '$$', tags: ['sea', 'easy', 'alcohol'] });
  add('nightlife', 'sousse', 'boujaffar-promenade', 'Boujaffar promenade evening', 'سهرة على كورنيش بوجعفر', 'Ice cream, cafés and the whole town out walking on Sousse’s seafront; no alcohol needed.', 'آيس كريم ومقاهٍ والمدينة كلها تتنزه على شاطئ سوسة؛ بلا حاجة للكحول.', [35.8330, 10.6400], { slot: 'night', dur: '1 h', price: '$', tags: ['sea', 'easy', 'noAlcohol'] });
  add('nightlife', 'hammamet', 'manhattan', 'Manhattan Club · Hammamet', 'مانهاتن كلوب · الحمامات', 'The big Hammamet nightclub since the 1990s; open-air dance floors, opens around midnight.', 'ملهى الحمامات الكبير منذ التسعينيات؛ حلبات رقص مكشوفة، يفتح نحو منتصف الليل.', [36.3780, 10.5600], { slot: 'night', dur: '3 h', price: '$$$', tags: ['alcohol'] });
  add('nightlife', 'hammamet', 'calypso', 'Calypso · Hammamet', 'كاليبسو · الحمامات', 'Hammamet’s other institution: pool-side club with international DJs in season.', 'المؤسسة الأخرى في الحمامات: ملهى بجانب المسبح مع دي جي عالميين في الموسم.', [36.3800, 10.5650], { slot: 'night', dur: '3 h', price: '$$$', tags: ['alcohol'] });
  add('nightlife', 'hammamet', 'yasmine-night', 'Yasmine Hammamet marina bars', 'بارات مرسى ياسمين الحمامات', 'Cocktail terraces and hotel bars around the marina; the relaxed, walkable option.', 'شرفات كوكتيل وبارات فنادق حول المرسى؛ الخيار المريح القريب سيرًا.', [36.3715, 10.5375], { slot: 'night', dur: '2 h', price: '$$', tags: ['sea', 'easy', 'alcohol'] });
  add('nightlife', 'hammamet', 'sidi-bou-hdid-night', 'Sidi Bou Hdid at night', 'سيدي بوحديد ليلًا', 'Tea, shisha and the sound of the sea under the Kasbah walls; the Medina evening for the whole family.', 'شاي وشيشة وصوت البحر تحت أسوار القصبة؛ سهرة المدينة العتيقة للعائلة كلها.', [36.3940, 10.6130], { slot: 'night', dur: '1.5 h', price: '$', tags: ['sea', 'tea', 'noAlcohol'] });
  add('nightlife', 'tunis', 'what-to-drink', 'What to drink in Tunisia', 'ماذا تشربون في تونس', 'Celtia is the beer; Magon and Vieux Magon the wines; Boukha (fig spirit) and Thibarine (date liqueur) the digestifs. Alcohol is sold in licensed hotels, bars and larger supermarkets, not in the Medina.', 'سلتيا هي البيرة؛ ماقون وفيو ماقون النبيذ؛ البوخة (من التين) والثيبارين (من التمر) بعد الطعام. يُباع الكحول في الفنادق والبارات المرخصة والمتاجر الكبرى لا في المدينة العتيقة.', null, { slot: 'night', dur: '', price: '', tags: ['alcohol'] });

  /* ───────────── RELAX ───────────── */
  add('relax', 'hammamet', 'hammamet-beach', 'Hammamet beach', 'شاطئ الحمامات', 'Long sandy bay from the Medina north; the section in front of the Medina is the prettiest, Hammamet Nord the calmest.', 'خليج رملي طويل من المدينة العتيقة شمالًا؛ الجزء أمام المدينة الأجمل والحمامات الشمالية الأهدأ.', [36.4000, 10.6200], { slot: 'morning', dur: '2 h', price: '', tags: ['beach', 'free'] });
  add('relax', 'hammamet', 'bio-azur', 'Bio Azur Thalasso', 'بيو أزور تالاسو', 'Independent thalassotherapy centre in Hammamet Nord; half-day packages, book a day ahead.', 'مركز علاج بمياه البحر مستقل في الحمامات الشمالية؛ باقات نصف يوم، احجزوا قبل يوم.', [36.4110, 10.6290], { slot: 'afternoon', dur: '3 h', price: '$$$', tags: ['spa', 'reserve'], book: 'reserve' });
  add('relax', 'hammamet', 'hasdrubal-thalassa', 'Hasdrubal Thalassa · Yasmine', 'حصدربعل تالاسا · ياسمين', 'One of the country’s best spas; day passes for non-guests on request.', 'من أفضل المنتجعات الصحية في البلاد؛ تذاكر يومية لغير النزلاء عند الطلب.', [36.3660, 10.5350], { slot: 'afternoon', dur: '3 h', price: '$$$', tags: ['spa', 'reserve'], book: 'reserve', url: 'https://www.hasdrubal-thalassa.com/' });
  add('relax', 'hammamet', 'yasmine-boat', 'Boat trip from Yasmine marina', 'رحلة بحرية من مرسى ياسمين', 'Two-hour coastal cruises with a swim stop; check the sea state and shade on the boat.', 'رحلات ساحلية لساعتين مع توقف للسباحة؛ تحققوا من حالة البحر والظل على المركب.', [36.3710, 10.5370], { slot: 'afternoon', dur: '2 h', price: '$$', tags: ['sea', 'reserve'], book: 'reserve' });
  add('relax', 'hammamet', 'carthage-land', 'Carthage Land', 'كارثيج لاند', 'Theme park and water park at Yasmine Hammamet; only if the group wants a silly afternoon.', 'مدينة ملاهٍ وألعاب مائية في ياسمين الحمامات؛ فقط إذا أراد الجميع عصرًا مرحًا.', [36.3720, 10.5400], { slot: 'afternoon', dur: '3 h', price: '$$', tags: ['tickets'] });
  add('relax', 'hammamet', 'citrus-golf', 'Citrus Golf Hammamet', 'نادي سيتروس للغولف', 'Two 18-hole courses among orange groves; green fees on request.', 'ملعبان من 18 حفرة بين بساتين البرتقال؛ رسوم اللعب عند الطلب.', [36.4200, 10.5800], { slot: 'morning', dur: '4 h', price: '$$$', tags: ['reserve'], book: 'reserve' });
  add('relax', 'hammamet', 'friguia-park', 'Friguia Park (Bouficha)', 'حديقة فريقيا (بوفيشة)', 'Wildlife park on the Sousse–Hammamet road; giraffes, lions, a dolphin show. Good stop with the car.', 'حديقة حيوانات على طريق سوسة–الحمامات؛ زرافات وأسود وعرض دلافين. وقفة جيدة بالسيارة.', [36.0270, 10.4500], { slot: 'afternoon', dur: '2 h', price: '$$', tags: ['tickets'] });
  add('relax', 'nabeul', 'korbous', 'Korbous hot springs', 'حمامات قربص', 'Thermal springs running into the sea on the Cap Bon cliff road; an hour’s scenic drive from Hammamet.', 'ينابيع حارة تصب في البحر على طريق جرف رأس الطيب؛ ساعة قيادة جميلة من الحمامات.', [36.8260, 10.5730], { slot: 'afternoon', dur: '2 h', price: '$', tags: ['sea', 'view'] });
  add('relax', 'nabeul', 'kelibia-beach', 'El Mansourah beach · Kelibia', 'شاطئ المنصورة · قليبية', 'Often called the best beach in Tunisia: white sand and clear water below the fort.', 'يوصف غالبًا بأفضل شاطئ في تونس: رمل أبيض وماء صافٍ أسفل القلعة.', [36.8500, 11.1100], { slot: 'midday', dur: '2 h', price: '', tags: ['beach', 'free'] });
  add('relax', 'sousse', 'boujaffar-beach', 'Boujaffar beach · Sousse', 'شاطئ بوجعفر · سوسة', 'City beach a ten-minute walk from the Medina; loungers for rent, cafés behind.', 'شاطئ المدينة على عشر دقائق سيرًا من المدينة العتيقة؛ أسرّة للإيجار ومقاهٍ خلفها.', [35.8330, 10.6400], { slot: 'afternoon', dur: '2 h', price: '$', tags: ['beach', 'easy'] });
  add('relax', 'sousse', 'kantaoui-beach', 'Port El Kantaoui beach & marina', 'شاطئ ومرسى القنطاوي', 'Cleaner sand than the city beach, a promenade and boat trips from the marina.', 'رمل أنظف من شاطئ المدينة وممشى ورحلات بحرية من المرسى.', [35.8930, 10.5980], { slot: 'afternoon', dur: '2 h', price: '$', tags: ['beach', 'sea', 'easy'] });
  add('relax', 'sousse', 'kantaoui-boat', 'Pirate-ship cruise · Port El Kantaoui', 'رحلة سفينة القراصنة · القنطاوي', 'Two-hour family cruise with music and a swim; buy tickets at the marina the day before.', 'رحلة عائلية لساعتين مع موسيقى وسباحة؛ اشتروا التذاكر من المرسى قبل يوم.', [35.8925, 10.5965], { slot: 'afternoon', dur: '2 h', price: '$$', tags: ['sea', 'tickets'], book: 'tickets' });
  add('relax', 'sousse', 'movenpick-spa', 'Mövenpick Sousse marine spa', 'سبا موفنبيك سوسة البحري', 'Thalasso and hammam treatments bookable by non-guests; the recovery option after Kairouan.', 'علاجات تالاسو وحمام يمكن لغير النزلاء حجزها؛ خيار الاستشفاء بعد القيروان.', [35.8400, 10.6270], { slot: 'afternoon', dur: '2 h', price: '$$$', tags: ['spa', 'reserve'], book: 'reserve' });
  add('relax', 'monastir', 'mahdia-beach', 'Mahdia beach', 'شاطئ المهدية', 'Wide, quiet and shallow; the calmest sea on the whole itinerary.', 'واسع وهادئ وضحل؛ أهدأ بحر في الرحلة كلها.', [35.5150, 11.0500], { slot: 'afternoon', dur: '2 h', price: '', tags: ['beach', 'free'] });
  add('relax', 'coast', 'thermes-carthage', 'Les Thermes Marins de Carthage', 'حمامات قرطاج البحرية', 'Gammarth’s big thalasso at The Residence; hammam, pools and massages by the sea.', 'مركز التالاسو الكبير في قمرت داخل ذا ريزيدنس؛ حمام ومسابح وتدليك على البحر.', [36.9220, 10.2905], { slot: 'afternoon', dur: '3 h', price: '$$$', tags: ['spa', 'reserve'], book: 'reserve' });
  add('relax', 'coast', 'gammarth-beach', 'Gammarth & Amilcar beaches', 'شواطئ قمرت وأميلكار', 'The nicest swimming near Tunis; hotel beach clubs rent loungers to visitors.', 'أجمل سباحة قرب تونس؛ نوادي شواطئ الفنادق تؤجّر الأسرّة للزوار.', [36.9150, 10.3050], { slot: 'afternoon', dur: '2 h', price: '$', tags: ['beach'] });
  add('relax', 'coast', 'sidi-bou-said-port', 'Sidi Bou Said marina walk', 'نزهة مرسى سيدي بوسعيد', 'Down the steps to the yacht harbour and the small beach; flat once you are down.', 'نزولًا على الدرج إلى مرسى اليخوت والشاطئ الصغير؛ مستوٍ بعد النزول.', [36.8730, 10.3500], { slot: 'morning', dur: '1 h', price: '', tags: ['sea', 'free', 'stairs'] });
  add('relax', 'tunis', 'hammam-medina', 'Traditional hammam', 'حمام تقليدي', 'Ask your host for the neighbourhood hammam and its women’s and men’s hours; take your own towel and kessa glove.', 'اسألوا المضيف عن حمام الحي وأوقات النساء والرجال؛ خذوا منشفتكم وقفاز الكسة.', [36.7990, 10.1700], { slot: 'afternoon', dur: '1.5 h', price: '$', tags: ['spa'] });
  add('relax', 'tunis', 'belvedere', 'Belvédère Park', 'حديقة البلفيدير', 'The big hill park north of downtown; shade, a Moorish pavilion and the city below.', 'الحديقة الكبيرة على التل شمال وسط المدينة؛ ظل وكشك مغربي والمدينة من تحت.', [36.8210, 10.1730], { slot: 'morning', dur: '1 h', price: '', tags: ['free', 'view'] });

  /* ───────────── STAYS (researched shortlist, ported) ───────────── */
  const S = (id, n, type, tag, guests, rating, note, ll, url, exp, priv, val, tier) => ({ id, n, type, tag, guests, rating, note, ll, url, exp, priv, val, tier });
  const stays = [
    { id: 'tunis', n: 'Tunis', na: 'تونس', nights: 'Sat 19 – Mon 21 · 2 nights', nightsAr: 'السبت 19 – الاثنين 21 · ليلتان', days: ['D2', 'D3'], def: 'dar24', options: [
      S('dar24', 'Dar 24 · whole 18th-century Medina house', 'Entire home', 'Top pick', '7 guests · 3 bedrooms · 3 baths', '4.97 · 152 reviews', 'An entire renovated 18th-century house with patio, rooftop and three bedrooms; the cleanest match to “a riad of our own”. Late check-in must be confirmed.', [36.8016, 10.1688], 'https://www.airbnb.com/rooms/13846170', 10, 10, 6, '$$$'),
      S('typical-medina', 'Typical Medina House', 'Entire home', 'Most traditional', '6 guests · 4 bedrooms · 3 baths', '4.95 · 19 reviews', 'Restored with antique tiles and period objects; more old-house character than a guesthouse.', [36.7988, 10.1700], 'https://www.airbnb.com/rooms/1000626548921981810', 10, 10, 7, '$$$'),
      S('dar-nabiha', 'Dar Nabiha · Tourbet El Bey', 'Entire home', 'Best size for 3', '4 guests · 2 bedrooms · 2 baths', '4.96 · 46 reviews', 'Historic whole house facing Tourbet El Bey with patio and rooftop; two bedrooms fit three naturally.', [36.7941, 10.1702], 'https://www.airbnb.com/rooms/786252231713372133', 9.8, 10, 8, '$$'),
      S('pearl-medina', 'The Pearl of the Medina', 'Entire home', 'Guest favourite', '4 guests · 2 bedrooms', '4.99 · 67 reviews', 'Very strong private-home option in the old city with a high review score.', [36.7984, 10.1706], 'https://www.airbnb.com/rooms/1273014287129551258', 9.8, 10, 7, '$$$'),
      S('elmedina-residence', 'The Elmedina Residence · 19th-century home', 'Entire home', 'Large historic home', '8 guests · 3 bedrooms', '4.83 · 23 reviews', 'Restored 19th-century residence for a stronger whole-house feeling.', [36.7991, 10.1701], 'https://www.airbnb.com/rooms/1370884196405527362', 9.7, 10, 6, '$$$'),
      S('dar-chams', 'Dar Chams · Medina house + small hammam', 'Entire home', 'Hammam + terrace', '6 guests · 3 bedrooms', '4.8 · 15 reviews', 'Renovated Medina home close to Zitouna with terrace and a small traditional hammam.', [36.7990, 10.1697], 'https://www.airbnb.com/rooms/1433514110140365390', 9.6, 10, 7, '$$$'),
      S('dar-saida', 'Dar Saïda · private Medina villa', 'Entire townhouse', 'Best rooftop', '4 guests · 2 bedrooms · 2 baths', '4.78 · 36 reviews', 'Fully private traditional villa in the UNESCO Medina.', [36.7980, 10.1695], 'https://www.airbnb.com/rooms/1522323563808716231', 9.5, 10, 7, '$$$'),
      S('renovated-arab', 'Renovated Arab House · Tourbet El Bey', 'Entire home', 'Designer restoration', '2 guests', '4.79 · 130 reviews', 'Excellent authenticity but sleeps two; only with an extra room nearby.', [36.7942, 10.1702], 'https://www.airbnb.com/rooms/717507', 9.4, 10, 8, '$$'),
      S('dar-zina', 'Dar Zina · family home in the Medina', 'Entire home', 'Family friendly', '4 guests · 2 bedrooms', '4.69 · 54 reviews', 'Private family-sized stay directly on the Medina tourist route.', [36.7978, 10.1709], 'https://www.airbnb.com/rooms/895969011243509417', 9.2, 10, 8, '$$'),
      S('beautiful-medina', 'Beautiful traditional Medina house', 'Entire home', 'Patio house', '4 guests · 1 bedroom + living', '4.71 · 48 reviews', 'Traditional patio house in the middle of the Medina.', [36.7983, 10.1713], 'https://www.airbnb.com/rooms/1161748366994687978', 9.1, 10, 8, '$$'),
      S('guest-medina-apt', 'Guest apartment in a restored Arab house', 'Self-contained apartment', 'Best reviews', '3 guests · 1 bedroom', '4.95 · 388 reviews', 'Private apartment around a bright patio; the entrance is shared.', [36.8015, 10.1687], 'https://www.airbnb.com/rooms/1128813', 9.0, 8, 9, '$$'),
      S('medina-condo', 'Authentic Medina private condo', 'Entire condo', 'Easiest private stay', '4 guests · 2 bedrooms · 1 bath', '4.97 · 32 reviews', 'Less palatial than a full dar, but exclusive use and a traditional patio.', [36.7979, 10.1720], 'https://www.airbnb.com/rooms/1498749589479453958', 8.8, 10, 9, '$$'),
      S('dar-bengacem', 'Dar Ben Gacem', 'Boutique dar', 'Service fallback', 'Book 2 rooms', 'Highly rated', 'Not a whole house, but one of the strongest authentic Medina stays with staff on hand.', [36.8018, 10.1686], 'https://www.darbengacem.com/', 9.8, 5, 5, '$$$$'),
      S('dar-benturkia', 'Dar Ben Turkia · suites + hammam', 'Boutique dar', 'Easiest for mother', 'Book 2 rooms / suite', 'Highly rated', 'Traditional architecture with hotel-like service and easier comfort.', [36.7985, 10.1689], 'https://www.darbenturkia.com/en/home-en-dar-ben-turkia/', 9.4, 5, 5, '$$$$'),
      S('palais-bayram', 'Palais Bayram', 'Historic palace hotel', 'Most palatial', '2 rooms / suites', 'Historic palace', 'High on architecture, lower on privacy than a whole home.', [36.7942, 10.1710], 'https://palaisbayram.com/en/', 9.2, 4, 4, '$$$$'),
      S('dar-el-jeld-hotel', 'Dar El Jeld Hotel & Spa', 'Historic hotel', 'Luxury fallback', '2 rooms', 'Luxury property', 'Strong architecture and comfort, with the famous restaurant downstairs.', [36.8006, 10.1680], 'https://www.dareljeld.com/', 8.8, 4, 3, '$$$$$'),
      S('dar-el-medina', 'Dar El Médina', 'Boutique hotel', 'Classic Medina', '2 rooms', 'Established property', 'Good Medina character with a conventional hospitality setup.', [36.8002, 10.1690], 'https://darelmedinatunis.com/', 8.7, 4, 5, '$$$$'),
      S('center-2br', 'Central Tunis 2-bedroom flat near Medina', 'Entire condo', 'Easy access', '4 guests · 2 bedrooms', '5.0 · 17 reviews', 'Less atmospheric, but practical and close to Avenue Bourguiba.', [36.8035, 10.1780], 'https://www.airbnb.com/rooms/715127335987549636', 7.4, 10, 9, '$$'),
      S('airport-groundfloor', 'Ground-floor family apartment · airport side', 'Entire apartment', 'No stairs', '4 guests', '4.78 · 18 reviews', 'Ground floor, secure, easy with luggage; outside the Medina.', [36.8280, 10.1890], 'https://www.airbnb.com/rooms/41760517', 6.8, 10, 9, '$$'),
      S('lac1-apartment', 'Lac 1 private apartment + parking', 'Entire condo', 'Airport option', '2 guests', '4.89 · 35 reviews', 'Very easy airport access; not the Medina experience.', [36.8350, 10.2240], 'https://www.airbnb.com/rooms/614532216119288980', 6.4, 10, 8, '$$')
    ] },
    { id: 'central', n: 'Sousse / Kairouan', na: 'سوسة / القيروان', nights: 'Mon 21 – Wed 23 · 2 nights', nightsAr: 'الاثنين 21 – الأربعاء 23 · ليلتان', days: ['D4', 'D5'], def: 'central-dar-antonia', options: [
      S('central-dar-antonia', 'Dar Antonia · Sousse Medina', 'Boutique guest house', 'Best two-night base', 'Book 2 rooms / suites', '11 suites', 'Elegant guesthouse in the heart of the Medina with local craft and historical design; service and atmosphere without changing properties.', [35.8268, 10.6378], 'https://darantonia.com/', 10, 6, 5, '$$$$'),
      S('central-split-koraich-antonia', 'Split: Dar Koraich (Kairouan) + Dar Antonia (Sousse)', 'Two-property bundle', 'Covers both cities', '1 night + 1 night', 'Book both directly', 'One authentic Kairouan night with rooftop and hammam, then one refined night inside Sousse Medina. More packing, maximum place-specific experience.', [35.7540, 10.3700], 'https://darkoraich.com/', 10, 6, 5, '$$$$'),
      S('central-split-alouini-antonia', 'Split: Dar Alouini (Kairouan) + Dar Antonia (Sousse)', 'Two-property bundle', 'Best luxury heritage', '1 night + 1 night', 'Book both directly', 'Dar Alouini’s decorated suites, hammam and Great Mosque views, then Dar Antonia.', [35.7540, 10.3700], 'https://dar-alouini.com/index.html', 10, 6, 4, '$$$$$'),
      S('central-private-medina', 'Entire private house · Sousse Medina (search)', 'Entire home search', 'Best privacy', 'Filter for 2+ bedrooms', 'Live Airbnb inventory', 'Prioritise an entire home in or beside Sousse Medina; confirm street, stairs, parking.', [35.8270, 10.6370], 'https://www.airbnb.com/s/Sousse--Tunisia/homes?query=Sousse%20Medina%20Tunisia', 9.2, 10, 7, '$$$'),
      S('central-dar-koraich', 'Dar Koraich · Kairouan', 'Traditional guest house', 'Best Kairouan immersion', 'Rooms / suites', 'Official property', 'Traditional Kairouanese house with rooftop café, private hammam and local food.', [35.6800, 10.1005], 'https://darkoraich.com/', 10, 6, 6, '$$$'),
      S('central-dhiafa-klee', 'Dar Dhiafa Klee · Kairouan Medina', 'Art-led guest house', 'Art + heritage', 'Twin, double, family, royal suite', '2026 pricing published', 'Traditional Kairouan architecture interpreted through Paul Klee’s 1914 visit; a 3-person royal suite suits the group.', [35.6812, 10.1040], 'https://www.dardhiafaklee.com/', 9.9, 6, 8, '$$–$$$'),
      S('central-dar-alouini', 'Dar Alouini · Kairouan Medina', 'Historic luxury guest house', 'Pool + mosque view', '9 suites', 'Official property', 'Themed suites, hammam, indoor pool, underground parking and a terrace over the Great Mosque.', [35.6810, 10.1030], 'https://dar-alouini.com/index.html', 10, 6, 5, '$$$$'),
      S('central-dar-djamila', 'Dar Djamila · Kairouan', 'Traditional guest house', 'Ground-floor suite', '3 suites', 'Official property', 'Small immersive Medina property with a ground-floor suite described with reduced-mobility features.', [35.6806, 10.1018], 'https://www.dardjamila.com/', 9.7, 6, 6, '$$$'),
      S('central-dar-baaziz', 'Dar Baaziz · Sousse Medina', 'Traditional guest house', 'Intimate Medina', 'Rooms around a courtyard', 'Check live', 'Small traditional house inside Sousse Medina with a gentler price.', [35.8261, 10.6362], 'https://www.google.com/search?q=Dar+Baaziz+Sousse', 9.6, 6, 8, '$$'),
      S('central-dar-lekbira', 'Dar Lekbira Boutique Hôtel · Sousse', 'Boutique dar', 'Traditional + central', 'Rooms / suites', 'Check live', 'Traditional-style Medina stay close to the Ribat and souks.', [35.8269, 10.6370], 'https://www.google.com/search?q=Dar+Lekbira+Boutique+Hotel+Sousse', 9.4, 6, 7, '$$$'),
      S('central-dar-omi', 'Dar Omi · Sousse', 'Family guest house', 'Women-run', 'Guest rooms', 'Official property', 'Women-run family guesthouse focused on Tunisian culture and local suppliers.', [35.8300, 10.6100], 'https://www.daromi-bnb.com/', 9.2, 5, 8, '$$'),
      S('central-dar-badiaa', 'Dar Badiaa · Sousse Medina', 'Traditional guest house', 'Rooftop + Medina', 'Rooms / suites', 'Official property', 'Traditional guesthouse in Sousse Medina with rooftop views.', [35.8266, 10.6368], 'https://www.darbadiaa.com.tn/', 9.1, 5, 7, '$$$'),
      S('central-dar-hkaiem', 'Dar Hkaïem · Sousse', 'Guest house', 'Best value character', 'Rooms / family options', 'Check live', 'Smaller locally run option with a calm residential feel.', [35.8380, 10.6280], 'https://www.google.com/search?q=Dar+Hkaiem+Sousse', 8.8, 6, 9, '$$'),
      S('central-hassine-allani', 'Dar Hassine Allani · Kairouan', 'Traditional guest rooms', '18th-century house', '3 rooms', 'Very limited', 'Rare 18th-century Kairouanese house with three rooms; call immediately.', [35.6805, 10.1015], 'https://www.google.com/search?q=Dar+Hassine+Allani+Kairouan', 10, 5, 4, '$$$$'),
      S('central-la-kasbah', 'La Kasbah Kairouan', 'Hotel', 'Full-service Kairouan', '2 rooms / suite', 'Check live', 'The strongest conventional full-service base in Kairouan.', [35.6798, 10.1020], 'https://www.google.com/search?q=La+Kasbah+Kairouan+hotel', 8.4, 5, 5, '$$$$'),
      S('central-continental', 'Hotel Continental · Kairouan', 'Hotel', 'Parking + pool', '2 rooms / suite', 'Official property', 'Across from the Aghlabid Basins with parking and pool.', [35.6783, 10.0961], 'https://continental.tn/en-gb/', 6.8, 5, 8, '$$'),
      S('central-private-kantaoui', 'Private apartment / villa · Port El Kantaoui (search)', 'Entire home search', 'Space + sea', 'Filter for 2+ bedrooms', 'Live Airbnb inventory', 'Private and easier for parking than the Medina; lower historical immersion.', [35.8940, 10.5940], 'https://www.airbnb.com/s/Port-El-Kantaoui--Tunisia/homes', 7.8, 10, 8, '$$$'),
      S('central-movenpick', 'Mövenpick Resort & Marine Spa Sousse', 'Luxury resort', 'Beach + spa', '2 rooms / suite', 'Check live', 'Reliable beachfront resort and spa; strong comfort, weaker character.', [35.8402, 10.6272], 'https://movenpick.accor.com/en/africa/tunisia/sousse/resort-sousse.html', 7.4, 5, 5, '$$$$'),
      S('central-pearl-marriott', 'Sousse Pearl Marriott Resort & Spa', 'Luxury hotel', 'Modern luxury', '2 rooms / suite', 'Check live', 'Full-service seafront luxury with parking and easy logistics.', [35.8355, 10.6260], 'https://www.marriott.com/en-us/hotels/mirmc-sousse-pearl-marriott-resort-and-spa/overview/', 7.5, 5, 4, '$$$$$'),
      S('central-hasdrubal', 'Hasdrubal Thalassa & Spa Port El Kantaoui', 'Luxury thalasso hotel', 'Premium spa', '2 rooms / suites', 'Check live', 'Premium thalassotherapy and marina access.', [35.8920, 10.5980], 'https://www.hasdrubal-thalassa.com/', 7.0, 5, 3, '$$$$$')
    ] },
    { id: 'hammamet', n: 'Hammamet', na: 'الحمامات', nights: 'Wed 23 – Fri 25 · 2 nights', nightsAr: 'الأربعاء 23 – الجمعة 25 · ليلتان', days: ['D6', 'D7'], def: 'dar-sandra', options: [
      S('dar-sandra', 'Dar Sandra · traditional house 100 m from beach', 'Entire home', 'Best of both', '6 guests · 2 bedrooms · 3.5 baths', '4.86 · 42 reviews', 'Private traditional Hammamet house with hammam and rooftop jacuzzi, about 100 m from the beach and close to the Medina.', [36.4050, 10.6080], 'https://www.airbnb.com/rooms/5833417', 10, 10, 7, '$$$'),
      S('dar-el-nour', 'Dar El Nour · authentic home steps from the sea', 'Entire home', 'Best for exactly 3', '4 guests · 2 bedrooms · 2 baths', '5.0 · 7 reviews', 'Private courtyard, carved doors, antique furniture, about 100 m from the sea.', [36.4130, 10.6300], 'https://www.airbnb.com/rooms/1525311066959517055', 10, 10, 8, '$$'),
      S('medina-pool-villa', 'Medina villa · pool + sea view', 'Entire villa', 'Hybrid + pool', '9 guests · 3 bedrooms · 2 baths', '4.8', 'Traditional dar renovated in Medina style, a few dozen metres from the sea, with private pool.', [36.4003, 10.6146], 'https://www.airbnb.com/rooms/3725112', 9.7, 10, 5, '$$$$'),
      S('auth-home-100m', 'Authentic vaulted home · 100 m from beach', 'Entire home', 'Traditional + beach', '6 guests · 2 bedrooms', 'New listing', 'Vaulted interior, private patio and beach access about 100 m away.', [36.4065, 10.6150], 'https://www.airbnb.com/rooms/40671339', 9.7, 10, 9, '$$'),
      S('feet-water', 'Traditional Medina home · 80 m from beach', 'Entire home', 'Walk everywhere', '5 guests · 2 bedrooms · 1 bath', '5.0 · 5 reviews', 'Arabesque-style private house in Hammamet Medina, near beach, restaurants and market.', [36.3998, 10.6148], 'https://www.airbnb.com/rooms/1666196726506983656', 9.6, 10, 9, '$$'),
      S('atypical-medina', 'Atypical Medina house · close to beach', 'Entire home', '5 bedrooms', '10 guests · 5 bedrooms', '4.78', 'Large heritage-forward home near the fort and beach with private patio.', [36.3999, 10.6144], 'https://www.airbnb.com/rooms/44019421', 9.3, 10, 5, '$$$$'),
      S('dar-lily', 'Dar Lily · Arabesque villa + pool', 'Entire home', 'Design + beach', '8 guests · 4 bedrooms', '4.98 · 48 reviews', 'Modern design blended with Arabesque character; pool and a short drive to beaches.', [36.4140, 10.6260], 'https://www.airbnb.com/rooms/1188160876603055835', 9.2, 10, 4, '$$$$'),
      S('dar-sadok', 'Dar Sadok · pool · 300 m from beach', 'Entire villa', 'Family villa', '10 guests · 4 bedrooms', '4.95 · 42 reviews', 'Decorated family house with pool and beach access nearby.', [36.3850, 10.5520], 'https://www.airbnb.com/rooms/16076008', 8.9, 10, 6, '$$$'),
      S('perfect-beach', 'Perfect Beach House · direct sea access + pool', 'Entire villa', 'Pure beach luxury', '8 guests · 4 suites · 4.5 baths', 'New listing', 'Direct garden-to-sand access, heated pool and rooftop jacuzzi.', [36.4380, 10.6850], 'https://www.airbnb.com/rooms/1387187738394617333', 8.8, 10, 3, '$$$$$'),
      S('ideal-holidays', 'Single-storey villa · 50 m from beach', 'Entire villa', 'No stairs', '6 guests · 2 bedrooms', '4.9 · 106 reviews', 'Very close to the beach, secure residence, single-storey layout.', [36.4200, 10.6450], 'https://www.airbnb.com/rooms/6581887', 8.7, 10, 9, '$$'),
      S('villa-athena', 'Villa Athena · pool + hammam + rooftop', 'Entire home', 'Full amenities', '10 guests · 5 bedrooms', '4.8', 'Large villa with pool, hammam and rooftop sea view, about 500 m from beach.', [36.4140, 10.6060], 'https://www.airbnb.com/rooms/964410154431144201', 8.6, 10, 3, '$$$$$'),
      S('waterfront-villa', 'Waterfront villa · garden', 'Entire villa', 'Large private villa', '12 guests · 5 bedrooms · 3 baths', '4.83', 'A larger private option with garden and a standalone beach-house feel.', [36.4320, 10.6750], 'https://www.airbnb.com/rooms/23662274', 8.4, 10, 4, '$$$$'),
      S('triplex-pool', 'Beach triplex · private pool · 200 m beach', 'Entire home', 'Best value beach home', '8 guests · 3 bedrooms · 3 baths', '4.97 · 31 reviews', 'Modern private option with pool and a short beach walk.', [36.4200, 10.6500], 'https://www.airbnb.com/rooms/1023026721428369661', 8.3, 10, 8, '$$$'),
      S('smart-seaview', 'Luxury smart villa · panoramic sea view', 'Entire villa', 'Luxury panorama', '8 guests · 4 suites', '5.0', 'Private pool and panoramic bay view; luxury rather than traditional.', [36.4450, 10.6740], 'https://www.airbnb.com/rooms/1695726963843056186', 8.3, 10, 2, '$$$$$'),
      S('new-villa-ham', 'New Villa Hammamet · pool', 'Entire villa', 'Top 10%', '10 guests · 4 bedrooms', '4.92 · 13 reviews', 'Quiet secured villa about 8 minutes on foot from the beach.', [36.4080, 10.5980], 'https://www.airbnb.com/rooms/1132556202972894132', 8.2, 10, 7, '$$$'),
      S('dar-janna', 'Villa Dar Janna · 200 m from beach', 'Entire villa', 'Large garden', '15 guests · 7 bedrooms', '4.48 · 21 reviews', 'Huge traditional-style family villa close to the beach; oversized for three.', [36.4310, 10.6720], 'https://www.airbnb.com/rooms/26003992', 8.0, 10, 5, '$$$$'),
      S('private-beach-garden', 'Private beach + pool + garden', 'Entire home', 'Direct beach feel', '10 guests · 3 bedrooms', '4.6 · 5 reviews', 'Private pool, garden and access to a private beach.', [36.3700, 10.5350], 'https://www.airbnb.com/rooms/1372884089781513228', 8.0, 10, 4, '$$$$'),
      S('pool-3min', 'Private pool villa · 3 min from beach', 'Entire villa', 'Pool + hot tub', '6 guests · 3 bedrooms', '5.0 · 6 reviews', 'Strong family setup near beach and shops.', [36.4180, 10.6410], 'https://www.airbnb.com/rooms/43981027', 7.9, 10, 7, '$$$'),
      S('villa-5min', 'Upscale villa · 5-min walk to beach', 'Entire villa', 'Modern family', '8 guests · 4 bedrooms', 'Strong recent reviews', 'Modern villa with pool close to beach.', [36.4230, 10.6500], 'https://www.airbnb.com/rooms/1245526449934492917', 7.8, 10, 5, '$$$$'),
      S('elite-villa', 'Elite Villa · La Badira area', 'Entire home', 'Private pool', '7 guests · 3 bedrooms', '5.0 · 8 reviews', 'Modern luxury, private pool, about three minutes to beach.', [36.4300, 10.6800], 'https://www.airbnb.com/rooms/1708017538541241668', 7.7, 10, 4, '$$$$')
    ] }
  ];

  /* ───────────── CAR (researched shortlist, ported) ───────────── */
  const C = (id, n, type, tag, lux, comfort, val, price, avail, note, link) => ({ id, n, type, tag, lux, comfort, val, price, avail, note, link });
  const cars = [
    C('bmw-x5', 'BMW X5 or similar', 'Luxury SUV · 5 seats', 'Best luxury fit', 10, 9.7, 7.5, 'From ~€85/day benchmark', 'Tunis-airport model search exists', 'Best balance of luxury, luggage space and road-trip comfort for three adults. Confirm the exact X5, automatic, unlimited mileage, full cover.', 'https://bookingauto.com/en/tunisia/tunis-airport/bmw-x5'),
    C('range-rover-sport', 'Range Rover / Range Rover Sport', 'Full-size luxury SUV', 'Most prestigious', 10, 9.8, 5.5, 'Premium quote required', 'Ask premium local agencies', 'The most prestigious choice if an agency guarantees the exact model; highest cost and deposit.', 'https://tunisiarentcar.net/car-hire-luxe'),
    C('land-cruiser-prado', 'Toyota Land Cruiser Prado 2025', 'Large SUV · 7 seats', 'Verified local full-size', 8.2, 8.8, 6.5, 'VIPCAR benchmark: €420/day', 'VIPCAR lists a 2025 Prado', 'The strongest currently listed full-size SUV for an immediate exact-model booking: seven seats, automatic, four-bag capacity.', 'https://vipcar.com.tn/en/services/rental'),
    C('mercedes-gle', 'Mercedes-Benz GLE', 'Luxury SUV · 5 seats', 'Luxury + comfort', 9.8, 9.8, 6.0, 'Premium live quote', 'Request exact GLE', 'Superb long-distance comfort and enough boot space for a moving itinerary.', 'https://www.troisa.com/location-voiture-luxe-tunisie/'),
    C('audi-q7', 'Audi Q7', 'Large luxury SUV · up to 7 seats', 'Spacious premium', 9.6, 9.6, 6.0, 'Premium live quote', 'Premium fleet request', 'Excellent cabin and luggage capacity; large for Medina streets, ideal on the road.', 'https://www.troisa.com/location-voiture-luxe-tunisie/'),
    C('volvo-xc90', 'Volvo XC90', 'Luxury SUV · up to 7 seats', 'Comfort pick', 9.4, 9.8, 6.1, 'Premium live quote', 'Ask premium supplier', 'Comfort and safety oriented, easy cabin access, generous luggage room.', 'https://www.sixt.com/car-rental/tunisia/'),
    C('bmw-x3', 'BMW X3', 'Premium SUV · 5 seats', 'Easier city luxury', 9.2, 9.2, 7.2, 'Live airport quote', 'Tunis-airport model search exists', 'More manageable in Tunis and Sousse streets than an X5 with premium comfort.', 'https://bookingauto.com/en/tunisia/tunis-airport/bmw-x3'),
    C('mercedes-glc', 'Mercedes-Benz GLC', 'Premium SUV · 5 seats', 'Refined compact luxury', 9.2, 9.3, 7.0, 'Live premium quote', 'Request GLC or equivalent', 'A strong size compromise for parking, airport luggage and long-road comfort.', 'https://www.lacrentacar.com/en/luxury-car-rental-tunisia'),
    C('lexus-rx', 'Lexus RX', 'Luxury SUV · 5 seats', 'Quiet luxury', 9.3, 9.6, 6.2, 'Special request quote', 'Limited', 'Quiet, smooth and comfortable if a premium supplier can source it.', 'https://www.sixt.com/car-rental/tunisia/'),
    C('porsche-cayenne', 'Porsche Cayenne / Macan', 'Performance luxury SUV', 'Driver luxury', 9.7, 8.8, 4.5, 'High premium quote', 'Special premium request', 'Excellent to drive; less rational on cost and luggage than X5 or GLE.', 'https://www.troisa.com/location-voiture-luxe-tunisie/'),
    C('audi-q5', 'Audi Q5', 'Premium SUV · 5 seats', 'Balanced premium', 9.0, 9.0, 7.0, 'Live premium quote', 'Ask for exact model', 'Well-sized premium option for mixed city and highway driving.', 'https://www.sixt.com/car-rental/tunisia/'),
    C('volvo-xc60', 'Volvo XC60', 'Premium SUV · 5 seats', 'Comfortable premium', 8.9, 9.3, 6.8, 'Live quote', 'Premium request', 'Comfort-focused midsize SUV, easier around Tunis than a full-size model.', 'https://www.sixt.com/car-rental/tunisia/'),
    C('mercedes-gla', 'Mercedes-Benz GLA', 'Compact luxury SUV', 'Verified local premium', 8.6, 8.4, 7.5, 'LAC Rent A Car: from 350 TND/day', 'Listed at Tunis airport', 'A genuine premium SUV listed by a Tunis agency; easier in old-city streets, check boot for three large cases.', 'https://www.lacrentacar.com/'),
    C('vw-tiguan', 'Volkswagen Tiguan', 'SUV · 5 seats', 'Verified local practical', 7.8, 8.8, 8.2, 'LAC Rent A Car: from 250 TND/day', 'Listed automatic at Tunis airport', 'The most realistic premium-practical fallback: automatic, manageable in Tunis, comfortable on the road.', 'https://www.lacrentacar.com/'),
    C('peugeot-5008', 'Peugeot 5008', 'Large SUV · up to 7 seats', 'Family space', 7.5, 8.7, 8.0, 'Live quote', 'Common class', 'Very good luggage and passenger space with a refined family cabin.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html'),
    C('jetour-t2', 'Jetour T2', 'SUV · 5 seats', 'Rugged style', 7.7, 8.4, 8.4, 'Exact rental quote needed', 'Request guaranteed model', 'Stylish and spacious; kept because it was an earlier favourite.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html'),
    C('skoda-karoq', 'Škoda Karoq / Kushaq', 'Compact SUV · 5 seats', 'Practical value', 7.2, 8.4, 9.0, 'Live airport quote', 'Kushaq-or-similar class at TUN', 'A sensible value backup with an easier city footprint.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html'),
    C('hyundai-santa-fe', 'Hyundai Santa Fe', 'Large SUV · up to 7 seats', 'Roomy family SUV', 7.4, 8.8, 7.5, 'Live quote', 'Ask supplier', 'Comfortable and roomy for luggage at a lower price than European luxury.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html'),
    C('kia-sorento', 'Kia Sorento', 'Large SUV · up to 7 seats', 'Comfort + space', 7.3, 8.7, 7.6, 'Live quote', 'Ask supplier', 'Good family comfort and luggage capacity if the premium fleet is unavailable.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html'),
    C('nissan-xtrail', 'Nissan X-Trail', 'SUV · up to 7 seats', 'Reliable fallback', 6.8, 8.2, 8.0, 'Live quote', 'Common SUV class', 'A practical last-minute fallback with good luggage space.', 'https://www.booking.com/cars/airport/tn/tun.en-gb.html')
  ];

  /* ───────────── DAYS ───────────── */
  const D = (id, date, en, ar, ten, tar, areas, stay, fixed) => ({ id, date, en, ar, ten, tar, areas, stay, fixed });
  // fixed rows: {slot, time, en, ar, ll, kind:'flight'|'drive'|'note'}
  const days = [
    D('D1', '2026-09-18', 'Fri 18', 'الجمعة 18', 'Night flight to Tunis', 'رحلة ليلية إلى تونس', [], null, [
      { slot: 'night', time: 'out.dep', en: 'Depart Riyadh', ar: 'المغادرة من الرياض', kind: 'flight' }
    ]),
    D('D2', '2026-09-19', 'Sat 19', 'السبت 19', 'Arrive · a gentle first day in Tunis', 'الوصول · يوم أول هادئ في تونس', ['tunis', 'coast'], 'tunis', [
      { slot: 'morning', time: 'out.arr', en: 'Land at Tunis–Carthage, drive to the Medina, sleep in', ar: 'الهبوط في مطار تونس قرطاج، ثم إلى المدينة العتيقة والنوم', ll: [36.8510, 10.2272], kind: 'flight' }
    ]),
    D('D3', '2026-09-20', 'Sun 20', 'الأحد 20', 'Bardo, Carthage and the coast', 'باردو وقرطاج والساحل', ['tunis', 'coast', 'road'], 'tunis', []),
    D('D4', '2026-09-21', 'Mon 21', 'الاثنين 21', 'Tunis → Zaghouan → Kairouan → Sousse', 'تونس ← زغوان ← القيروان ← سوسة', ['road', 'kairouan', 'sousse'], 'central', [
      { slot: 'morning', time: '08:00', en: 'Check out, drive to Kairouan · ~2 h via Zaghouan', ar: 'تسجيل الخروج والقيادة إلى القيروان · نحو ساعتين عبر زغوان', kind: 'drive' },
      { slot: 'afternoon', time: '16:00', en: 'Drive Kairouan → Sousse · ~1 h', ar: 'القيادة من القيروان إلى سوسة · نحو ساعة', kind: 'drive' }
    ]),
    D('D5', '2026-09-22', 'Tue 22', 'الثلاثاء 22', 'Sousse, Monastir or back to Kairouan', 'سوسة أو المنستير أو العودة إلى القيروان', ['sousse', 'monastir', 'kairouan'], 'central', []),
    D('D6', '2026-09-23', 'Wed 23', 'الأربعاء 23', 'El Jem → Hammamet', 'الجم ← الحمامات', ['eljem', 'monastir', 'road', 'hammamet'], 'hammamet', [
      { slot: 'morning', time: '08:30', en: 'Check out, drive to El Jem · ~1 h', ar: 'تسجيل الخروج والقيادة إلى الجم · نحو ساعة', kind: 'drive' },
      { slot: 'afternoon', time: '14:30', en: 'Drive El Jem → Hammamet · ~2 h', ar: 'القيادة من الجم إلى الحمامات · نحو ساعتين', kind: 'drive' }
    ]),
    D('D7', '2026-09-24', 'Thu 24', 'الخميس 24', 'Nabeul, the beach and a slow evening', 'نابل والشاطئ ومساء هادئ', ['hammamet', 'nabeul'], 'hammamet', []),
    D('D8', '2026-09-25', 'Fri 25', 'الجمعة 25', 'Hammamet → airport → Riyadh', 'الحمامات ← المطار ← الرياض', ['hammamet'], null, [
      { slot: 'midday', time: 'back.leave', en: 'Leave Hammamet for the airport · ~1 h 15 drive, arrive 3 h before', ar: 'الانطلاق من الحمامات إلى المطار · نحو ساعة و15 دقيقة، والوصول قبل 3 ساعات', kind: 'drive' },
      { slot: 'afternoon', time: 'back.dep', en: 'Depart Tunis–Carthage for Riyadh', ar: 'المغادرة من مطار تونس قرطاج إلى الرياض', ll: [36.8510, 10.2272], kind: 'flight' }
    ])
  ];

  const areas = {
    tunis: { en: 'Tunis', ar: 'تونس', c: [36.800, 10.175] },
    coast: { en: 'Carthage · Sidi Bou Said · La Marsa', ar: 'قرطاج · سيدي بوسعيد · المرسى', c: [36.870, 10.330] },
    road: { en: 'Day trips & road stops', ar: 'رحلات يومية ووقفات الطريق', c: [36.40, 10.10] },
    kairouan: { en: 'Kairouan', ar: 'القيروان', c: [35.680, 10.100] },
    sousse: { en: 'Sousse · Port El Kantaoui', ar: 'سوسة · القنطاوي', c: [35.830, 10.635] },
    monastir: { en: 'Monastir · Mahdia', ar: 'المنستير · المهدية', c: [35.640, 10.950] },
    eljem: { en: 'El Jem', ar: 'الجم', c: [35.296, 10.707] },
    hammamet: { en: 'Hammamet', ar: 'الحمامات', c: [36.395, 10.600] },
    nabeul: { en: 'Nabeul · Cap Bon', ar: 'نابل · الوطن القبلي', c: [36.455, 10.735] }
  };

  const cats = [
    { id: 'food', en: 'Food', ar: 'طعام' },
    { id: 'sights', en: 'Sights', ar: 'معالم' },
    { id: 'shopping', en: 'Shopping', ar: 'تسوّق' },
    { id: 'nightlife', en: 'Nightlife', ar: 'سهر' },
    { id: 'relax', en: 'Relax', ar: 'استرخاء' }
  ];

  const slots = [
    { id: 'morning', en: 'Morning', ar: 'صباحًا' },
    { id: 'midday', en: 'Midday', ar: 'ظهرًا' },
    { id: 'afternoon', en: 'Afternoon', ar: 'عصرًا' },
    { id: 'evening', en: 'Evening', ar: 'مساءً' },
    { id: 'night', en: 'Night', ar: 'ليلًا' }
  ];

  const tags = {
    unesco: { en: 'UNESCO', ar: 'يونسكو' }, view: { en: 'View', ar: 'إطلالة' }, sea: { en: 'By the sea', ar: 'على البحر' },
    easy: { en: 'Easy walking', ar: 'مشي سهل' }, stairs: { en: 'Stairs', ar: 'درج' }, reserve: { en: 'Reserve', ar: 'يلزم حجز' },
    tickets: { en: 'Tickets', ar: 'تذاكر' }, friday: { en: 'Fridays only', ar: 'الجمعة فقط' }, sunset: { en: 'Sunset', ar: 'غروب' },
    alcohol: { en: 'Serves alcohol', ar: 'يقدّم كحولًا' }, noAlcohol: { en: 'No alcohol', ar: 'بلا كحول' }, tea: { en: 'Tea', ar: 'شاي' },
    beach: { en: 'Beach', ar: 'شاطئ' }, spa: { en: 'Spa', ar: 'سبا' }, museum: { en: 'Museum', ar: 'متحف' }, free: { en: 'Free', ar: 'مجاني' },
    closedMon: { en: 'Closed Mondays', ar: 'مغلق الاثنين' }
  };

  // Default plan: a coherent, unhurried week. Every row can be removed or moved.
  const defaultPlan = {
    D2: ['medina-walk', 'zitouna', 'fondouk-attarine', 'souk-attarine', 'souk-kmach', 'sidi-bou-said', 'sidi-chabaane', 'bon-vieux-temps'],
    D3: ['bardo', 'byrsa', 'antonine-baths', 'cafe-vert', 'la-marsa-corniche', 'dar-zarrouk'],
    D4: ['zaghouan-temple', 'great-mosque', 'aghlabid-basins', 'dar-koraich', 'kairouan-medina', 'makroudh', 'dar-antonia-dinner'],
    D5: ['sousse-ribat', 'sousse-mosque', 'sousse-museum', 'le-lido', 'kantaoui-beach', 'monastir-ribat', 'monastir-marina-lunch'],
    D6: ['eljem-amphitheatre', 'eljem-museum', 'eljem-lunch', 'takrouna', 'hammamet-medina', 'hammamet-kasbah', 'barberousse'],
    D7: ['nabeul-pottery', 'nabeul-souk', 'chez-achour', 'hammamet-beach', 'bio-azur', 'sidi-bou-hdid'],
    D8: ['hammamet-beach']
  };
  // slot overrides for default rows that differ from the place default
  const defaultSlots = { 'D5:monastir-marina-lunch': 'evening', 'D6:hammamet-medina': 'evening', 'D6:hammamet-kasbah': 'evening', 'D7:sidi-bou-hdid': 'evening', 'D8:hammamet-beach': 'morning', 'D3:la-marsa-corniche': 'afternoon' };

  const goodToKnow = [
    { en: 'Money: Tunisian dinar (TND) is a closed currency; withdraw from ATMs on arrival and keep receipts to change back. Cards work in hotels and bigger restaurants, cash in souks.', ar: 'المال: الدينار التونسي عملة مغلقة؛ اسحبوا من الصراف عند الوصول واحتفظوا بالإيصالات لإعادة الصرف. البطاقات تعمل في الفنادق والمطاعم الكبيرة، والنقد في الأسواق.' },
    { en: 'Tipping: round up in cafés; 5–10% in restaurants; 2–5 TND for porters and guides’ helpers.', ar: 'الإكرامية: تقريب المبلغ في المقاهي؛ 5–10% في المطاعم؛ 2–5 دنانير للحمّالين ومساعدي المرشدين.' },
    { en: 'Fridays: souks quieten around midday prayer; the Nabeul market is Friday mornings; museums keep normal hours. The Bardo closes on Mondays.', ar: 'الجمعة: تهدأ الأسواق وقت صلاة الجمعة؛ سوق نابل صباح الجمعة؛ المتاحف بمواعيدها المعتادة. باردو يغلق الاثنين.' },
    { en: 'Driving: motorway A1 Tunis–Sousse–El Jem is fast and tolled (small change). Medina streets are pedestrian; park outside and walk. Speed cameras are common.', ar: 'القيادة: الطريق السيار A1 تونس–سوسة–الجم سريع ومدفوع (فكة). شوارع المدن العتيقة للمشاة؛ اركنوا خارجها وامشوا. رادارات السرعة منتشرة.' },
    { en: 'Mosques: Zitouna and the Great Mosque of Kairouan welcome Muslim visitors to the prayer halls; dress modestly, shoes off, avoid prayer times for sightseeing.', ar: 'المساجد: الزيتونة وجامع القيروان يرحبان بالزوار المسلمين في بيوت الصلاة؛ لباس محتشم وخلع الأحذية وتجنب أوقات الصلاة للزيارة.' },
    { en: 'Heat: late September is still 28–32 °C on the coast. Sights before 11 or after 16; beach and spa in the middle of the day.', ar: 'الحر: أواخر سبتمبر ما زال 28–32 درجة على الساحل. المعالم قبل 11 أو بعد 16؛ الشاطئ والسبا وسط النهار.' }
  ];

  return { start: '2026-09-18', travelers: 3, flight: { airline: 'Royal Jordanian · RJ737 + RJ553', route: 'RUH → AMM → TUN', out: { dep: '20:15', arr: '02:15' }, back: { dep: '', leave: '' } }, places: P, stays, cars, days, areas, cats, slots, tags, defaultPlan, defaultSlots, goodToKnow };
})();
