(()=>{
const dict={
'TUNISIA · URGENT PLAN':'تونس · خطة عاجلة',
'Book now':'الحجز الآن',
'3 adults · departure date must be confirmed before payment':'3 بالغين · يجب تأكيد تاريخ المغادرة قبل الدفع',
'Tunis first.':'تونس أولًا.',
'Central Tunisia next.':'ثم وسط تونس.',
'Two nights in Tunis, two nights in Sousse/Kairouan, two beach nights in Hammamet, then one final night near Sidi Bou Said or Tunis.':'ليلتان في تونس، وليلتان في سوسة/القيروان، وليلتان على شاطئ الحمامات، ثم ليلة أخيرة قرب سيدي بوسعيد أو تونس.',
'✈ Riyadh ~16:00':'✈ الرياض نحو 16:00','🏠 Tunis · 2 nights':'🏠 تونس · ليلتان','🕌 Sousse/Kairouan · 2 nights':'🕌 سوسة/القيروان · ليلتان','🌊 Hammamet · 2 nights':'🌊 الحمامات · ليلتان','🏡 Tunis/Sidi · 1 night':'🏡 تونس/سيدي · ليلة واحدة',
'Choose the full route or a specific day. Your selected stays and timeslot choices update this map automatically.':'اختاروا المسار كاملًا أو يومًا محددًا. تُحدّث الإقامات والأنشطة المختارة الخريطة تلقائيًا.',
'The selected plan, day by day.':'الخطة المختارة يومًا بيوم.',
'Tap a day to expand it. Every activity timeslot pulls one choice from the three alternatives in Configuration.':'اضغطوا على أي يوم لعرض التفاصيل. لكل فترة نشاط خيار واحد من ثلاثة بدائل في قسم الإعدادات.',
'03 · Booking control center':'03 · مركز إدارة الحجوزات','Turn the plan into reservations.':'حوّلوا الخطة إلى حجوزات.',
'Choose the actual departure dates first, then lock the flight, first stay and SUV before working through the remaining checklist.':'اختاروا تواريخ السفر الفعلية أولًا، ثم ثبّتوا الرحلة الجوية والإقامة الأولى والسيارة قبل متابعة بقية قائمة الحجز.',
'04 · Configuration':'04 · الإعدادات','Choose each piece of the trip.':'اختاروا كل جزء من الرحلة.',
'Your selections are saved on this device and immediately feed the calendar, map and booking brief.':'تُحفظ اختياراتكم على هذا الجهاز وتُحدّث الجدول والخريطة وملخص الحجز مباشرة.',
'Configure the luxury SUV':'اختيار السيارة الفاخرة','Import the WhatsApp group suggestions':'استيراد اقتراحات مجموعة واتساب',
'20 route patterns ranked around your preferred':'20 مسارًا جويًا مرتبة وفق توقيتكم المفضل','~16:00 Riyadh departure':'مغادرة الرياض نحو 16:00','shortest journey time, and preferred hubs: Istanbul, Doha and Jeddah.':'وأقصر مدة سفر، مع تفضيل إسطنبول والدوحة وجدة.',
'Fastest time-fit:':'الأقرب لتوقيتكم:','the 16:05 Flynas flight to Istanbul can connect to a 21:50 Turkish flight to Tunis, but it may be a self-connect. A protected one-ticket itinerary is safer when booking at the last minute.':'يمكن لرحلة طيران ناس الساعة 16:05 إلى إسطنبول أن ترتبط برحلة التركية الساعة 21:50 إلى تونس، لكن قد يكون الربط ذاتيًا. الحجز بتذكرة واحدة محمية أكثر أمانًا عند الحجز المتأخر.',
'Schedules and fares are live-check prompts, not locked inventory. Confirm terminal, baggage transfer, connection protection and final arrival date at checkout.':'الجداول والأسعار تحتاج تحققًا مباشرًا وليست مخزونًا محجوزًا. أكدوا مبنى المطار ونقل الأمتعة وحماية الربط وتاريخ الوصول النهائي عند الدفع.',
'20 premium SUVs ranked for luxury, comfort, luggage space and realistic Tunisian availability. The selected vehicle is intended for the full stay.':'20 سيارة SUV فاخرة مرتبة حسب الفخامة والراحة ومساحة الأمتعة وإمكانية التوفر في تونس. السيارة المختارة مخصصة لكامل مدة الرحلة.',
'Recommended first:':'الخيار الأول:','BMW X5 or similar. Then Range Rover Sport, Mercedes GLE, Audi Q7 and Volvo XC90. Get the exact model, automatic transmission, unlimited mileage and full insurance confirmed in writing.':'BMW X5 أو ما يماثلها، ثم Range Rover Sport وMercedes GLE وAudi Q7 وVolvo XC90. اطلبوا تأكيد الطراز المحدد وناقل الحركة الأوتوماتيكي والكيلومترات غير المحدودة والتأمين الكامل كتابةً.',
'“Or similar” does not guarantee the model pictured. Confirm boot size for three adults’ luggage, deposit, excess, second driver and cross-city drop-off rules.':'عبارة «أو ما يماثلها» لا تضمن الطراز المصوّر. أكدوا مساحة الصندوق لحقائب ثلاثة بالغين والتأمين والوديعة والسائق الإضافي وسياسة التسليم في مدينة أخرى.',
'Paste the latest stay suggestions and links from the group. They are preserved as group-sourced options and added to the appropriate stay block without replacing the researched shortlist.':'الصقوا أحدث اقتراحات وروابط الإقامة من المجموعة. ستُحفظ كخيارات مصدرها المجموعة وتُضاف إلى فترة الإقامة المناسبة دون استبدال القائمة المدروسة.',
'Four stay blocks: Tunis, Sousse/Kairouan, Hammamet and the final Tunis/Sidi night. Each researched block contains at least 20 ranked options, plus any WhatsApp imports.':'أربع فترات إقامة: تونس، سوسة/القيروان، الحمامات، والليلة الأخيرة في تونس/سيدي بوسعيد. تحتوي كل فترة على 20 خيارًا مدروسًا على الأقل، إضافة إلى اقتراحات واتساب المستوردة.',
'✨ Experience = how memorable/local the stay feels':'✨ التجربة = مدى تميّز ومحلية الإقامة','🔒 Privacy = how exclusively the space is yours':'🔒 الخصوصية = مدى استقلال المكان لكم','💰 Price = relative value; 10/10 is better value':'💰 السعر = القيمة النسبية؛ 10/10 تعني قيمة أفضل',
'28 timeslots · 3 alternatives per slot · 84 image-backed choices.':'28 فترة · 3 بدائل لكل فترة · 84 خيارًا بالصور.','Select one option in each slot or skip the slot. The calendar and map recalculate instantly.':'اختاروا خيارًا واحدًا لكل فترة أو تخطوا الفترة. يتحدث الجدول والخريطة مباشرة.',
'Show recommended only':'عرض المقترح فقط','Show all 3 per slot':'عرض البدائل الثلاثة','🏛 Historical & cultural':'🏛 تاريخي وثقافي','🎭 Dining · shopping · leisure':'🎭 مطاعم · تسوق · ترفيه',
'BOOKING DEADLINE MODE':'وضع الحجز العاجل','Lock the flight, first stay and car before anything else.':'ثبّتوا الرحلة والإقامة الأولى والسيارة قبل أي شيء آخر.','The plan is still carrying two possible date sets. Choose the correct one before opening any non-refundable checkout.':'الخطة تتضمن مجموعتين محتملتين من التواريخ. اختاروا الصحيح قبل فتح أي حجز غير قابل للاسترداد.',
'Urgent option · depart Thu 17 Sep, return Thu 24 Sep':'الخيار العاجل · المغادرة الخميس 17 سبتمبر والعودة الخميس 24 سبتمبر','Original option · depart Fri 18 Sep, return Fri 25 Sep':'الخيار الأصلي · المغادرة الجمعة 18 سبتمبر والعودة الجمعة 25 سبتمبر',
'✈ FLIGHT':'✈ الرحلة','🚙 SUV':'🚙 السيارة','🛏 STAYS':'🛏 الإقامات','✓ ACTIVITIES':'✓ الأنشطة','Exact model + full cover required':'الطراز المحدد + تأمين كامل مطلوب','blocks selected':'فترات مختارة','timeslots selected':'فترات نشاط مختارة','One choice per active timeslot':'خيار واحد لكل فترة نشطة',
'Book-now checklist':'قائمة الحجز الآن','Selected-plan brief':'ملخص الخطة المختارة','Copy booking brief':'نسخ ملخص الحجز','✓ Copied':'✓ تم النسخ',
'Confirm whether departure is Thu 17 or Fri 18 September':'تأكيد ما إذا كانت المغادرة الخميس 17 أو الجمعة 18 سبتمبر','Book one protected flight itinerary or accept self-connect risk explicitly':'حجز مسار جوي محمي بتذكرة واحدة أو قبول مخاطر الربط الذاتي بوضوح','Reserve the first two nights in Tunis':'حجز أول ليلتين في تونس','Reserve two nights in Sousse / Kairouan':'حجز ليلتين في سوسة / القيروان','Reserve two nights in Hammamet':'حجز ليلتين في الحمامات','Reserve the final night near Sidi Bou Said / Tunis airport':'حجز الليلة الأخيرة قرب سيدي بوسعيد / مطار تونس','Reserve the luxury SUV with automatic transmission and full insurance':'حجز سيارة SUV فاخرة أوتوماتيكية مع تأمين كامل','Confirm airport pickup, accessible room/stairs and luggage handling':'تأكيد الاستقبال من المطار وسهولة الوصول للغرفة والسلالم وحمل الأمتعة','Buy travel insurance and save passports, confirmations and emergency contacts':'شراء تأمين السفر وحفظ الجوازات والتأكيدات وأرقام الطوارئ','Call the top restaurants / guides to confirm next-day availability':'الاتصال بأفضل المطاعم والمرشدين لتأكيد توفر اليوم التالي',
'Automatic browser import is not connected yet.':'الاستيراد التلقائي من المتصفح غير متصل بعد.','Paste the newest WhatsApp group messages or listing links here now. After connecting the suggested browser connector in ChatGPT, the same panel can be populated directly from the open group.':'الصقوا الآن أحدث رسائل مجموعة واتساب أو روابط الإعلانات. بعد توصيل أداة المتصفح المقترحة في ChatGPT، يمكن تعبئة اللوحة مباشرة من المجموعة المفتوحة.',
'Import group suggestions':'استيراد اقتراحات المجموعة','No WhatsApp group suggestions imported yet.':'لم يتم استيراد اقتراحات من مجموعة واتساب بعد.','WHATSAPP GROUP':'مجموعة واتساب','WhatsApp suggestion':'اقتراح واتساب','Needs verification':'يحتاج تحققًا','Shared by the group':'مشارك من المجموعة','Remove':'حذف',
'Tunis · first two nights':'تونس · أول ليلتين','Nights 1–2':'الليلتان 1–2','MEDINA / PRIVATE DAR':'المدينة العتيقة / دار خاصة','Sousse / Kairouan · two nights':'سوسة / القيروان · ليلتان','Nights 3–4':'الليلتان 3–4','CENTRAL TUNISIA BASE':'قاعدة وسط تونس','Hammamet · two beach nights':'الحمامات · ليلتان على الشاطئ','Nights 5–6':'الليلتان 5–6','PRIVATE BEACH STAY':'إقامة شاطئية خاصة','Sidi Bou Said / Tunis · final night':'سيدي بوسعيد / تونس · الليلة الأخيرة','Night 7':'الليلة 7','FINAL COASTAL / AIRPORT BASE':'قاعدة ساحلية أخيرة / قرب المطار',
'Arrival day':'يوم الوصول','Fly Riyadh → Tunis + late check-in':'الطيران من الرياض إلى تونس + دخول متأخر','Tunis day 2':'اليوم الثاني في تونس','Tunis history, food and local shopping':'تاريخ تونس وطعامها والتسوق المحلي','Central day 1':'اليوم الأول في وسط تونس','Tunis → Kairouan → Sousse':'تونس ← القيروان ← سوسة','Central day 2':'اليوم الثاني في وسط تونس','Sousse / Monastir / Kairouan choices':'خيارات سوسة / المنستير / القيروان','Beach transfer':'الانتقال إلى الشاطئ','El Jem or Mahdia → Hammamet':'الجم أو المهدية ← الحمامات','Hammamet day':'يوم الحمامات','Hammamet, Nabeul and beach time':'الحمامات ونابل ووقت الشاطئ','Final Tunis day':'اليوم الأخير في تونس','Return north + Sidi Bou Said / Tunis':'العودة شمالًا + سيدي بوسعيد / تونس','Departure day':'يوم المغادرة','Airport + Riyadh':'المطار + الرياض',
'YOUR CURRENT FLIGHT PICK':'اختيار الرحلة الحالي','YOUR CURRENT CAR PICK':'اختيار السيارة الحالي','BEST MATCH TO 4 PM':'الأقرب لمغادرة 4 مساءً','BEST LUXURY FIT':'أفضل ملاءمة فاخرة','MOST PRESTIGIOUS':'الأكثر فخامة','Luxury':'الفخامة','Skip this slot':'تخطي هذه الفترة','Open / book ↗':'فتح / حجز ↗','Choose':'اختيار','✓ Selected':'✓ تم الاختيار',
'Arrival night · choose 1':'ليلة الوصول · اختر 1','Late arrival food · choose 1':'طعام الوصول المتأخر · اختر 1','Tunis morning anchor · choose 1':'المحطة الأساسية صباحًا في تونس · اختر 1','Late morning · choose 1':'آخر الصباح · اختر 1','Tunis lunch · choose 1':'غداء تونس · اختر 1','Mother’s shopping block · choose 1':'فترة تسوق الوالدة · اختر 1','Tunis evening · choose 1':'مساء تونس · اختر 1','Kairouan morning · choose 1':'صباح القيروان · اختر 1','Kairouan lunch · choose 1':'غداء القيروان · اختر 1','Sousse arrival · choose 1':'الوصول إلى سوسة · اختر 1','Sousse dinner · choose 1':'عشاء سوسة · اختر 1','Central Tunisia morning · choose 1':'صباح وسط تونس · اختر 1','Central Tunisia lunch · choose 1':'غداء وسط تونس · اختر 1','Central Tunisia afternoon · choose 1':'بعد ظهر وسط تونس · اختر 1','Central Tunisia evening · choose 1':'مساء وسط تونس · اختر 1','El Jem / Mahdia morning · choose 1':'صباح الجم / المهدية · اختر 1','Road-day lunch · choose 1':'غداء يوم الطريق · اختر 1','Hammamet arrival · choose 1':'الوصول إلى الحمامات · اختر 1','Hammamet dinner · choose 1':'عشاء الحمامات · اختر 1','Hammamet / Nabeul morning · choose 1':'صباح الحمامات / نابل · اختر 1','Hammamet / Nabeul lunch · choose 1':'غداء الحمامات / نابل · اختر 1','Hammamet afternoon · choose 1':'بعد ظهر الحمامات · اختر 1','Final regional shopping · choose 1':'التسوق الإقليمي الأخير · اختر 1','Beach-night dinner · choose 1':'عشاء ليلة الشاطئ · اختر 1','Final-day cultural anchor · choose 1':'المحطة الثقافية لليوم الأخير · اختر 1','Final coastal lunch · choose 1':'الغداء الساحلي الأخير · اختر 1','Final shopping buffer · choose 1':'فترة التسوق الأخيرة · اختر 1','Farewell dinner · choose 1':'عشاء الوداع · اختر 1'
};
const rules=[
 [/^(\d+) planned stops(?: · (.+))?$/,(m,n,s)=>`${n} محطات مخطط لها${s?` · ${s}`:''}`],
 [/^(\d+) blocks selected$/,(m,n)=>`${n} فترات مختارة`],
 [/^(\d+) timeslots selected$/,(m,n)=>`${n} فترات نشاط مختارة`],
 [/^Selected overnight:\s*(.+)$/,(m,s)=>`الإقامة المختارة: ${s}`]
];
let applying=false;
function translate(core){if(dict[core])return dict[core];for(const [r,f] of rules){if(r.test(core))return core.replace(r,f)}return core}
function apply(){if(applying||document.documentElement.lang!=='ar')return;applying=true;const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(n){const p=n.parentElement;if(!p||/^(SCRIPT|STYLE|NOSCRIPT|TEXTAREA|OPTION)$/i.test(p.tagName))return NodeFilter.FILTER_REJECT;return n.nodeValue.trim()?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}}),nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{const original=n.__tnOriginal??n.nodeValue;if(n.__tnOriginal===undefined)n.__tnOriginal=original;const core=original.trim(),t=translate(core);if(t!==core){const lead=original.match(/^\s*/)?.[0]||'',trail=original.match(/\s*$/)?.[0]||'';n.nodeValue=lead+t+trail}});document.querySelectorAll('option').forEach(o=>{if(o.__tnOriginal===undefined)o.__tnOriginal=o.textContent;const t=translate(o.__tnOriginal.trim());if(t!==o.__tnOriginal.trim())o.textContent=t});applying=false}
function restore(){if(applying)return;applying=true;document.querySelectorAll('*').forEach(e=>{e.childNodes.forEach(n=>{if(n.nodeType===3&&n.__tnOriginal!==undefined)n.nodeValue=n.__tnOriginal})});document.querySelectorAll('option').forEach(o=>{if(o.__tnOriginal!==undefined)o.textContent=o.__tnOriginal});applying=false}
document.addEventListener('trip-language-change',e=>requestAnimationFrame(()=>{if(e.detail.lang==='ar')apply();else restore()}));new MutationObserver(()=>{if(document.documentElement.lang==='ar')requestAnimationFrame(apply)}).observe(document.body,{childList:true,subtree:true});if(document.documentElement.lang==='ar')apply();
})();