(()=>{
const D=window.TRIP_DATA;if(!D)return;
const cityImgs={tunis:D.images.tunis,hammamet:D.images.hammamet,sidi:D.images.sidi};
const enrich=(o,e,p,v,tier)=>Object.assign(o,{experience:e,privacy:p,priceScore:v,priceTier:tier,score:Math.round(e*5+p*3+v*2)});
const seg=id=>D.staySegments.find(s=>s.id===id);
// Existing options: add the three visible ratings requested by the user.
const existing={
'dar24':[10,10,6,'$$$'],'typical-medina':[10,10,7,'$$$'],'dar-nabiha':[9.8,10,8,'$$'],'dar-saida':[9.5,10,7,'$$$'],'medina-condo':[8.8,10,9,'$$'],
'dar-sandra':[10,10,7,'$$$'],'dar-el-nour':[10,10,8,'$$'],'medina-pool-villa':[9.7,10,5,'$$$$'],'feet-water':[9.6,10,9,'$$'],'perfect-beach':[8.8,10,3,'$$$$$'],'waterfront-villa':[8.4,10,4,'$$$$'],'triplex-pool':[8.3,10,8,'$$$'],
'sidi-authentic':[9.8,10,7,'$$$'],'sidi-etoile':[9.2,10,4,'$$$$'],'sidi-charming':[9.1,10,8,'$$'],'dar24-return':[9.5,10,7,'$$$']};
D.staySegments.forEach(s=>s.options.forEach(o=>{const m=existing[o.id]||[8,9,6,'$$$'];enrich(o,...m)}));
const add=(sid,arr)=>{const s=seg(sid);arr.forEach(o=>{if(!s.options.some(x=>x.id===o.id))s.options.push(o)});s.options.sort((a,b)=>b.score-a.score);s.options=s.options.slice(0,20);s.default=s.options[0].id};
add('tunisRiad',[
 enrich({id:'pearl-medina',name:'The Pearl of the Medina · Authentic Luxury',type:'Entire home',tag:'Guest favorite',hybrid:false,guests:'4 guests · 2 bedrooms',rating:'4.99 · 67 reviews',note:'Very strong private-home option in the old city with a high review score and traditional setting.',lat:36.7984,lng:10.1706,url:'https://www.airbnb.com/rooms/1273014287129551258',images:cityImgs.tunis},9.8,10,7,'$$$'),
 enrich({id:'elmedina-residence',name:'The Elmedina Residence · 19th-century home',type:'Entire home',tag:'Large historic home',hybrid:false,guests:'8 guests · 3 bedrooms',rating:'4.83 · 23 reviews',note:'Restored 19th-century residence for a stronger whole-house feeling.',lat:36.7991,lng:10.1701,url:'https://www.airbnb.com/rooms/1370884196405527362',images:cityImgs.tunis},9.7,10,6,'$$$'),
 enrich({id:'dar-chams',name:'Dar Chams · Medina house + small hammam',type:'Entire home',tag:'Hammam + terrace',hybrid:false,guests:'6 guests · 3 bedrooms',rating:'4.8 · 15 reviews',note:'Renovated Medina home close to Zitouna with terrace and a small traditional hammam.',lat:36.7990,lng:10.1697,url:'https://www.airbnb.com/rooms/1433514110140365390',images:cityImgs.tunis},9.6,10,7,'$$$'),
 enrich({id:'dar-zina',name:'Dar Zina · family home in the Medina',type:'Entire home',tag:'Family friendly',hybrid:false,guests:'4 guests · 2 bedrooms',rating:'4.69 · 54 reviews',note:'Private family-sized stay directly on the Medina tourist route.',lat:36.7978,lng:10.1709,url:'https://www.airbnb.com/rooms/895969011243509417',images:cityImgs.tunis},9.2,10,8,'$$'),
 enrich({id:'beautiful-medina',name:'Beautiful traditional Medina house',type:'Entire home',tag:'Patio house',hybrid:false,guests:'4 guests · 1 bedroom + living',rating:'4.71 · 48 reviews',note:'Traditional patio house in the middle of the Medina.',lat:36.7983,lng:10.1713,url:'https://www.airbnb.com/rooms/1161748366994687978',images:cityImgs.tunis},9.1,10,8,'$$'),
 enrich({id:'guest-medina-apt',name:'Guest Apartment in a restored Arab house',type:'Self-contained apartment',tag:'Best reviews',hybrid:false,guests:'3 guests · 1 bedroom',rating:'4.95 · 388 reviews',note:'Private apartment around a bright patio inside a restored Arab house; entrance is shared.',lat:36.8015,lng:10.1687,url:'https://www.airbnb.com/rooms/1128813',images:cityImgs.tunis},9.0,8,9,'$$'),
 enrich({id:'renovated-arab',name:'Renovated Arab House · Tourbet El Bey',type:'Entire home',tag:'Designer restoration',hybrid:false,guests:'2 guests',rating:'4.79 · 130 reviews',note:'Excellent authenticity but only suitable if you book an additional nearby room for the third traveler.',lat:36.7942,lng:10.1702,url:'https://www.airbnb.com/rooms/717507',images:cityImgs.tunis},9.4,10,8,'$$'),
 enrich({id:'center-2br',name:'Central Tunis 2-bedroom flat near Medina',type:'Entire condo',tag:'Easy access',hybrid:false,guests:'4 guests · 2 bedrooms',rating:'5.0 · 17 reviews',note:'Less atmospheric than a dar, but practical and close to Avenue Habib Bourguiba and the Medina.',lat:36.8035,lng:10.1780,url:'https://www.airbnb.com/rooms/715127335987549636',images:cityImgs.tunis},7.4,10,9,'$$'),
 enrich({id:'airport-groundfloor',name:'Ground-floor family apartment · airport side',type:'Entire apartment',tag:'Mother-friendly',hybrid:false,guests:'4 guests',rating:'4.78 · 18 reviews',note:'Ground-floor, secure and easy with luggage; lower experience score because it is outside the Medina.',lat:36.8280,lng:10.1890,url:'https://www.airbnb.com/rooms/41760517',images:cityImgs.tunis},6.8,10,9,'$$'),
 enrich({id:'dar-bengacem',name:'Dar Ben Gacem · traditional dar',type:'Boutique dar',tag:'Service fallback',hybrid:false,guests:'Book 2 rooms',rating:'Highly rated',note:'Not a whole private house, but one of the strongest authentic Medina experiences if private-home inventory is unavailable.',lat:36.8018,lng:10.1686,url:'https://www.darbengacem.com/',images:cityImgs.tunis},9.8,5,5,'$$$$'),
 enrich({id:'dar-benturkia',name:'Dar Ben Turkia · suites + hammam',type:'Boutique dar',tag:'Best service for mother',hybrid:false,guests:'Book 2 rooms / suite',rating:'Highly rated',note:'Traditional architecture with more hotel-like service and easier comfort.',lat:36.7985,lng:10.1689,url:'https://www.darbenturkia.com/en/home-en-dar-ben-turkia/',images:cityImgs.tunis},9.4,5,5,'$$$$'),
 enrich({id:'dar-el-jeld',name:'Dar El Jeld Hotel & Spa',type:'Historic hotel',tag:'Luxury fallback',hybrid:false,guests:'2 rooms',rating:'Luxury property',note:'Strong architecture and comfort, but lower privacy than an entire home.',lat:36.8006,lng:10.1680,url:'https://www.dareljeld.com/',images:cityImgs.tunis},8.8,4,3,'$$$$$'),
 enrich({id:'dar-el-medina',name:'Dar El Médina',type:'Boutique hotel',tag:'Classic Medina',hybrid:false,guests:'2 rooms',rating:'Established property',note:'Good Medina character with a conventional hospitality setup.',lat:36.8002,lng:10.1690,url:'https://darelmedinatunis.com/',images:cityImgs.tunis},8.7,4,5,'$$$$'),
 enrich({id:'palais-bayram',name:'Palais Bayram',type:'Historic palace hotel',tag:'Most palatial',hybrid:false,guests:'2 rooms / suites',rating:'Historic palace',note:'High experience score for architecture, lower privacy than a whole home.',lat:36.7942,lng:10.1710,url:'https://palaisbayram.com/en/',images:cityImgs.tunis},9.2,4,4,'$$$$'),
 enrich({id:'lac1-apartment',name:'Lac 1 private apartment + parking',type:'Entire condo',tag:'Practical airport option',hybrid:false,guests:'2 guests',rating:'4.89 · 35 reviews',note:'Very easy access to airport and north suburbs, but not the Medina experience.',lat:36.8350,lng:10.2240,url:'https://www.airbnb.com/rooms/614532216119288980',images:cityImgs.tunis},6.4,10,8,'$$')
]);
add('hammametBeach',[
 enrich({id:'auth-home-100m',name:'Authentic vaulted home · 100 m from beach',type:'Entire home',tag:'Traditional + beach',hybrid:true,guests:'6 guests · 2 bedrooms',rating:'New listing',note:'Traditional vaulted interior, private patio and beach access about 100 m away.',lat:36.4065,lng:10.6150,url:'https://www.airbnb.com/rooms/40671339',images:cityImgs.hammamet},9.7,10,9,'$$'),
 enrich({id:'atypical-medina',name:'Atypical Medina house · close to beach',type:'Entire home',tag:'5 bedrooms',hybrid:true,guests:'10 guests · 5 bedrooms',rating:'4.78',note:'Large heritage-forward home near the fort and beach with private patio.',lat:36.3999,lng:10.6144,url:'https://www.airbnb.com/rooms/44019421',images:cityImgs.hammamet},9.3,10,5,'$$$$'),
 enrich({id:'dar-lily',name:'Dar Lily · Arabesque villa + pool',type:'Entire home',tag:'Design + beach',hybrid:true,guests:'8 guests · 4 bedrooms',rating:'4.98 · 48 reviews',note:'Modern design blended with Arabesque character; pool and short drive to beaches.',lat:36.4140,lng:10.6260,url:'https://www.airbnb.com/rooms/1188160876603055835',images:cityImgs.hammamet},9.2,10,4,'$$$$'),
 enrich({id:'ideal-holidays',name:'Single-storey villa · 50 m from beach',type:'Entire villa',tag:'Excellent value beach',hybrid:false,guests:'6 guests · 2 bedrooms',rating:'4.9 · 106 reviews',note:'Very close to the beach, secure residence and practical single-storey layout.',lat:36.4200,lng:10.6450,url:'https://www.airbnb.com/rooms/6581887',images:cityImgs.hammamet},8.7,10,9,'$$'),
 enrich({id:'dar-sadok',name:'Dar Sadok · pool · 300 m from beach',type:'Entire villa',tag:'Family villa',hybrid:true,guests:'10 guests · 4 bedrooms',rating:'4.95 · 42 reviews',note:'Decorated family house with pool and Mediterranean beach access nearby.',lat:36.3850,lng:10.5520,url:'https://www.airbnb.com/rooms/16076008',images:cityImgs.hammamet},8.9,10,6,'$$$'),
 enrich({id:'new-villa-ham',name:'New Villa Hammamet · pool',type:'Entire villa',tag:'Top 10%',hybrid:false,guests:'10 guests · 4 bedrooms',rating:'4.92 · 13 reviews',note:'Quiet secured villa about 8 minutes on foot from the beach.',lat:36.4080,lng:10.5980,url:'https://www.airbnb.com/rooms/1132556202972894132',images:cityImgs.hammamet},8.2,10,7,'$$$'),
 enrich({id:'dar-janna',name:'Villa Dar Janna · 200 m from beach',type:'Entire villa',tag:'Large garden',hybrid:false,guests:'15 guests · 7 bedrooms',rating:'4.48 · 21 reviews',note:'Huge traditional-style family villa close to the beach; oversized for three.',lat:36.4310,lng:10.6720,url:'https://www.airbnb.com/rooms/26003992',images:cityImgs.hammamet},8.0,10,5,'$$$$'),
 enrich({id:'pool-3min',name:'Private pool villa · 3 min from beach',type:'Entire villa',tag:'Pool + hot tub',hybrid:false,guests:'6 guests · 3 bedrooms',rating:'5.0 · 6 reviews',note:'Strong family setup near beach and shops.',lat:36.4180,lng:10.6410,url:'https://www.airbnb.com/rooms/43981027',images:cityImgs.hammamet},7.9,10,7,'$$$'),
 enrich({id:'smart-seaview',name:'Luxury smart villa · panoramic sea view',type:'Entire villa',tag:'Luxury panorama',hybrid:false,guests:'8 guests · 4 suites',rating:'5.0',note:'Private pool and panoramic bay view; experience is luxury rather than traditional.',lat:36.4450,lng:10.6740,url:'https://www.airbnb.com/rooms/1695726963843056186',images:cityImgs.hammamet},8.3,10,2,'$$$$$'),
 enrich({id:'villa-5min',name:'Upscale villa · 5-min walk to beach',type:'Entire villa',tag:'Modern family',hybrid:false,guests:'8 guests · 4 bedrooms',rating:'Strong recent reviews',note:'Modern villa with pool close to beach.',lat:36.4230,lng:10.6500,url:'https://www.airbnb.com/rooms/1245526449934492917',images:cityImgs.hammamet},7.8,10,5,'$$$$'),
 enrich({id:'elite-villa',name:'Elite Villa · La Badira area',type:'Entire home',tag:'Private pool',hybrid:false,guests:'7 guests · 3 bedrooms',rating:'5.0 · 8 reviews',note:'Modern luxury, private pool and about three minutes to beach.',lat:36.4300,lng:10.6800,url:'https://www.airbnb.com/rooms/1708017538541241668',images:cityImgs.hammamet},7.7,10,4,'$$$$'),
 enrich({id:'villa-athena',name:'Villa Athena · pool + hammam + rooftop',type:'Entire home',tag:'Full amenities',hybrid:true,guests:'10 guests · 5 bedrooms',rating:'4.8',note:'Large villa with pool, hammam and rooftop sea view, about 500 m from beach.',lat:36.4140,lng:10.6060,url:'https://www.airbnb.com/rooms/964410154431144201',images:cityImgs.hammamet},8.6,10,3,'$$$$$'),
 enrich({id:'private-beach-garden',name:'Private beach + pool + garden',type:'Entire home',tag:'Direct beach feel',hybrid:false,guests:'10 guests · 3 bedrooms',rating:'4.6 · 5 reviews',note:'Private pool, garden and access to private beach.',lat:36.3700,lng:10.5350,url:'https://www.airbnb.com/rooms/1372884089781513228',images:cityImgs.hammamet},8.0,10,4,'$$$$')
]);
add('finalHybrid',[
 enrich({id:'sidi-traditional',name:'Dar Saydouna · Sidi Bou Said Traditional House',type:'Entire home',tag:'Best finale',hybrid:true,guests:'7 guests · 3 bedrooms',rating:'4.93 · 191 reviews',note:'Centuries-old traditional house around a patio with panoramic rooftop Gulf views.',lat:36.8702,lng:10.3416,url:'https://www.airbnb.com/rooms/21562961',images:cityImgs.sidi},10,10,7,'$$$'),
 enrich({id:'dar-mima',name:'Dar Mima · 300-year-old house + rooftop jacuzzi',type:'Entire home',tag:'Heritage + sea',hybrid:true,guests:'7 guests · 3 bedrooms',rating:'4.9 · 20 reviews',note:'A preserved 300-year-old Sidi Bou Said home with sea-view rooftop.',lat:36.8701,lng:10.3420,url:'https://www.airbnb.com/rooms/1494928392825293570',images:cityImgs.sidi},10,10,5,'$$$$'),
 enrich({id:'dar-el-aalia',name:'Dar El Aalia · sea-view Tunisian home',type:'Entire home',tag:'Authentic + modern',hybrid:true,guests:'4 guests · 2 bedrooms',rating:'4.91 · 11 reviews',note:'Authentic Tunisian charm, panoramic views and excellent village location.',lat:36.8705,lng:10.3424,url:'https://www.airbnb.com/rooms/1466507728164592194',images:cityImgs.sidi},9.7,10,7,'$$$'),
 enrich({id:'el-dar',name:'EL Dar · secular Sidi Bou Said residence',type:'Entire home',tag:'Big heritage home',hybrid:true,guests:'12 guests · 5 bedrooms',rating:'4.94 · 47 reviews',note:'Large heritage residence in the center of the Andalusian village with panoramic views.',lat:36.8697,lng:10.3412,url:'https://www.airbnb.com/rooms/725799215798835823',images:cityImgs.sidi},9.8,10,3,'$$$$$'),
 enrich({id:'shand',name:'SHAND · family house in Sidi Bou Said',type:'Entire home',tag:'Beach 5 min',hybrid:true,guests:'6 guests · 4 bedrooms',rating:'4.96 · 24 reviews',note:'Spacious quiet family home in the village, about five minutes from the beach.',lat:36.8690,lng:10.3405,url:'https://www.airbnb.com/rooms/700431184400251469',images:cityImgs.sidi},9.3,10,7,'$$$'),
 enrich({id:'villa-verde',name:'Villa Verde · traditional-contemporary Sidi house',type:'Entire home',tag:'Pool + hot tub',hybrid:true,guests:'8 guests · 4 suites',rating:'4.94 · 31 reviews',note:'Traditional charm with contemporary design, pool and hot tub.',lat:36.8707,lng:10.3410,url:'https://www.airbnb.com/rooms/1395668710372631557',images:cityImgs.sidi},9.1,10,3,'$$$$$'),
 enrich({id:'ethnic-villa',name:'Chic Exotic Villa · 180° sea view',type:'Entire home',tag:'Cliffside view',hybrid:true,guests:'4 guests · 2 bedrooms',rating:'4.94 · 33 reviews',note:'Mediterranean architecture, cliffside position and quick beach/harbor access.',lat:36.8710,lng:10.3440,url:'https://www.airbnb.com/rooms/31383966',images:cityImgs.sidi},9.1,10,5,'$$$$'),
 enrich({id:'villa-sidi',name:'Villa Sidi Bou Said · character house',type:'Entire home',tag:'Typical architecture',hybrid:true,guests:'4 guests · 2 bedrooms',rating:'4.95 · 43 reviews',note:'Character house renovated to respect typical village architecture and comfort.',lat:36.8695,lng:10.3427,url:'https://www.airbnb.com/rooms/42252314',images:cityImgs.sidi},9.3,10,7,'$$$'),
 enrich({id:'auth-sidi-10min',name:'Authentic Sidi experience · 10 min to beach',type:'Entire home',tag:'Great location',hybrid:true,guests:'5 guests · 2 bedrooms',rating:'4.87 · 116 reviews',note:'Authentic village house close to everything with very strong location feedback.',lat:36.8698,lng:10.3417,url:'https://www.airbnb.com/rooms/1173280278343265795',images:cityImgs.sidi},9.2,10,8,'$$'),
 enrich({id:'dar-soltane',name:'Dar Soltane · heritage bungalow by the sea',type:'Entire home',tag:'Heritage + port',hybrid:true,guests:'4 guests · 2 bedrooms',rating:'4.8 · 97 reviews',note:'Tunisian heritage dar a few meters from the port with a strong local atmosphere.',lat:36.8730,lng:10.3500,url:'https://www.airbnb.com/rooms/17401284',images:cityImgs.sidi},9.5,10,8,'$$'),
 enrich({id:'villa-oliviers',name:'Villa des Oliviers · sea views from every opening',type:'Entire villa',tag:'Sea-view design',hybrid:true,guests:'4 guests · 2 bedrooms',rating:'4.9',note:'Bright Sidi Bou Said villa with mashrabiya details and sea views.',lat:36.8708,lng:10.3431,url:'https://www.airbnb.com/rooms/44830151',images:cityImgs.sidi},9.0,10,5,'$$$$'),
 enrich({id:'red-cliff',name:'Red Cliff · Amilcar sea-view villa',type:'Entire home',tag:'Pool + bay view',hybrid:true,guests:'12 guests · 5 bedrooms',rating:'5.0 · 5 reviews',note:'Private pool, garden and panoramic Amilcar Bay view; luxury rather than intimate.',lat:36.8780,lng:10.3400,url:'https://www.airbnb.com/rooms/13168747',images:cityImgs.sidi},8.8,10,2,'$$$$$'),
 enrich({id:'dar-sophia',name:'Dar Sophia · 6BR sea-view villa',type:'Entire villa',tag:'Panoramic luxury',hybrid:true,guests:'12 guests · 6 bedrooms',rating:'5.0',note:'Large hilltop villa with pool and major panoramic view.',lat:36.8708,lng:10.3438,url:'https://www.airbnb.com/rooms/1436107521366321685',images:cityImgs.sidi},8.7,10,1,'$$$$$'),
 enrich({id:'la-marsa-home',name:'La Marsa garden home close to sea',type:'Entire home',tag:'Family + pool',hybrid:true,guests:'13 guests · 4 bedrooms',rating:'4.89 · 106 reviews',note:'Quiet garden home with pool between La Marsa, Sidi Bou Said and Gammarth.',lat:36.8810,lng:10.3220,url:'https://www.airbnb.com/rooms/3370990',images:cityImgs.sidi},8.2,10,5,'$$$$'),
 enrich({id:'la-marsa-duplex',name:'La Marsa duplex close to sea',type:'Entire home',tag:'Practical coastal',hybrid:true,guests:'6 guests · 3 bedrooms',rating:'4.91',note:'Quiet guarded duplex with garden/courtyard close to Sidi Bou Said and Gammarth.',lat:36.8840,lng:10.3210,url:'https://www.airbnb.com/rooms/5989213',images:cityImgs.sidi},7.9,10,8,'$$$'),
 enrich({id:'large-sidi',name:'Large house in Sidi Bou Said',type:'Entire home',tag:'Simple local option',hybrid:true,guests:'3 guests · 1 bedroom',rating:'No reviews',note:'Secure residence, about 10 minutes to beach and minutes from Carthage and La Marsa.',lat:36.8655,lng:10.3375,url:'https://www.airbnb.com/rooms/42561956',images:cityImgs.sidi},7.5,10,9,'$$')
]);
// 20 outbound candidates. Price is an indicative round-trip benchmark/range, not a locked fare.
D.flightSources=[
 ['Google Flights RUH–TUN','https://www.google.com/travel/flights/flights-from-riyadh-to-tunis.html'],['Turkish Airlines RUH–TUN','https://www.turkishairlines.com/en-sa/flights-from-riyadh-to-tunis'],['Etihad RUH–TUN','https://www.etihad.com/en-sa/flights/flights-from-riyadh-to-tunis'],['Royal Jordanian schedule','https://www.flight.info/RJ737'],['Qatar RUH–DOH schedules','https://www.flight.info/QR1165'],['EgyptAir RUH–CAI schedule','https://www.flight.info/MS690'],['Emirates RUH–DXB schedule','https://www.flight.info/EK818'],['Saudia JED–TUN schedule','https://www.flight.info/SV365']
];
const F=(id,name,route,depart,arrive,duration,price,ps,ds,ts,tag,book,note,self=false)=>({id,name,route,depart,arrive,duration,price,priceScore:ps,durationScore:ds,timingScore:ts,tag,book,note,self,overall:Math.round(ps*3+ds*3+ts*4)});
D.flights=[
 F('rj-evening','Royal Jordanian evening via Amman','RUH → AMM → TUN','Fri 20:15','Sat 02:15','~8h 00m','≈ SAR 1,775+ benchmark',10,10,10,'BEST OVERALL','https://www.rj.com/','Best alignment with Jumu’ah preference: late departure, short total journey and a strong current price benchmark.'),
 F('xy-tk-ist','Flynas + Turkish via Istanbul','RUH → IST → TUN','Fri 16:05','Fri 22:45','~8h 40m','Check live · separate tickets',7,9,10,'FAST AFTER JUMU’AH','https://www.google.com/travel/flights','Excellent timing and duration, but likely a self-connect: baggage/recheck and delay protection must be checked.',true),
 F('xy-tu-jed','Flynas + Tunisair via Jeddah','RUH → JED → TUN','Fri 23:05','Sat 06:25','~9h 20m','Check live · often value-led',8,9,8,'LATE-NIGHT VALUE','https://www.google.com/travel/flights','Strong after-prayer timing with a compact overnight connection; likely separate-ticket risk.',true),
 F('ek-evening','Emirates evening via Dubai','RUH → DXB → TUN','Fri 20:25','Sat 11:55','~17h 30m','≈ SAR 3,130+ benchmark',5,5,10,'COMFORTABLE TIMING','https://www.emirates.com/sa/english/destinations/ruh/tun/flights-from-riyadh-to-tunis/','Very easy Friday timing and a protected one-airline journey, but a long overnight Dubai layover.'),
 F('ms-late','EgyptAir late via Cairo','RUH → CAI → TUN','Fri 22:20','Sat 10:00','~13h 40m','≈ SAR 2,600+ benchmark',7,7,9,'GOOD LATE OPTION','https://www.egyptair.com/','Late departure after Jumu’ah with an overnight Cairo connection.'),
 F('f3-ms','flyadeal + EgyptAir via Cairo','RUH → CAI → TUN','Fri 22:55','Sat 10:00','~13h 05m','Check live · mixed carriers',8,7,9,'LOW-COST MIX','https://www.google.com/travel/flights','Potentially cheaper, but separate-ticket / baggage protection needs careful checking.',true),
 F('qr-afternoon','Qatar Airways 15:30 via Doha','RUH → DOH → TUN','Fri 15:30','Sat ~13:20','~23h 50m','≈ SAR 2,190+ benchmark',8,3,10,'BEST QATAR TIMING','https://www.qatarairways.com/','Excellent post-Jumu’ah departure; drawback is the overnight Doha wait before the Tunis flight.'),
 F('qr-evening','Qatar Airways 18:20 via Doha','RUH → DOH → TUN','Fri 18:20','Sat ~13:20','~21h 00m','≈ SAR 2,190+ benchmark',8,4,10,'EVENING QATAR','https://www.qatarairways.com/','Comfortable Friday timing; still a long overnight connection.'),
 F('qr-late','Qatar Airways 21:40 via Doha','RUH → DOH → TUN','Fri 21:40','Sat ~13:20','~17h 40m','≈ SAR 2,190+ benchmark',8,5,9,'LATE QATAR','https://www.qatarairways.com/','Later departure reduces the Doha layover compared with afternoon Qatar options.'),
 F('ms-afternoon','EgyptAir 16:00 via Cairo','RUH → CAI → TUN','Fri 16:00','Sat 10:00','~20h 00m','≈ SAR 2,600+ benchmark',7,4,10,'AFTER JUMU’AH','https://www.egyptair.com/','Good departure timing but a long overnight Cairo layover.'),
 F('ey-overnight','Etihad via Abu Dhabi','RUH → AUH → TUN','Fri evening / overnight','Sun 06:25 on direct AUH–TUN operating day','Long / date-sensitive','≈ SAR 6,000+ on Sep benchmarks',2,3,8,'PRICEY / DATE-SENSITIVE','https://www.etihad.com/en-sa/flights/flights-from-riyadh-to-tunis','Etihad’s direct AUH–TUN frequency is not daily in this schedule window, so exact connection may shift travel date.'),
 F('tk-early-fast','Turkish Airlines early via Istanbul','RUH → IST → TUN','Fri 01:45','Fri ~09:00','~9h 15m','≈ SAR 1,900–2,300',9,9,1,'FAST BUT BEFORE JUMU’AH','https://www.turkishairlines.com/en-sa/flights-from-riyadh-to-tunis','One of the strongest price/duration choices, but it conflicts with the preferred Friday-after-prayer departure.'),
 F('ek-early-fast','Emirates early via Dubai','RUH → DXB → TUN','Fri 04:00','Fri 11:55','~9h 55m','≈ SAR 3,130+ benchmark',5,9,1,'FAST EMIRATES','https://www.emirates.com/sa/english/destinations/ruh/tun/flights-from-riyadh-to-tunis/','Efficient same-day arrival, but leaves long before Friday prayer.'),
 F('rj-early-fast','Royal Jordanian early via Amman','RUH → AMM → TUN','Fri 06:10','Fri 12:35','~8h 25m','≈ SAR 1,775+ benchmark',10,10,2,'CHEAP + FAST','https://www.rj.com/','Excellent journey time and price benchmark, but not compatible with the Jumu’ah preference.'),
 F('qr-early-fast','Qatar Airways early via Doha','RUH → DOH → TUN','Fri 05:00','Fri ~13:20','~10h 20m','≈ SAR 2,190+ benchmark',8,9,1,'FAST QATAR','https://www.qatarairways.com/','Reasonable same-day duration but far too early for the preferred Friday schedule.'),
 F('sv-ist-mix','Saudia + Turkish via Istanbul','RUH → IST → TUN','Fri 10:35','Fri 22:45','~14h 10m','Check live · mixed carrier',7,6,3,'MIXED ISTANBUL','https://www.google.com/travel/flights','Can work as a mixed-carrier Istanbul route; verify through-ticketing and minimum connection time.',true),
 F('xy-tu-ist','Flynas + Tunisair via Istanbul','RUH → IST → TUN','Fri 16:05','Sat 04:45','~14h 40m','Check live · separate tickets',7,6,10,'AFTER JUMU’AH + IST','https://www.google.com/travel/flights','Good Friday departure but a late-night Istanbul self-connect.',true),
 F('rj-midday-long','Royal Jordanian midday via Amman','RUH → AMM → TUN','Fri 10:55','Sat 02:15','~17h 20m','≈ SAR 1,775+ benchmark',10,5,3,'CHEAP / LONG LAYOVER','https://www.rj.com/','Low price benchmark but misses the morning Tunis connection and departs before Jumu’ah.'),
 F('ek-midday-long','Emirates 09:45 via Dubai','RUH → DXB → TUN','Fri 09:45','Sat 11:55','~28h 10m','≈ SAR 3,130+ benchmark',5,1,2,'LONGEST EMIRATES','https://www.emirates.com/sa/english/destinations/ruh/tun/flights-from-riyadh-to-tunis/','Included for completeness; poor timing and an excessive overnight connection.'),
 F('sv-jed-early','Saudia via Jeddah','RUH → JED → TUN','Fri early morning','Fri / Sat depending connection','~8–12h candidate','Check live',7,8,1,'SAUDIA NETWORK','https://www.saudia.com/','Saudia has frequent RUH–JED service and daily JED–TUN SV365; exact Friday connection must be checked live before booking.')
].sort((a,b)=>b.overall-a.overall);
})();