const {test,expect}=require('@playwright/test');
const URL='http://127.0.0.1:4173/tunis-trip/';
async function ready(page){await page.goto(URL,{waitUntil:'domcontentloaded'});await expect(page.locator('#tripMap')).toBeVisible();await expect(page.locator('#flightOptions .flight-card')).toHaveCount(20);await expect(page.locator('#carOptions .car-card')).toHaveCount(20);await expect(page.locator('#staySegments .stay-segment')).toHaveCount(3);await expect(page.locator('#urgentBooking')).not.toBeEmpty()}

test('01 layout order remains map calendar booking configuration',async({page})=>{await ready(page);const o=await page.evaluate(()=>['map','calendar','book-now','configure'].map(id=>document.getElementById(id).getBoundingClientRect().top+scrollY));expect(o[0]).toBeLessThan(o[1]);expect(o[1]).toBeLessThan(o[2]);expect(o[2]).toBeLessThan(o[3]);await expect(page.locator('.bottom-nav a')).toHaveCount(4)});

test('02 route now starts with Friday night flight and Saturday Tunis arrival',async({page})=>{await ready(page);await expect(page.locator('.urgent-summary')).toContainText('night departure Fri 18 Sep');await expect(page.locator('.urgent-summary')).toContainText('Tunis Sat morning');await expect(page.locator('#schedule .day-card')).toHaveCount(8);await expect(page.locator('#schedule .day-card').nth(0)).toContainText('Night flight from Riyadh');await expect(page.locator('#schedule .day-card').nth(1)).toContainText('Arrive Tunis');await expect(page.locator('#schedule .day-card').nth(1)).toContainText('Tunis–Carthage Airport arrival')});

test('03 top flight is night departure with Saturday early-morning arrival',async({page})=>{await ready(page);const cards=page.locator('#flightOptions .flight-card');await expect(cards.first()).toContainText('Royal Jordanian');await expect(cards.first()).toContainText('Fri 20:15');await expect(cards.first()).toContainText('Sat 02:15');await expect(page.locator('#flightSelected')).toContainText('Royal Jordanian');await expect(page.locator('#flightSelected')).toContainText('Fri 20:15');await expect(page.locator('#flightSelected')).toContainText('Sat 02:15')});

test('04 Jeddah and Istanbul alternatives are visible with risk context',async({page})=>{await ready(page);const cards=page.locator('#flightOptions .flight-card');await expect(cards.nth(1)).toContainText('Jeddah');await expect(cards.nth(1)).toContainText('self-transfer');await expect(cards.nth(2)).toContainText('Turkish Airlines');await expect(cards.nth(2)).toContainText('Sat 01:45');await expect(cards.nth(2)).toContainText('Sat ~09:00')});

test('05 flight choice persists after reload',async({page})=>{await ready(page);const cards=page.locator('#flightOptions .flight-card'),name=(await cards.nth(2).locator('h4').textContent()).trim();await cards.nth(2).locator('.choose-flight').click();await expect(page.locator('#flightSelected')).toContainText(name);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#flightSelected')).toContainText(name)});

test('06 three stay blocks match Tunis central Tunisia and Hammamet',async({page})=>{await ready(page);const s=page.locator('#staySegments .stay-segment');await expect(s).toHaveCount(3);await expect(s.nth(0)).toContainText('Tunis');await expect(s.nth(0)).toContainText('19–20 Sep');await expect(s.nth(1)).toContainText('Sousse / Kairouan');await expect(s.nth(1)).toContainText('21–22 Sep');await expect(s.nth(2)).toContainText('Hammamet');await expect(s.nth(2)).toContainText('23–24 Sep');for(let i=0;i<3;i++){expect(await s.nth(i).locator('.stay-card').count()).toBeGreaterThanOrEqual(20);await expect(s.nth(i).locator('.stay-card').first().locator('.stay-metrics>div')).toHaveCount(3)}});

test('07 choosing a stay updates calendar and survives reload',async({page})=>{await ready(page);const o=page.locator('#staySegments .stay-segment').nth(1).locator('.stay-card').nth(1),n=(await o.locator('h3').textContent()).trim();await o.locator('.choose-stay').click();await expect(page.locator('#schedule')).toContainText(n);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#schedule')).toContainText(n)});

test('08 luxury SUV shortlist is intact and locally verified Prado is promoted',async({page})=>{await ready(page);const c=page.locator('#carOptions .car-card');await expect(c).toHaveCount(20);await expect(c.nth(0)).toContainText('BMW X5');await expect(c.nth(1)).toContainText('Range Rover');await expect(c.nth(2)).toContainText('Land Cruiser Prado');await expect(c.nth(2)).toContainText('VIPCAR');const src=await c.locator('.car-photo').evaluateAll(x=>x.map(i=>i.src));expect(new Set(src).size).toBe(20)});

test('09 activities retain 28 timeslots and three alternatives per slot',async({page})=>{await ready(page);const g=page.locator('.slot-group'),c=page.locator('.slot-group .choice-card');await expect(g).toHaveCount(28);await expect(c).toHaveCount(84);for(let i=0;i<28;i++)await expect(g.nth(i).locator('.choice-card')).toHaveCount(3);const src=await c.locator('.photo-rail img').evaluateAll(x=>x.map(i=>i.src));expect(new Set(src).size/src.length).toBeGreaterThan(.95)});

test('10 activity selection replaces same-slot choice and changes calendar',async({page})=>{await ready(page);await page.locator('.tab[data-tab="leisure"]').click();const g=page.locator('#leisureList .slot-group').first(),c=g.locator('.choice-card'),n=(await c.nth(1).locator('h3').textContent()).trim();await c.nth(1).locator('.choice-toggle').click();await expect(g.locator('.selected-choice')).toHaveCount(1);await expect(page.locator('#schedule')).toContainText(n)});

test('11 WhatsApp importer adds persists and removes a stay suggestion',async({page})=>{await ready(page);await page.locator('#waSegment').selectOption('centralBase');await page.locator('#waInput').fill('Group stay https://example.com/group-stay');await page.locator('#waImport').click();await expect(page.locator('.wa-suggestion')).toContainText('Group stay');await expect(page.locator('#staySegments .stay-segment').nth(1)).toContainText('WHATSAPP GROUP');await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('.wa-suggestion')).toContainText('Group stay');await page.locator('[data-remove-wa]').click();await expect(page.locator('.wa-suggestion')).toHaveCount(0)});

test('12 map controls day filters and popups work',async({page})=>{await ready(page);await expect(page.locator('#topDays .day-chip')).toHaveCount(9);const r=page.locator('#routesToggle'),p=page.locator('#pinsToggle');await r.click();await expect(r).not.toHaveClass(/active/);await r.click();await p.click();await expect(p).not.toHaveClass(/active/);await p.click();await page.locator('#topDays .day-chip[data-day="D4"]').click();const markers=page.locator('#tripMap .leaflet-marker-icon');await expect.poll(async()=>markers.count(),{timeout:10000}).toBeGreaterThan(3);await markers.first().dispatchEvent('click');await expect(page.locator('.leaflet-popup-content')).toBeVisible()});

test('13 mobile view has no overflow and booking navigation works',async({page})=>{await page.setViewportSize({width:390,height:844});await ready(page);await expect(page.locator('.bottom-nav')).toBeVisible();await expect(page.locator('.bottom-nav a')).toHaveCount(4);expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(2);await page.locator('.bottom-nav a').nth(2).click();await expect(page.locator('#book-now')).toBeInViewport()});

test('14 Arabic switcher translates the night-flight plan and persists',async({page})=>{await ready(page);const t=page.locator('.topbar [data-language-toggle]');await t.click();await expect(page.locator('html')).toHaveAttribute('lang','ar');await expect(page.locator('html')).toHaveAttribute('dir','rtl');await expect(page.locator('h1')).toContainText('رحلة ليلية');await expect(page.locator('#configure-flights .flight-note')).toContainText('الملكية الأردنية');await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('html')).toHaveAttribute('lang','ar');await page.evaluate(()=>document.querySelector('.topbar [data-language-toggle]').click());await expect(page.locator('html')).toHaveAttribute('lang','en')});

test('15 no uncaught JavaScript errors and external links are hardened',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(String(e)));await ready(page);await page.locator('#topDays .day-chip[data-day="D6"]').click();await page.locator('.tab[data-tab="leisure"]').click();await page.locator('#recommendedBtn').click();await page.locator('#recommendedBtn').click();await page.waitForTimeout(800);expect(errors).toEqual([]);const links=page.locator('a[target="_blank"]');expect(await links.count()).toBeGreaterThan(30);expect(await links.evaluateAll(a=>a.filter(x=>!/^https:\/\//i.test(x.href)||!x.rel.split(/\s+/).includes('noopener')).map(x=>x.outerHTML))).toEqual([])});
