(()=>{
const D=window.TRIP_DATA;if(!D)return;
const WA_KEY='tn-wa-suggestions-v1',CHECK_KEY='tn-booking-checklist-v1',DATE_KEY='tn-date-preset-v1';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeUrl=u=>/^https:\/\//i.test(u||'');
const shot=url=>`https://image.thum.io/get/width/900/crop/650/noanimate/${encodeURIComponent(url)}`;
const coords={tunisRiad:[36.7986,10.171],centralBase:[35.8268,10.6378],hammametBeach:[36.405,10.608],finalHybrid:[36.87,10.342]};
const checklistLabels=[
 'Confirm the primary dates: Fri 18 Sep to Fri 25 Sep',
 'Book the 16:05 Istanbul pattern only if the full journey is one protected PNR',
 'If the Istanbul through-fare is unavailable, compare the protected Turkish, Doha and Amman fallbacks',
 'Reserve the first two nights in Tunis',
 'Reserve two nights in Sousse / Kairouan — preferably one night in each if packing is acceptable',
 'Reserve two beach nights in Hammamet',
 'Reserve the final night near Sidi Bou Said / Tunis airport',
 'Reserve the exact luxury SUV with automatic transmission, unlimited mileage and full insurance',
 'Confirm airport pickup, room stairs/accessibility and luggage handling for your mother',
 'Import or paste the latest WhatsApp group stay suggestions and verify each one',
 'Buy travel insurance and save passports, confirmations and emergency contacts',
 'Call the top restaurants / guides to confirm next-day availability'
];
let checklist=JSON.parse(localStorage.getItem(CHECK_KEY)||'{}');
function selectedStay(id){return window.TRIP_APP?.stayBySegment(id)||null}
function selectedFlight(){const id=localStorage.getItem('tn-flight-v1');return D.flights?.find(x=>x.id===id)||D.flights?.[0]}
function selectedCarName(){return document.querySelector('#carSelected h4')?.textContent?.trim()||'Not selected yet'}
function selectedActivities(){return window.TRIP_APP?D.activities.filter(a=>window.TRIP_APP.state.activities[a.id]):[]}
function activeDatePreset(){const id=localStorage.getItem(DATE_KEY)||'original';return D.datePresets?.find(x=>x.id===id)||D.datePresets?.[0]}
function buildBrief(){const date=activeDatePreset(),f=selectedFlight(),stays=D.staySegments.map(s=>`${s.label}: ${selectedStay(s.id)?.name||'Not selected'}`),grouped=new Map(),actLines=[];selectedActivities().forEach(a=>{if(!grouped.has(a.day))grouped.set(a.day,[]);grouped.get(a.day).push(`${a.time} ${a.name}`)});[...grouped].forEach(([day,list])=>actLines.push(`${day}: ${list.join(' | ')}`));return ['TUNISIA BOOKING BRIEF',`Dates: ${date?.label||'Confirm dates'}`,'Travelers: 3 adults',`Flight: ${f?.name||'Not selected'} | ${f?.route||''} | ${f?.depart||''} → ${f?.arrive||''}`,`Car: ${selectedCarName()}`,...stays,'Selected activities:',...actLines].join('\n')}
function renderBookingDashboard(){const host=document.querySelector('#urgentBooking');if(!host)return;const date=activeDatePreset(),flight=selectedFlight(),car=selectedCarName(),stays=D.staySegments.map(s=>({label:s.label,stay:selectedStay(s.id)})),acts=selectedActivities();host.innerHTML=`<div class="deadline-alert"><div><span class="deadline-kicker">BOOKING DEADLINE MODE</span><b>Lock the flight, first Tunis stay and luxury SUV before anything else.</b><p>The primary dates are Fri 18 Sep to Fri 25 Sep. Use the one-day fallback only if the exact flight or stay inventory is no longer bookable.</p></div><select id="datePreset" aria-label="Travel date preset">${(D.datePresets||[]).map(x=>`<option value="${esc(x.id)}" ${x.id===date?.id?'selected':''}>${esc(x.label)}</option>`).join('')}</select></div><div class="booking-summary-grid"><article><span>✈ FLIGHT</span><b>${esc(flight?.name||'Choose a flight')}</b><small>${esc(flight?.depart||'')} → ${esc(flight?.arrive||'')}</small></article><article><span>🚙 SUV</span><b>${esc(car)}</b><small>Exact model + full cover required</small></article><article><span>🛏 STAYS</span><b>${stays.filter(x=>x.stay).length} blocks selected</b><small>${stays.map(x=>esc(x.stay?.name||'Not selected')).join(' · ')}</small></article><article><span>✓ ACTIVITIES</span><b>${acts.length} timeslots selected</b><small>One choice per active timeslot</small></article></div><div class="booking-tools"><div class="booking-checklist"><h3>Book-now checklist</h3>${checklistLabels.map((label,i)=>`<label><input type="checkbox" data-check="${i}" ${checklist[i]?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div><div class="booking-brief"><h3>Selected-plan brief</h3><div id="briefPreview">${buildBrief().replace(/\n/g,'<br>')}</div><button id="copyBrief" class="primary-action">Copy booking brief</button></div></div>`;host.querySelector('#datePreset')?.addEventListener('change',e=>{localStorage.setItem(DATE_KEY,e.target.value);renderBookingDashboard();document.dispatchEvent(new CustomEvent('trip:updated'))});host.querySelectorAll('[data-check]').forEach(cb=>cb.addEventListener('change',()=>{checklist[cb.dataset.check]=cb.checked;localStorage.setItem(CHECK_KEY,JSON.stringify(checklist))}));host.querySelector('#copyBrief')?.addEventListener('click',async e=>{try{await navigator.clipboard.writeText(buildBrief());e.currentTarget.textContent='✓ Copied';setTimeout(()=>e.currentTarget.textContent='Copy booking brief',1600)}catch(err){e.currentTarget.textContent='Select and copy the brief above'}})}
function loadSuggestions(){try{return JSON.parse(localStorage.getItem(WA_KEY)||'[]')}catch(e){return []}}
function saveSuggestions(x){localStorage.setItem(WA_KEY,JSON.stringify(x))}
function uniqueId(){return `wa-${Date.now()}-${Math.random().toString(36).slice(2,7)}`}
function parseSuggestionLines(raw,segment){const lines=String(raw||'').split(/\n+/).map(x=>x.trim()).filter(x=>x.length>4),seen=new Set();return lines.slice(0,60).map(line=>{const url=(line.match(/https?:\/\/[^\s<>"']+/i)||[])[0]||'',clean=line.replace(url,'').replace(/^[\s\-–—:]+|[\s\-–—:]+$/g,'').trim(),key=(url||clean).toLowerCase();if(seen.has(key))return null;seen.add(key);const [lat,lng]=coords[segment]||coords.tunisRiad;return{id:uniqueId(),segment,fromWhatsApp:true,name:clean.slice(0,120)||(url?new URL(url).hostname:'WhatsApp group suggestion'),type:'WhatsApp suggestion',tag:'Needs verification',hybrid:false,guests:'Verify capacity',rating:'Shared by the group',note:line.slice(0,420),lat,lng,url,experience:null,privacy:null,priceScore:null,priceTier:'Verify',score:50,images:[url?shot(url):`data:image/svg+xml;charset=UTF-8,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="900" height="650"><rect width="100%" height="100%" fill="#eaf7f4"/><text x="50%" y="45%" text-anchor="middle" font-family="Arial" font-size="52" fill="#0b6b62">WhatsApp suggestion</text><text x="50%" y="56%" text-anchor="middle" font-family="Arial" font-size="28" fill="#52606d">${clean.slice(0,45)}</text></svg>`)}`]}}).filter(Boolean)}
function addSuggestionToData(o){const s=D.staySegments.find(x=>x.id===o.segment);if(s&&!s.options.some(x=>x.id===o.id))s.options.unshift(o)}
function removeSuggestionFromData(id){D.staySegments.forEach(s=>{s.options=s.options.filter(o=>o.id!==id);if(window.TRIP_APP?.state.stays[s.id]===id)window.TRIP_APP.state.stays[s.id]=s.default})}
function renderWhatsAppPanel(){const host=document.querySelector('#whatsAppImporter');if(!host)return;const items=loadSuggestions();host.innerHTML=`<div class="wa-status"><span>●</span><div><b>The open WhatsApp browser tab is not connected to this planner yet.</b><p>Paste the newest group messages or listing links here now. After connecting a browser connector in ChatGPT, the same shortlist can be populated from the open group without retyping.</p></div></div><div class="wa-import-grid"><select id="waSegment" aria-label="Stay block">${D.staySegments.map(s=>`<option value="${esc(s.id)}">${esc(s.label)}</option>`).join('')}</select><textarea id="waInput" rows="6" placeholder="Paste WhatsApp messages, property names and links — one suggestion per line"></textarea><button id="waImport" class="primary-action">Import group suggestions</button></div><div class="wa-suggestion-list">${items.length?items.map(o=>`<article class="wa-suggestion"><div><span>${esc(D.staySegments.find(s=>s.id===o.segment)?.label||o.segment)}</span><b>${esc(o.name)}</b><p>${esc(o.note)}</p></div><div class="wa-actions">${safeUrl(o.url)?`<a href="${esc(o.url)}" target="_blank" rel="noopener">Open ↗</a>`:''}<button data-remove-wa="${esc(o.id)}">Remove</button></div></article>`).join(''):'<p class="empty-state">No WhatsApp group suggestions imported yet.</p>'}</div>`;host.querySelector('#waImport')?.addEventListener('click',()=>{const segment=host.querySelector('#waSegment').value,imported=parseSuggestionLines(host.querySelector('#waInput').value,segment);if(!imported.length)return;const current=loadSuggestions();imported.forEach(addSuggestionToData);saveSuggestions([...current,...imported]);host.querySelector('#waInput').value='';window.TRIP_APP?.renderStays();window.TRIP_APP?.save();renderWhatsAppPanel();renderBookingDashboard();document.dispatchEvent(new CustomEvent('trip:updated'))});host.querySelectorAll('[data-remove-wa]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.removeWa;saveSuggestions(loadSuggestions().filter(x=>x.id!==id));removeSuggestionFromData(id);window.TRIP_APP?.save();window.TRIP_APP?.renderStays();window.TRIP_APP?.renderSchedule();window.TRIP_APP?.renderMap();renderWhatsAppPanel();renderBookingDashboard()}))}
let timer;function scheduleRender(){clearTimeout(timer);timer=setTimeout(renderBookingDashboard,70)}document.addEventListener('trip:updated',scheduleRender);['#flightSelected','#carSelected','#staySegments','#schedule'].forEach(sel=>{const el=document.querySelector(sel);if(el)new MutationObserver(scheduleRender).observe(el,{childList:true,subtree:true})});renderWhatsAppPanel();renderBookingDashboard();window.TRIP_SUPPORT={renderBookingDashboard,renderWhatsAppPanel,buildBrief,parseSuggestionLines};
})();